"""A high level unified function make api calls"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_acomplete.ipynb.

# %% auto #0
__all__ = ['specs_path', 'ant_spec', 'oai_spec', 'gem_spec', 'vendor_mapping', 'api2spec', 'mk_client',
           'ContextWindowExceededError', 'acomplete']

# %% ../nbs/06_acomplete.ipynb #f2f57253
import nbdev, yaml, json
from dataclasses import dataclass, field, fields
from importlib.resources import files
from fastcore.utils import *
from fastcore.meta import *
from fastspec.spec import *
from fastspec.oapi import *
from fastspec.errors import APIError

from .types import *
from .streaming import *
from .openai_responses import *
from .openai_chat import *
from .anthropic import *
from .gemini import *

# %% ../nbs/06_acomplete.ipynb #08a84488
specs_path = files('fastllm') / 'specs'
ant_spec  = SpecParser.from_openapi(dict2obj(yaml.safe_load((specs_path/'anthropic.yml').read_text())))
oai_spec  = SpecParser.from_openapi(dict2obj(yaml.safe_load((specs_path/'openai.with-code-samples.yml').read_text())))
gem_spec  = SpecParser.from_discovery(dict2obj(json.loads((specs_path/'gemini.json').read_text())))

# %% ../nbs/06_acomplete.ipynb #32ee2546
vendor_mapping = {
    "openai":       ('openai', 'https://api.openai.com/v1', 'OPENAI_API_KEY'),
    "anthropic":    ('anthropic', 'https://api.anthropic.com', 'ANTHROPIC_API_KEY'),
    "gemini":       ('gemini', 'https://generativelanguage.googleapis.com/', 'GEMINI_API_KEY'),
    "openai_chat":  ('openai_chat', 'https://api.openai.com/v1', 'OPENAI_API_KEY'),
    "codex":        ('openai', 'https://chatgpt.com/backend-api/codex', 'CODEX_AUTH_TOKEN'),
    "moonshot":     ('openai_chat', "https://api.moonshot.ai/v1", "MOONSHOT_API_KEY"),
    "deepseek":     ('openai_chat', "https://api.deepseek.com/v1", "DEEPSEEK_API_KEY"),
    "openrouter":   ('openai_chat', "https://openrouter.ai/api/v1", "OPENROUTER_API_KEY"),
    "together":     ('openai_chat', "https://api.together.xyz/v1", "TOGETHER_API_KEY"),
    "fireworks_ai": ('openai_chat', "https://api.fireworks.ai/inference/v1", "FIREWORKS_API_KEY"),
    "qwen":         ('openai_chat', "https://dashscope.aliyuncs.com/compatible-mode/v1", "QWEN_API_KEY")
}

# %% ../nbs/06_acomplete.ipynb #77d27ea7
api2spec = {'openai':oai_spec, 'openai_chat':oai_spec, 'anthropic':ant_spec, 'gemini':gem_spec}

# %% ../nbs/06_acomplete.ipynb #79075d95
@flexicache()
def mk_client(model, vendor_name=None, api_name=None, api_key=None, base_url=None, xtra_hdrs=None):
    err_msg = f"please pass a valid one vendor: {', '.join(list(vendor_mapping))} or pass `api_name`,`base_url` and `api_key`"
    if vendor_name:
        override_base_url = base_url
        try: 
            api_name, base_url, env_api_nm = vendor_mapping[vendor_name]
            base_url = override_base_url or base_url
            api_key = get_api_key(api_key, env_api_nm)
        except KeyError: raise ValueError(f"Unknown vendor '{vendor_name}', {err_msg}")
    elif api_name and base_url and api_key:  vendor_name = ifnone(vendor_name, 'custom')
    elif (api_name:=infer_api_name(model)):  base_url, vendor_name = None, api_name
    else: raise ValueError(f"Model {model} can't be auto resolved, {err_msg}")
    api = api_registry.apis[api_name]
    spec, hdrs = api2spec[api_name], api.get_hdrs(api_key)
    cli = OpenAPIClient(spec, headers=merge(hdrs, ifnone(xtra_hdrs, {})))
    if base_url is not None: 
        for op in cli.ops: op.base_url = base_url
    return cli, api_name, vendor_name

# %% ../nbs/06_acomplete.ipynb #df851a5c
class ContextWindowExceededError(APIError): pass

def _is_ctx_exceeded(code, msg):
    m = (msg or "").lower()
    if any(x in m for x in ("string_above_max_length", "invalid 'user'")): return False
    if str(code or "").lower() == "context_length_exceeded": return True
    return any(s in m for s in ("exceed context limit", "maximum context length", "maximum context limit",
    "longer than the model's context length", "input tokens exceed the configured limit",
    "exceeds the maximum number of tokens allowed", "prompt is too long"))

def _classify_error(exc):
    "Upgrade generic `APIError` to a specific subclass if applicable."
    if not isinstance(exc, APIError): return exc
    if _is_ctx_exceeded(exc.code, exc.message):
        return ContextWindowExceededError(exc.message, provider=exc.provider, model=exc.model,
            endpoint=exc.endpoint, status_code=exc.status_code, error_type=exc.error_type,
            code=exc.code, request_id=exc.request_id, retryable=exc.retryable, raw=exc.raw)
    return exc

async def _classify_error_stream(gen):
    "Wrap an async generator to upgrade `APIError`s as they're raised during iteration."
    try:
        async for x in gen: yield x
    except APIError as e: raise _classify_error(e) from e

# %% ../nbs/06_acomplete.ipynb #2379ec94
@delegates(payload_kwargs)
async def acomplete(msgs, model, api_name=None, vendor_name=None, api_key=None, base_url=None, xtra_body=None, xtra_hdrs=None, **kwargs):
    "Unified completion across different APIs."
    cli, api_name, vendor_name = mk_client(model, vendor_name, api_name, api_key, base_url, xtra_hdrs)
    api = api_registry.apis[api_name]
    payload = api.mk_payload(msgs, model, **kwargs)
    payload = merge(payload, ifnone(xtra_body, {}))
    if vendor_name == 'codex': 
        for k in 'temperature max_tokens max_output_tokens max_completion_tokens metadata'.split(): payload.pop(k, None)
        payload['store'] = False
    if nested_idx(payload, 'messages', -1, 'role') == 'assistant':
        if vendor_name == 'deepseek' and 'v4' in model:   payload['messages'][-1]['prefix'] = True
        if vendor_name == 'moonshot' and 'kimi' in model: payload['messages'][-1]['partial'] = True
    stream = kwargs.get('stream', False)
    func = attrgetter(api.op_path[stream])(cli)
    try: resp = await func(**payload)
    except APIError as e: raise _classify_error(e) from e
    if stream: return _classify_error_stream(api.acollect_stream(resp, model=model, vendor_name=vendor_name))
    return mk_completion(resp, model=model, api_name=api_name, vendor_name=vendor_name)
