"""A high level unified function make api calls"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_acomplete.ipynb.

# %% auto #0
__all__ = ['specs_path', 'ant_spec', 'oai_spec', 'gem_spec', 'vendor_mapping', 'api2spec', 'mk_tool_res_msg',
           'denorm_openai_responses_tool_use', 'denorm_openai_responses_tool', 'denorm_openai_responses_assistant',
           'denorm_openai_responses_msgs', 'denorm_openai_chat_tool_use', 'denorm_openai_chat_assistant',
           'denorm_openai_chat_tool', 'denorm_openai_chat_msgs', 'denorm_anthropic_tool_use',
           'denorm_anthropic_assistant', 'denorm_anthropic_tool', 'denorm_anthropic_msgs', 'denorm_gemini_tool_use',
           'denorm_gemini_assistant', 'denorm_gemini_tool', 'denorm_gemini_msgs', 'denorm_openai_responses_tool_schs',
           'denorm_openai_chat_tool_schs', 'denorm_anthropic_tool_schs', 'denorm_gemini_tool_schs',
           'denorm_openai_responses_tool_choice', 'denorm_openai_chat_tool_choice', 'denorm_anthropic_tool_choice',
           'denorm_gemini_tool_choice', 'denorm_openai_responses_reasoning', 'denorm_openai_chat_reasoning',
           'denorm_anthropic_reasoning', 'denorm_gemini_reasoning', 'denorm_openai_chat_web_search',
           'denorm_openai_responses_web_search', 'denorm_anthropic_web_search', 'denorm_gemini_web_search',
           'denorm_openai_responses_user', 'denorm_openai_chat_user', 'denorm_anthropic_user', 'denorm_gemini_user',
           'denorm_openai_responses_tool_result', 'denorm_openai_chat_tool_result', 'denorm_anthropic_tool_result',
           'denorm_gemini_tool_result', 'infer_api_name', 'get_hdrs', 'mk_client', 'ContextWindowExceededError',
           'payload_kwargs', 'acomplete']

# %% ../nbs/03_acomplete.ipynb #f2f57253
import nbdev, yaml, json
from dataclasses import dataclass, field, fields
from importlib.resources import files
from fastcore.utils import *
from fastcore.meta import *
from fastspec.spec import *
from fastspec.oapi import *
from fastspec.errors import APIError

from .types import *
from .normalize import *
from .streaming import *

# %% ../nbs/03_acomplete.ipynb #08a84488
specs_path = files('fastllm') / 'specs'
ant_spec  = SpecParser.from_openapi(dict2obj(yaml.safe_load((specs_path/'anthropic.yml').read_text())))
oai_spec  = SpecParser.from_openapi(dict2obj(yaml.safe_load((specs_path/'openai.with-code-samples.yml').read_text())))
gem_spec  = SpecParser.from_discovery(dict2obj(json.loads((specs_path/'gemini.json').read_text())))

# %% ../nbs/03_acomplete.ipynb #2c20d753
def mk_tool_res_msg(tool_calls:list[ToolCall], results:list[str|list]):
    'A util to prepare parallel tool call with str or media list results'
    parts = []
    for tc,res in zip(tool_calls, results):
        data = dict(id=tc.id, name=tc.name, arguments=tc.arguments, server=tc.server)
        parts.append(Part(type=PartType.tool_result, text=res, data=data))
    return Msg(role="tool", content=parts)

# %% ../nbs/03_acomplete.ipynb #8aceb917
def denorm_openai_responses_tool_use(p:Part):
    "Convert canonical tool_use Part back to OpenAI Responses function_call item."
    return dict(type='function_call', call_id=p.data.get('id'), name=p.data.get('name'), arguments=json.dumps(p.data.get('arguments', '{}')))

# %% ../nbs/03_acomplete.ipynb #1bcffd38
def denorm_openai_responses_tool(m:Msg):
    items = []
    for part in m.content:
        if part.type == PartType.tool_result: items.append(denorm_openai_responses_tool_result(part))
    return items

# %% ../nbs/03_acomplete.ipynb #50bb39b7
def denorm_openai_responses_assistant(m:Msg):
    items, srv_call_id = [], None
    for p in m.content:
        if p.type == PartType.tool_use:
            items.append(denorm_openai_responses_tool_use(p))
            if p.data.get('server'): 
                srv_txt = f"[Server tool `{p.data['name']}` executed successfully, results are generated below]"
                items.append(dict(type='function_call_output', call_id=p.data['id'], output=srv_txt))    
        elif p.type in (PartType.text, PartType.thinking):
            items.append(dict(type="message", role="assistant", content=[dict(type="output_text", text=p.text)]))
    return items

# %% ../nbs/03_acomplete.ipynb #3bd7dad1
def denorm_openai_responses_msgs(msgs:list[Msg]):
    res = []
    for m in msgs:
        if m.role == 'user':        res.append(denorm_openai_responses_user(m))
        elif m.role == 'assistant': res.extend(denorm_openai_responses_assistant(m))
        elif m.role == 'tool':      res.extend(denorm_openai_responses_tool(m))
    return res

# %% ../nbs/03_acomplete.ipynb #01f5a970
def denorm_openai_chat_tool_use(p:Part):
    "Convert canonical tool_use Part to OpenAI Chat tool_call dict."
    return dict(id=p.data.get('id'), type='function', function=dict(name=p.data.get('name'), arguments=json.dumps(p.data.get('arguments', '{}'))))

def denorm_openai_chat_assistant(m:Msg):
    "Convert canonical assistant Msg to OpenAI Chat assistant message + synthetic tool responses for server tools."
    tcs, srv_responses, texts = [], [], []
    for p in m.content:
        if p.type == PartType.tool_use:
            tcs.append(denorm_openai_chat_tool_use(p))
            if p.data.get('server'):
                srv_txt = f"[Server tool `{p.data['name']}` executed successfully, results are generated]"
                srv_responses.append(dict(role='tool', tool_call_id=p.data['id'], content=srv_txt))
        elif p.type == PartType.text: texts.append(p)
    msg = dict(role='assistant')
    if texts: msg['content'] = texts[0].text if len(texts)==1 else [dict(type='text', text=p.text or '') for p in texts]
    if tcs: msg['tool_calls'] = tcs
    thinking = [p for p in m.content if p.type == PartType.thinking]
    if thinking: msg['reasoning_content'] = ''.join(p.text or '' for p in thinking)
    return [msg] + srv_responses

def denorm_openai_chat_tool(m:Msg):
    "Convert canonical tool Msg to list of OpenAI Chat tool messages."
    return [denorm_openai_chat_tool_result(p) for p in m.content if p.type == PartType.tool_result]

def denorm_openai_chat_msgs(msgs:list[Msg]):
    "Convert list of canonical Msgs to OpenAI Chat messages."
    res = []
    for m in msgs:
        if   m.role == 'user':      res.append(denorm_openai_chat_user(m))
        elif m.role == 'assistant': res.extend(denorm_openai_chat_assistant(m))
        elif m.role == 'tool':      res.extend(denorm_openai_chat_tool(m))
    return res

# %% ../nbs/03_acomplete.ipynb #3e44a438
def _ant_cc(block, p):
    "Add cache_control to block if present in Part.data."
    if (cc := (p.data or {}).get('cache_control')): block['cache_control'] = cc
    return block

# %% ../nbs/03_acomplete.ipynb #06af39e6
def denorm_anthropic_tool_use(p:Part):
    "Convert canonical tool_use Part to Anthropic tool_use content block."
    d = p.data or {}
    block = dict(type='tool_use', id=d.get('id',''), name=d.get('name',''), input=d.get('arguments') or {})
    if 'caller' in d: block['caller'] = d['caller']
    return _ant_cc(block, p)

def denorm_anthropic_assistant(m:Msg):
    "Convert canonical assistant Msg to Anthropic assistant message + synthetic tool results for non-Anthropic server tools."
    blocks, srv_results, srv_call_id = [], [], None
    for p in m.content:
        if p.type == PartType.thinking:
            if srv_call_id:
                srv_results.append(dict(type='tool_result', tool_use_id=srv_call_id, content=p.text or ''))
                srv_call_id = None
            elif sig:=(p.data or {}).get('signature',''): blocks.append(dict(type='thinking', thinking=p.text or '', signature=sig))
            else:                               blocks.append(_ant_cc(dict(type='text', text=p.text or ''), p))
        elif p.type == PartType.text:
            if srv_call_id:
                srv_results.append(dict(type='tool_result', tool_use_id=srv_call_id, content=p.text or ''))
                srv_call_id = None
            else: blocks.append(_ant_cc(dict(type='text', text=p.text or ''), p))
        elif p.type == PartType.tool_use:
            if p.data.get('server') and (p.data.get('id','') or '').startswith('srvtoolu_'):
                blocks.append(dict(type='server_tool_use', id=p.data['id'], name=p.data.get('name',''), input=p.data.get('arguments') or {}))
            elif p.data.get('server'):
                blocks.append(denorm_anthropic_tool_use(p))
                srv_call_id = p.data.get('id','')
            else: blocks.append(denorm_anthropic_tool_use(p))
        elif p.type == PartType.server_tool_result: blocks.append(p.data if p.data else dict(type='server_tool_result'))
    res = [dict(role='assistant', content=blocks)]
    if srv_results: res.append(dict(role='user', content=srv_results))
    return res

def denorm_anthropic_tool(m:Msg):
    "Convert canonical tool Msg to Anthropic user message with tool_result blocks."
    blocks = [denorm_anthropic_tool_result(p) for p in m.content if p.type == PartType.tool_result]
    return [dict(role='user', content=blocks)]

def denorm_anthropic_msgs(msgs:list[Msg]):
    "Convert list of canonical Msgs to Anthropic messages."
    res = []
    for m in msgs:
        if   m.role == 'user':      res.append(denorm_anthropic_user(m))
        elif m.role == 'assistant': res.extend(denorm_anthropic_assistant(m))
        elif m.role == 'tool':      res.extend(denorm_anthropic_tool(m))
    return res

# %% ../nbs/03_acomplete.ipynb #ecad1afc
def denorm_gemini_tool_use(p:Part):
    "Convert canonical tool_use Part to Gemini functionCall part."
    d = p.data or {}
    fc = dict(name=d.get('name',''), args=d.get('arguments') or {})
    if d.get('id'): fc['id'] = d['id']
    part = dict(functionCall=fc)
    part['thoughtSignature'] = d.get('thoughtSignature', 'skip_thought_signature_validator')
    return part

def denorm_gemini_assistant(m:Msg):
    "Convert canonical assistant Msg to Gemini model content."
    parts = []
    for p in m.content:
        if   p.type == PartType.thinking: parts.append(dict(text=p.text or '', thought=True))
        elif p.type == PartType.text:     parts.append(dict(text=p.text or ''))
        elif p.type == PartType.tool_use: parts.append(denorm_gemini_tool_use(p))
    return dict(role='model', parts=parts)

def denorm_gemini_tool(m:Msg):
    "Convert canonical tool Msg to Gemini user content with functionResponse parts."
    parts = [denorm_gemini_tool_result(p) for p in m.content if p.type == PartType.tool_result]
    return dict(role='user', parts=parts)

def denorm_gemini_msgs(msgs:list[Msg]):
    "Convert list of canonical Msgs to Gemini contents."
    res = []
    for m in msgs:
        if   m.role == 'user':      res.append(denorm_gemini_user(m))
        elif m.role == 'assistant': res.append(denorm_gemini_assistant(m))
        elif m.role == 'tool':      res.append(denorm_gemini_tool(m))
    return res

# %% ../nbs/03_acomplete.ipynb #b67da0e2
def _fn_schema(t):
    "Extract (name, description, parameters) from any tool format."
    if not isinstance(t, dict): return None
    fn = t.get('function')
    if isinstance(fn, dict): return fn.get('name',''), fn.get('description',''), fn.get('parameters',{})
    if 'name' in t and ('parameters' in t or 'input_schema' in t):
        return t.get('name',''), t.get('description',''), t.get('parameters', t.get('input_schema',{}))
    return None

def denorm_openai_responses_tool_schs(tools):
    "Convert canonical tools to OpenAI Responses format."
    out = []
    for t in tools:
        fn = _fn_schema(t)
        if fn is None: out.append(t); continue
        name, desc, params = fn
        out.append(dict(type='function', name=name, description=desc, parameters=params))
    return out

def denorm_openai_chat_tool_schs(tools):
    "Passthrough — canonical format is already OpenAI Chat."
    return tools

def denorm_anthropic_tool_schs(tools):
    "Convert canonical tools to Anthropic format."
    out = []
    for t in tools:
        fn = _fn_schema(t)
        if fn is None: out.append(t); continue
        name, desc, params = fn
        out.append(dict(name=name, description=desc, input_schema=params))
    return out

def denorm_gemini_tool_schs(tools):
    "Convert canonical tools to Gemini format."
    fn_decls, other = [], []
    for t in tools:
        fn = _fn_schema(t)
        if fn is None: other.append(t); continue
        name, desc, params = fn
        fn_decls.append(dict(name=name, description=desc, parameters=params))
    out = other[:]
    if fn_decls: out.insert(0, dict(functionDeclarations=fn_decls))
    return out

# %% ../nbs/03_acomplete.ipynb #a9cf50a5
_tc_modes = {'auto', 'required', 'any', 'force', 'none', 'off', 'disabled'}

def denorm_openai_responses_tool_choice(v):
    "Map canonical tool_choice to OpenAI Responses format."
    if v is None: return None
    if v in _tc_modes: return v if v in ('auto','none','required') else {'auto':'auto','any':'required','force':'required','off':'none','disabled':'none'}[v]
    return {'type': 'function', 'name': v}

def denorm_openai_chat_tool_choice(v):
    "Map canonical tool_choice to OpenAI Chat format."
    if v is None: return None
    if v in _tc_modes: return v if v in ('auto','none','required') else {'any':'required','force':'required','off':'none','disabled':'none'}[v]
    return {'type': 'function', 'function': {'name': v}}

def denorm_anthropic_tool_choice(v):
    "Map canonical tool_choice to Anthropic format."
    if v is None: return None
    if v in ('auto',):                    return {'type': 'auto'}
    if v in ('required', 'any', 'force'): return {'type': 'any'}
    if v in ('none', 'off', 'disabled'):  return {'type': 'none'}
    return {'type': 'tool', 'name': v}

def denorm_gemini_tool_choice(v):
    "Map canonical tool_choice to Gemini toolConfig."
    if v is None: return None
    if v in ('auto',):                    return {'functionCallingConfig': {'mode': 'AUTO'}}
    if v in ('required', 'any', 'force'): return {'functionCallingConfig': {'mode': 'ANY'}}
    if v in ('none', 'off', 'disabled'):  return {'functionCallingConfig': {'mode': 'NONE'}}
    return {'functionCallingConfig': {'mode': 'ANY', 'allowedFunctionNames': [v]}}

# %% ../nbs/03_acomplete.ipynb #acf4c79e
def denorm_openai_responses_reasoning(v):
    "Map canonical reasoning_effort to OpenAI Responses reasoning param."
    if v is None: return None
    return {'effort': v} if isinstance(v, str) else v

def denorm_openai_chat_reasoning(v): return v  # passthrough as reasoning_effort param

_ant_think_aliases = dict(minimal='low', low='low', medium='medium', high='high', xhigh='xhigh', max='max')

def denorm_anthropic_reasoning(v):
    "Map canonical reasoning_effort to Anthropic adaptive thinking + output_config."
    if v is None: return None
    e = _ant_think_aliases.get(str(v).lower(), 'high')
    return {"thinking": {"type": "adaptive"}, "output_config": {"effort": e}}

_gem_think_budgets = dict(minimal=128, low=1024, medium=2048, high=4096)
_gem_think_levels  = dict(minimal='low', low='low', medium='medium', high='high')

def denorm_gemini_reasoning(v, model=''):
    "Map canonical reasoning_effort to Gemini thinkingConfig (uses thinkingLevel for Gemini 3+)."
    if v is None: return None
    if isinstance(v, dict): return v
    k = str(v).lower()
    # defaults to includeThoughts same as litellm
    if 'gemini-3' in model: return {'thinkingLevel': _gem_think_levels.get(k, 'medium'), 'includeThoughts': True}
    return {'thinkingBudget': _gem_think_budgets.get(str(v).lower(), 1024), 'includeThoughts': True}

# %% ../nbs/03_acomplete.ipynb #d74357fb
_ant_search_max_uses = {"low": 1, "medium": 5, "high": 10}

def denorm_openai_chat_web_search(v): return v  # passthrough

def denorm_openai_responses_web_search(v):
    "Map canonical web_search_options to OpenAI Responses web_search_preview tool."
    t = {"type": "web_search_preview"}
    if (typ := (v or {}).get("type")): t["type"] = typ
    if (s := (v or {}).get("search_context_size")): t["search_context_size"] = s
    if (u := (v or {}).get("user_location")): t["user_location"] = u
    return t

def denorm_anthropic_web_search(v):
    "Map canonical web_search_options to Anthropic hosted web_search tool."
    t = {"type": "web_search_20260209", "name": "web_search"}
    if (typ := (v or {}).get("type")): t["type"] = typ
    if (s := (v or {}).get("search_context_size")):
        t["max_uses"] = _ant_search_max_uses.get(s, 5)
    if (u := (v or {}).get("user_location", {}).get("approximate")):
        t["user_location"] = {"type": "approximate", **u}
    return t

def denorm_gemini_web_search(v): return {"googleSearch": {}}

# %% ../nbs/03_acomplete.ipynb #fe53537f
def _sys_text(system):
    "Extract text from system (str or Part)."
    if system is None: return None
    return system if isinstance(system, str) else system.text

# %% ../nbs/03_acomplete.ipynb #2f50f51f
def _part_txt(p): return p.text if isinstance(p,Part) else p
def _denorm_openai_responses_system(sp):  return _sys_text(_part_txt(sp))
def _denorm_openai_chat_system(sp, msgs): 
    msgs.insert(0, dict(role='system', content=_sys_text(_part_txt(sp))))
    return msgs
def _denorm_anthropic_system(sp): 
    if isinstance(sp, Part):
        block = dict(type='text', text=sp.text)
        if (cc := (sp.data or {}).get('cache_control')): block['cache_control'] = cc
        return [block]
    else: return sp
def _denorm_gemini_system(sp): return dict(parts=[{'text': _sys_text(_part_txt(sp))}])

# %% ../nbs/03_acomplete.ipynb #542fc6d7
_ext_mime = {
    '.jpg':'image/jpeg', '.jpeg':'image/jpeg', '.png':'image/png', '.gif':'image/gif', '.webp':'image/webp',
    '.pdf':'application/pdf',
    '.mp3':'audio/mpeg', '.wav':'audio/wav', '.ogg':'audio/ogg', '.flac':'audio/flac', '.m4a':'audio/mp4',
    '.mp4':'video/mp4', '.mov':'video/quicktime', '.webm':'video/webm',
}

def _data_url(url):
    "Parse data:mime;base64,data URL into (mime, b64_data), or None."
    if not isinstance(url, str) or not url.startswith('data:') or ',' not in url: return None
    header, body = url.split(',', 1)
    if ';base64' not in header or not body: return None
    return header[5:].split(';',1)[0].strip() or 'application/octet-stream', body

def _url_mime(url, default='application/octet-stream'):
    "Guess mime from URL extension."
    ext = '.' + url.rsplit('.', 1)[-1].split('?')[0].lower() if '.' in url.split('?')[0].split('/')[-1] else ''
    return _ext_mime.get(ext, default)

# %% ../nbs/03_acomplete.ipynb #7b255bf7
def denorm_openai_responses_user(m:Msg):
    "Convert canonical user Msg to OpenAI Responses input message."
    parts = []
    for p in m.content:
        if   p.type == PartType.text:        parts.append({"type": "input_text", "text": p.text or ""})
        elif p.type == PartType.input_image: parts.append(_denorm_oai_resp_image(p))
        elif p.type == PartType.input_audio: raise ValueError("OpenAI Responses API does not support audio input; Coming Soon.") 
        elif p.type == PartType.input_video: raise ValueError("OpenAI Responses API does not support video input")
        elif p.type == PartType.input_file:  parts.append(_denorm_oai_resp_file(p))
    return dict(type='message', role='user', content=parts)

def denorm_openai_chat_user(m:Msg):
    "Convert canonical user Msg to OpenAI Chat user message."
    parts = []
    for p in m.content:
        if   p.type == PartType.text:        parts.append({"type": "text", "text": p.text or ""})
        elif p.type == PartType.input_image: parts.append(_denorm_oai_chat_image(p))
        elif p.type == PartType.input_audio: parts.append(_denorm_oai_chat_audio(p))
        elif p.type == PartType.input_video: raise ValueError("OpenAI Chat API does not support video input")
        elif p.type == PartType.input_file:  parts.append(_denorm_oai_chat_file(p))
    if len(parts) == 1 and parts[0].get('type') == 'text': return dict(role='user', content=parts[0]['text'])
    return dict(role='user', content=parts)

def denorm_anthropic_user(m:Msg):
    "Convert canonical user Msg to Anthropic user message."
    parts = []
    for p in m.content:
        if   p.type == PartType.text:        parts.append(_ant_cc({"type": "text", "text": p.text or ""}, p))
        elif p.type == PartType.input_image: parts.append(_ant_cc(_denorm_ant_image(p), p))
        elif p.type == PartType.input_audio: raise ValueError("Anthropic does not support audio input")
        elif p.type == PartType.input_video: raise ValueError("Anthropic does not support video input")
        elif p.type == PartType.input_file:  parts.append(_ant_cc(_denorm_ant_file(p), p))
    return dict(role='user', content=parts)

def denorm_gemini_user(m:Msg):
    "Convert canonical user Msg to Gemini user content."
    parts = []
    for p in m.content:
        if   p.type == PartType.text:        parts.append({"text": p.text or ""})
        elif p.type == PartType.input_image: parts.append(_denorm_gem_image(p))
        elif p.type == PartType.input_audio: parts.append(_denorm_gem_audio(p))
        elif p.type == PartType.input_video: parts.append(_denorm_gem_video(p))
        elif p.type == PartType.input_file:  parts.append(_denorm_gem_file(p))
    return dict(role='user', parts=parts)

# %% ../nbs/03_acomplete.ipynb #ac00171b
def _denorm_oai_resp_image(p): return {"type": "input_image", "image_url": p.text}
def _denorm_oai_chat_image(p): return {"type": "image_url", "image_url": {"url": p.text}}
def _denorm_ant_image(p):
    if (b64:=_data_url(p.text)): return {"type": "image", "source": {"type": "base64", "media_type": b64[0], "data": b64[1]}}
    return {"type": "image", "source": {"type": "url", "url": p.text}}
def _denorm_gem_image(p):
    if (b64:=_data_url(p.text)): return {"inlineData": {"mimeType": b64[0], "data": b64[1]}}
    return {"fileData": {"mimeType": _url_mime(p.text, "image/*"), "fileUri": p.text}}

# %% ../nbs/03_acomplete.ipynb #76450e98
_mime_audio_fmt = {'audio/wav':'wav', 'audio/mpeg':'mp3', 'audio/mp3':'mp3'}
def _denorm_oai_chat_audio(p):
    if not (b64:=_data_url(p.text)): raise ValueError("OpenAI Chat audio input requires base64 data URL")
    return {"type": "input_audio", "input_audio": {"data": b64[1], "format": _mime_audio_fmt.get(b64[0], 'wav')}}
def _denorm_gem_audio(p): 
    if (b64:=_data_url(p.text)): return {"inlineData": {"mimeType": b64[0], "data": b64[1]}}
    return {"fileData": {"mimeType": _url_mime(p.text, "audio/*"), "fileUri": p.text}}

# %% ../nbs/03_acomplete.ipynb #46b1b8d7
def _denorm_gem_video(p):
    if (b64:=_data_url(p.text)): return {"inlineData": {"mimeType": b64[0], "data": b64[1]}}
    return {"fileData": {"mimeType": _url_mime(p.text, "video/mp4"), "fileUri": p.text}}

# %% ../nbs/03_acomplete.ipynb #05433c23
def _denorm_oai_resp_file(p):
    if (b64:=_data_url(p.text)): return {"type": "input_file", "file_data": p.text, "filename": f"upload.{b64[0].split('/')[-1]}"}
    return {"type": "input_file", "file_url": p.text}

def _denorm_oai_chat_file(p):
    if (b64:=_data_url(p.text)): return {"type": "file", "file": {"file_data": p.text, "filename": f"upload.{b64[0].split('/')[-1]}"}}
    raise ValueError("OpenAI Chat file input requires base64 data URL or file_id, not URLs")

def _denorm_ant_file(p):
    if (b64:=_data_url(p.text)): return {"type": "document", "source": {"type": "base64", "media_type": b64[0], "data": b64[1]}}
    return {"type": "document", "source": {"type": "url", "url": p.text}}

def _denorm_gem_file(p):
    if (b64:=_data_url(p.text)): return {"inlineData": {"mimeType": b64[0], "data": b64[1]}}
    return {"fileData": {"mimeType": _url_mime(p.text, "application/pdf"), "fileUri": p.text}}

# %% ../nbs/03_acomplete.ipynb #8cdfdc65
def denorm_openai_responses_tool_result(m:Part):
    "Convert canonical tool result back to OpenAI Responses function_call_output item."
    cid = m.data.get('id', '') or m.data.get('call_id')
    if isinstance(m.text, list):
        out = []
        for p in m.text:
            if   p.type == PartType.text:        out.append({"type": "input_text", "text": p.text or ""})
            elif p.type == PartType.input_image: out.append(_denorm_oai_resp_image(p))
            elif p.type == PartType.input_file:  out.append(_denorm_oai_resp_file(p))
            else: raise ValueError(f"OpenAI Responses tool_result does not support {p.type}")
        return dict(type='function_call_output', call_id=cid, output=out)
    return dict(type='function_call_output', call_id=cid, output=str(m.text))

# %% ../nbs/03_acomplete.ipynb #ba3256fb
def denorm_openai_chat_tool_result(p:Part):
    "Convert canonical tool_result Part to OpenAI Chat tool message."
    if isinstance(p.text, list): raise ValueError("OpenAI Chat does not support media in tool results")
    return dict(role='tool', tool_call_id=p.data.get('id') or p.data.get('call_id', ''), content=str(p.text))

# %% ../nbs/03_acomplete.ipynb #7b7fe155
def denorm_anthropic_tool_result(p:Part):
    "Convert canonical tool_result Part to Anthropic tool_result content block."
    d = p.data or {}
    tid = d.get('id') or d.get('call_id','')
    if isinstance(p.text, list):
        blocks = []
        for pp in p.text:
            if   pp.type == PartType.text:        blocks.append({"type": "text", "text": pp.text or ""})
            elif pp.type == PartType.input_image: blocks.append(_denorm_ant_image(pp))
            elif pp.type == PartType.input_file:  blocks.append(_denorm_ant_file(pp))
            else: raise ValueError(f"Anthropic tool_result does not support {pp.type}")
        return _ant_cc(dict(type='tool_result', tool_use_id=tid, content=blocks), p)
    return _ant_cc(dict(type='tool_result', tool_use_id=tid, content=str(p.text)), p)

# %% ../nbs/03_acomplete.ipynb #67fafafa
def denorm_gemini_tool_result(p:Part):
    "Convert canonical tool_result Part to Gemini functionResponse part."
    d = p.data or {}
    fr = dict(name=d.get('name',''), response={"content": "" if isinstance(p.text, list) else str(p.text)})
    if d.get('id'): fr['id'] = d['id']
    if isinstance(p.text, list):
        parts = []
        for pp in p.text:
            if   pp.type == PartType.text:        parts.append({"text": pp.text or ""})
            elif pp.type == PartType.input_image: parts.append(_denorm_gem_image(pp))
            elif pp.type == PartType.input_file:  parts.append(_denorm_gem_file(pp))
            else: raise ValueError(f"Gemini tool_result does not support {pp.type}")
        fr['parts'] = parts
    return dict(functionResponse=fr)

# %% ../nbs/03_acomplete.ipynb #32ee2546
vendor_mapping = {
    "openai_chat":  (ApiName.openai_chat, 'https://api.openai.com/v1', 'OPENAI_API_KEY'), # to force openai_chat API with openai models
    "codex":        (ApiName.openai, 'https://chatgpt.com/backend-api/codex', 'CHATGPT_API_KEY'), # codex with responses API
    "moonshot":     (ApiName.openai_chat, "https://api.moonshot.ai/v1", "MOONSHOT_API_KEY"),
    "deepseek":     (ApiName.openai_chat, "https://api.deepseek.com/v1", "DEEPSEEK_API_KEY"),
    "openrouter":   (ApiName.openai_chat, "https://openrouter.ai/api/v1", "OPENROUTER_API_KEY"),
    "together":     (ApiName.openai_chat, "https://api.together.xyz/v1", "TOGETHER_API_KEY"),
    "fireworks_ai": (ApiName.openai_chat, "https://api.fireworks.ai/inference/v1", "FIREWORKS_API_KEY"),
    "qwen":         (ApiName.openai_chat, "https://dashscope.aliyuncs.com/compatible-mode/v1", "QWEN_API_KEY")
}

# %% ../nbs/03_acomplete.ipynb #df9604b1
def infer_api_name(model):
    "Infer api_name from model"
    if "claude" in model: return ApiName.anthropic
    if "gemini" in model: return ApiName.gemini
    if any(o in model for o in ('gpt','o3-','o4-')): return ApiName.openai

# %% ../nbs/03_acomplete.ipynb #79075d95
api2spec = {ApiName.openai:oai_spec, ApiName.openai_chat:oai_spec, ApiName.anthropic:ant_spec, ApiName.gemini:gem_spec}

def get_hdrs(api_name, env_api_key=None):
    if api_name in (ApiName.openai, ApiName.openai_chat): return {"Authorization": f"Bearer {os.environ[env_api_key or 'OPENAI_API_KEY']}"}
    if api_name == ApiName.anthropic:                     return {"x-api-key": os.environ[env_api_key or 'ANTHROPIC_API_KEY'], "anthropic-version": "2023-06-01"}
    if api_name == ApiName.gemini:                        return {"x-goog-api-key": os.environ[env_api_key or 'GEMINI_API_KEY']}

@flexicache()
def mk_client(model, vendor_name=None, api_name=None, env_api_key=None, base_url=None, xtra_hdrs={}):
    if vendor_name and not (base_url and env_api_key):
        try: api_name, base_url, env_api_key = vendor_mapping[vendor_name]
        except KeyError: raise ValueError(f"Unknown vendor '{vendor_name}' please pass a valid one : {', '.join(list(vendor_mapping))} or pass `env_api_key` and `base_url`")
    elif base_url and env_api_key: 
        api_name = ApiName.openai_chat
        vendor_name = ifnone(vendor_name, 'custom')
    elif (api_name:=infer_api_name(model)): 
        base_url, vendor_name = None, api_name
    spec,hdrs = api2spec[api_name], get_hdrs(api_name, env_api_key)
    cli = OpenAPIClient(spec, headers=merge(hdrs, xtra_hdrs))
    if base_url is not None: 
        for op in cli.ops: op.base_url = base_url
    return cli, api_name, vendor_name

# %% ../nbs/03_acomplete.ipynb #df851a5c
class ContextWindowExceededError(APIError): pass

def _is_ctx_exceeded(code, msg):
    m = (msg or "").lower()
    if any(x in m for x in ("string_above_max_length", "invalid 'user'")): return False
    if str(code or "").lower() == "context_length_exceeded": return True
    return any(s in m for s in ("exceed context limit", "maximum context length", "maximum context limit",
    "longer than the model's context length", "input tokens exceed the configured limit",
    "exceeds the maximum number of tokens allowed", "prompt is too long"))

def _classify_error(exc):
    "Upgrade generic `APIError` to a specific subclass if applicable."
    if not isinstance(exc, APIError): return exc
    if _is_ctx_exceeded(exc.code, exc.message):
        return ContextWindowExceededError(exc.message, provider=exc.provider, model=exc.model,
            endpoint=exc.endpoint, status_code=exc.status_code, error_type=exc.error_type,
            code=exc.code, request_id=exc.request_id, retryable=exc.retryable, raw=exc.raw)
    return exc

async def _classify_error_stream(gen):
    "Wrap an async generator to upgrade `APIError`s as they're raised during iteration."
    try:
        async for x in gen: yield x
    except APIError as e: raise _classify_error(e) from e

# %% ../nbs/03_acomplete.ipynb #53640d14
async def _send(func, payload, norm, stream, model, api_name, vendor_name):
    "Await `func(**payload)`, classify errors, and either wrap stream or normalize response."
    try: resp = await func(**payload)
    except APIError as e: raise _classify_error(e) from e
    if stream: return _classify_error_stream(acollect_stream(resp, model=model, api_name=api_name, vendor_name=vendor_name))
    return norm(resp, model=model, api_name=api_name, vendor_name=vendor_name)

# %% ../nbs/03_acomplete.ipynb #32fb0e89
def payload_kwargs(msgs, model, stream=False, system=None, max_tokens=None, temperature=None, tools=None, tool_choice=None, reasoning_effort=None, web_search_options=None): pass

# %% ../nbs/03_acomplete.ipynb #48e17d85
@delegates(payload_kwargs)
def _mk_openai_responses_payload(msgs, model, **kwargs):
    payload = dict(model=model, input=denorm_openai_responses_msgs(msgs))
    if stream:=kwargs.get('stream'):        payload['stream'] = True
    if sp:=kwargs.get('system'):            payload['instructions'] = _denorm_openai_responses_system(sp)
    if mt:=kwargs.get('max_tokens'):        payload['max_output_tokens'] = mt
    if tools:=kwargs.get('tools'):          payload['tools'] = denorm_openai_responses_tool_schs(tools)
    if tchc:=kwargs.get('tool_choice'):     payload['tool_choice'] = denorm_openai_responses_tool_choice(tchc)
    if thk:=kwargs.get('reasoning_effort'): payload['reasoning'] = denorm_openai_responses_reasoning(thk)
    if (wopts:=kwargs.get('web_search_options')) is not None: payload.setdefault('tools', []).append(denorm_openai_responses_web_search(wopts))
    if (temp:=kwargs.get('temperature')) is not None: payload['temperature'] = temp
    return payload

@delegates(payload_kwargs)
def _mk_openai_chat_payload(msgs, model, **kwargs):
    payload = dict(model=model, messages=denorm_openai_chat_msgs(msgs))
    if sp:=kwargs.get('system'):            payload['messages'] = _denorm_openai_chat_system(sp, payload['messages'])
    if kwargs.get('stream'):                payload.update(stream=True, stream_options={"include_usage": True})
    if mt:=kwargs.get('max_tokens'):        payload['max_tokens'] = mt
    if tools:=kwargs.get('tools'):          payload['tools'] = denorm_openai_chat_tool_schs(tools)
    if tchc:=kwargs.get('tool_choice'):     payload['tool_choice'] = denorm_openai_chat_tool_choice(tchc)
    if thk:=kwargs.get('reasoning_effort'): payload['reasoning_effort'] = denorm_openai_chat_reasoning(thk)
    if (wopts:=kwargs.get('web_search_options')) is not None: payload['web_search_options'] = denorm_openai_chat_web_search(wopts)
    if (temp:=kwargs.get('temperature')) is not None: payload['temperature'] = temp
    return payload

@delegates(payload_kwargs)
def _mk_anthropic_payload(msgs, model, **kwargs):
    payload = dict(model=model, messages=denorm_anthropic_msgs(msgs), max_tokens=kwargs.get('max_tokens') or 1024)
    if kwargs.get('stream'):                payload['stream'] = True
    if sp:=kwargs.get('system'):            payload['system'] = _denorm_anthropic_system(sp)
    if tools:=kwargs.get('tools'):          payload['tools'] = denorm_anthropic_tool_schs(tools)
    if tchc:=kwargs.get('tool_choice'):     payload['tool_choice'] = denorm_anthropic_tool_choice(tchc)
    if thk:=kwargs.get('reasoning_effort'): payload.update(denorm_anthropic_reasoning(thk))
    if (wopts:=kwargs.get('web_search_options')) is not None: payload.setdefault('tools', []).append(denorm_anthropic_web_search(wopts))
    if (temp:=kwargs.get('temperature')) is not None: payload['temperature'] = temp
    return payload

@delegates(payload_kwargs)
def _mk_gemini_payload(msgs, model, **kwargs):
    payload = dict(model=model, contents=denorm_gemini_msgs(msgs))
    if sp:=kwargs.get('system'): payload['system_instruction'] = _denorm_gemini_system(sp)
    gen_config = {}
    if mt:=kwargs.get('max_tokens'):        gen_config['maxOutputTokens'] = mt
    if thk:=denorm_gemini_reasoning(kwargs.get('reasoning_effort'), model): gen_config['thinkingConfig'] = thk
    if (temp:=kwargs.get('temperature')) is not None: gen_config['temperature'] = temp
    if gen_config: payload['generation_config'] = gen_config
    gem_tools = denorm_gemini_tool_schs(kwargs.get('tools')) if kwargs.get('tools') else []
    if (wopts:=kwargs.get('web_search_options')) is not None: gem_tools.append(denorm_gemini_web_search(wopts))
    if gem_tools:
        payload['tools'] = gem_tools
        has_fn  = any('functionDeclarations' in t for t in gem_tools)
        has_srv = any(k in t for t in gem_tools for k in ('googleSearch','codeExecution','googleSearchRetrieval'))
        if has_fn and has_srv: payload.setdefault('tool_config', {})['includeServerSideToolInvocations'] = True
    if tchc:=denorm_gemini_tool_choice(kwargs.get('tool_choice')): payload.setdefault('tool_config', {}).update(tchc)
    if kwargs.get('stream'): payload.update(stream=True, _query={"alt": "sse"})
    return payload

# %% ../nbs/03_acomplete.ipynb #d4adf642
_payload_makers = {
    ApiName.openai:      (_mk_openai_responses_payload, 'responses.create_response',       normalize_openai_response),
    ApiName.openai_chat: (_mk_openai_chat_payload,      'chat.create_chat_completion',     normalize_openai_chat_completion),
    ApiName.anthropic:   (_mk_anthropic_payload,        'messages.messages_post',          normalize_anthropic_message),
    ApiName.gemini:      (_mk_gemini_payload,           'models.generate_content',         normalize_gemini_generate),
}

@delegates(payload_kwargs)
async def acomplete(msgs, model, api_name=None, vendor_name=None, env_api_key=None, base_url=None, xtra_body={}, xtra_hdrs={}, **kwargs):
    "Unified completion across different APIs."
    cli, api_name, vendor_name = mk_client(model, vendor_name, api_name, env_api_key, base_url, xtra_hdrs)
    mk, op_path, norm = _payload_makers[api_name]
    payload = mk(msgs, model, **kwargs)
    payload = merge(payload, xtra_body)
    if vendor_name == 'codex': 
        for k in 'temperature max_tokens max_output_tokens max_completion_tokens metadata'.split(): payload.pop(k, None)
    if api_name == ApiName.gemini and kwargs.get('stream'): op_path = 'models.stream_generate_content'
    func = attrgetter(op_path)(cli)
    return await _send(func, payload, norm, kwargs.get('stream', False), model, api_name, vendor_name)
