"""Provider clients built on the OpenAPI operation layer."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_acomplete.ipynb.

# %% auto #0
__all__ = ['denorm_openai_responses_tool_use', 'mk_tool_res_msg', 'denorm_openai_responses_tool_result',
           'denorm_openai_responses_user', 'denorm_openai_responses_assistant', 'denorm_openai_responses_tool',
           'denorm_openai_responses_msgs', 'denorm_openai_chat_tool_use', 'denorm_openai_chat_tool_result',
           'denorm_openai_chat_user', 'denorm_openai_chat_assistant', 'denorm_openai_chat_tool',
           'denorm_openai_chat_msgs', 'denorm_anthropic_tool_use', 'denorm_anthropic_tool_result',
           'denorm_anthropic_user', 'denorm_anthropic_assistant', 'denorm_anthropic_tool', 'denorm_anthropic_msgs',
           'denorm_gemini_tool_use', 'denorm_gemini_tool_result', 'denorm_gemini_user', 'denorm_gemini_assistant',
           'denorm_gemini_tool', 'denorm_gemini_msgs', 'denorm_openai_responses_tools', 'denorm_openai_chat_tools',
           'denorm_anthropic_tools', 'denorm_gemini_tools', 'denorm_openai_responses_tool_choice',
           'denorm_openai_chat_tool_choice', 'denorm_anthropic_tool_choice', 'denorm_gemini_tool_choice',
           'denorm_openai_responses_reasoning', 'denorm_openai_chat_reasoning', 'denorm_anthropic_reasoning',
           'denorm_gemini_reasoning']

# %% ../nbs/03_acomplete.ipynb #f2f57253
from dataclasses import dataclass, field, fields
from .types import *
from .normalize import *
from .streaming import *

# %% ../nbs/03_acomplete.ipynb #6da01318
def denorm_openai_responses_tool_use(p:Part):
    "Convert canonical tool_use Part back to OpenAI Responses function_call item."
    return dict(type='function_call', call_id=p.data.get('call_id') or p.data.get('id', ''), name=p.data.get('name', ''), arguments=json.dumps(p.data.get('arguments', '{}')))

# %% ../nbs/03_acomplete.ipynb #df4b415c
@patch(as_prop=True)
def tool_use_parts(self:Completion): return L(self.message.content).filter(lambda o: o.type==PartType.tool_use)

# %% ../nbs/03_acomplete.ipynb #5132d8ef
def mk_tool_res_msg(tool_parts:Part, results:str):
    'A user util'
    return Msg(role="tool", content=[Part(type=PartType.tool_result, text=res, data=p.data) for p,res in zip(tool_parts, results)])

# %% ../nbs/03_acomplete.ipynb #28e7d0f0
def denorm_openai_responses_tool_result(m:Part):
    "Convert canonical tool result back to OpenAI Responses function_call_output item."
    return dict(type='function_call_output', call_id=m.data.get('call_id') or m.data.get('id', ''), output=str(m.text))

# %% ../nbs/03_acomplete.ipynb #f9ba213e
def denorm_openai_responses_user(m:Msg):
    "Convert canonical user Msg to OpenAI Responses input message."
    parts = [{"type": "input_text", "text": p.text or ""} for p in m.content if p.type == PartType.text]
    return {"type": "message", "role": "user", "content": parts}

# %% ../nbs/03_acomplete.ipynb #8799f468
def denorm_openai_responses_assistant(m:Msg):
    items, srv_call_id = [], None
    for p in m.content:
        if p.type == PartType.tool_use:
            items.append(denorm_openai_responses_tool_use(p))
            srv_call_id = (p.data.get('call_id') or p.data.get('id','')) if p.data.get('server') else None
        elif p.type in (PartType.text, PartType.thinking) and srv_call_id:
            items.append(dict(type='function_call_output', call_id=srv_call_id, output=p.text or ''))
            srv_call_id = None
        elif p.type in (PartType.text, PartType.thinking):
            items.append(dict(type="message", role="assistant", content=[dict(type="output_text", text=p.text)]))
        ... # TODO: potentially other parts
    return items

# %% ../nbs/03_acomplete.ipynb #a11cd61c
def denorm_openai_responses_tool(m:Msg):
    items = []
    for part in m.content:
        if part.type == PartType.tool_result: items.append(denorm_openai_responses_tool_result(part))
        ... # TODO: potentially other parts
    return items

# %% ../nbs/03_acomplete.ipynb #1f594b90
def denorm_openai_responses_msgs(msgs:list[Msg]):
    res = []
    for m in msgs:
        if m.role == 'user':        res.append(denorm_openai_responses_user(m))
        elif m.role == 'assistant': res.extend(denorm_openai_responses_assistant(m))
        elif m.role == 'tool':      res.extend(denorm_openai_responses_tool(m))
    return res

# %% ../nbs/03_acomplete.ipynb #e8fee33a
def denorm_openai_chat_tool_use(p:Part):
    "Convert canonical tool_use Part to OpenAI Chat tool_call dict."
    return dict(id=p.data.get('id') or p.data.get('call_id', ''), type='function',
                function=dict(name=p.data.get('name', ''), arguments=json.dumps(p.data.get('arguments', '{}'))))

def denorm_openai_chat_tool_result(p:Part):
    "Convert canonical tool_result Part to OpenAI Chat tool message."
    return dict(role='tool', tool_call_id=p.data.get('id') or p.data.get('call_id', ''), content=str(p.text))

def denorm_openai_chat_user(m:Msg):
    "Convert canonical user Msg to OpenAI Chat user message."
    if len(m.content) == 1 and m.content[0].type == PartType.text: return dict(role='user', content=m.content[0].text or '')
    return dict(role='user', content=[dict(type='text', text=p.text or '') for p in m.content if p.type == PartType.text])

def denorm_openai_chat_assistant(m:Msg):
    "Convert canonical assistant Msg to OpenAI Chat assistant message + synthetic tool responses for server tools."
    tcs = [denorm_openai_chat_tool_use(p) for p in m.content if p.type == PartType.tool_use]
    msg, srv_responses, non_srv_texts, srv_call_id = dict(role='assistant'), [], [], None
    for p in m.content:
        if p.type == PartType.tool_use:
            srv_call_id = (p.data.get('id') or p.data.get('call_id','')) if p.data.get('server') else None
        elif p.type in (PartType.text, PartType.thinking) and srv_call_id:
            srv_responses.append(dict(role='tool', tool_call_id=srv_call_id, content=p.text or ''))
            srv_call_id = None
        elif p.type == PartType.text: non_srv_texts.append(p)
    if non_srv_texts: msg['content'] = non_srv_texts[0].text if len(non_srv_texts)==1 else [dict(type='text', text=p.text or '') for p in non_srv_texts]
    if tcs: msg['tool_calls'] = tcs
    thinking = [p for p in m.content if p.type == PartType.thinking]
    if thinking: msg['reasoning_content'] = ''.join(p.text or '' for p in thinking)
    return [msg] + srv_responses

def denorm_openai_chat_tool(m:Msg):
    "Convert canonical tool Msg to list of OpenAI Chat tool messages."
    return [denorm_openai_chat_tool_result(p) for p in m.content if p.type == PartType.tool_result]

def denorm_openai_chat_msgs(msgs:list[Msg]):
    "Convert list of canonical Msgs to OpenAI Chat messages."
    res = []
    for m in msgs:
        if   m.role == 'user':      res.append(denorm_openai_chat_user(m))
        elif m.role == 'assistant': res.extend(denorm_openai_chat_assistant(m))
        elif m.role == 'tool':      res.extend(denorm_openai_chat_tool(m))
    return res


# %% ../nbs/03_acomplete.ipynb #9e0007a9
def denorm_anthropic_tool_use(p:Part):
    "Convert canonical tool_use Part to Anthropic tool_use content block."
    d = p.data or {}
    block = dict(type='tool_use', id=d.get('id',''), name=d.get('name',''), input=d.get('arguments') or {})
    if 'caller' in d: block['caller'] = d['caller']
    return block

def denorm_anthropic_tool_result(p:Part):
    "Convert canonical tool_result Part to Anthropic tool_result content block."
    d = p.data or {}
    return dict(type='tool_result', tool_use_id=d.get('id') or d.get('call_id',''), content=str(p.text))

def denorm_anthropic_user(m:Msg):
    "Convert canonical user Msg to Anthropic user message."
    parts = [dict(type='text', text=p.text or '') for p in m.content if p.type == PartType.text]
    return dict(role='user', content=parts)

def denorm_anthropic_assistant(m:Msg):
    "Convert canonical assistant Msg to Anthropic assistant message + synthetic tool results for non-Anthropic server tools."
    blocks, srv_results, srv_call_id = [], [], None
    for p in m.content:
        if p.type == PartType.thinking:
            if srv_call_id:
                srv_results.append(dict(type='tool_result', tool_use_id=srv_call_id, content=p.text or ''))
                srv_call_id = None
            elif sig:=(p.data or {}).get('signature',''): blocks.append(dict(type='thinking', thinking=p.text or '', signature=sig))
            else:                               blocks.append(dict(type='text', text=p.text or ''))
        elif p.type == PartType.text:
            if srv_call_id:
                srv_results.append(dict(type='tool_result', tool_use_id=srv_call_id, content=p.text or ''))
                srv_call_id = None
            else: blocks.append(dict(type='text', text=p.text or ''))
        elif p.type == PartType.tool_use:
            if p.data.get('server') and (p.data.get('id','') or '').startswith('srvtoolu_'):
                blocks.append(dict(type='server_tool_use', id=p.data['id'], name=p.data.get('name',''), input=p.data.get('arguments') or {}))
            elif p.data.get('server'):
                blocks.append(denorm_anthropic_tool_use(p))
                srv_call_id = p.data.get('id','')
            else: blocks.append(denorm_anthropic_tool_use(p))
        elif p.type == PartType.server_tool_result: blocks.append(p.data if p.data else dict(type='server_tool_result'))
    res = [dict(role='assistant', content=blocks)]
    if srv_results: res.append(dict(role='user', content=srv_results))
    return res

def denorm_anthropic_tool(m:Msg):
    "Convert canonical tool Msg to Anthropic user message with tool_result blocks."
    blocks = [denorm_anthropic_tool_result(p) for p in m.content if p.type == PartType.tool_result]
    return [dict(role='user', content=blocks)]

def denorm_anthropic_msgs(msgs:list[Msg]):
    "Convert list of canonical Msgs to Anthropic messages."
    res = []
    for m in msgs:
        if   m.role == 'user':      res.append(denorm_anthropic_user(m))
        elif m.role == 'assistant': res.extend(denorm_anthropic_assistant(m))
        elif m.role == 'tool':      res.extend(denorm_anthropic_tool(m))
    return res


# %% ../nbs/03_acomplete.ipynb #64d54260
def denorm_gemini_tool_use(p:Part):
    "Convert canonical tool_use Part to Gemini functionCall part."
    d = p.data or {}
    fc = dict(name=d.get('name',''), args=d.get('arguments') or {})
    if d.get('id'): fc['id'] = d['id']
    part = dict(functionCall=fc)
    part['thoughtSignature'] = d.get('thoughtSignature', 'skip_thought_signature_validator')
    return part

def denorm_gemini_tool_result(p:Part):
    "Convert canonical tool_result Part to Gemini functionResponse part."
    d = p.data or {}
    fr = dict(name=d.get('name',''), response={"content": str(p.text)})
    if d.get('id'): fr['id'] = d['id']
    return dict(functionResponse=fr)

def denorm_gemini_user(m:Msg):
    "Convert canonical user Msg to Gemini user content."
    parts = [dict(text=p.text or '') for p in m.content if p.type == PartType.text]
    return dict(role='user', parts=parts)

def denorm_gemini_assistant(m:Msg):
    "Convert canonical assistant Msg to Gemini model content."
    parts = []
    for p in m.content:
        if   p.type == PartType.thinking: parts.append(dict(text=p.text or '', thought=True))
        elif p.type == PartType.text:     parts.append(dict(text=p.text or ''))
        elif p.type == PartType.tool_use: parts.append(denorm_gemini_tool_use(p))
    return dict(role='model', parts=parts)

def denorm_gemini_tool(m:Msg):
    "Convert canonical tool Msg to Gemini user content with functionResponse parts."
    parts = [denorm_gemini_tool_result(p) for p in m.content if p.type == PartType.tool_result]
    return dict(role='user', parts=parts)

def denorm_gemini_msgs(msgs:list[Msg]):
    "Convert list of canonical Msgs to Gemini contents."
    res = []
    for m in msgs:
        if   m.role == 'user':      res.append(denorm_gemini_user(m))
        elif m.role == 'assistant': res.append(denorm_gemini_assistant(m))
        elif m.role == 'tool':      res.append(denorm_gemini_tool(m))
    return res

# %% ../nbs/03_acomplete.ipynb #b67da0e2
def _fn_schema(t):
    "Extract (name, description, parameters) from any tool format."
    if not isinstance(t, dict): return None
    fn = t.get('function')
    if isinstance(fn, dict): return fn.get('name',''), fn.get('description',''), fn.get('parameters',{})
    if 'name' in t and ('parameters' in t or 'input_schema' in t):
        return t.get('name',''), t.get('description',''), t.get('parameters', t.get('input_schema',{}))
    return None

def denorm_openai_responses_tools(tools):
    "Convert canonical tools to OpenAI Responses format."
    out = []
    for t in tools:
        fn = _fn_schema(t)
        if fn is None: out.append(t); continue
        name, desc, params = fn
        out.append(dict(type='function', name=name, description=desc, parameters=params))
    return out

def denorm_openai_chat_tools(tools):
    "Passthrough — canonical format is already OpenAI Chat."
    return tools

def denorm_anthropic_tools(tools):
    "Convert canonical tools to Anthropic format."
    out = []
    for t in tools:
        fn = _fn_schema(t)
        if fn is None: out.append(t); continue
        name, desc, params = fn
        out.append(dict(name=name, description=desc, input_schema=params))
    return out

def denorm_gemini_tools(tools):
    "Convert canonical tools to Gemini format."
    fn_decls, other = [], []
    for t in tools:
        fn = _fn_schema(t)
        if fn is None: other.append(t); continue
        name, desc, params = fn
        fn_decls.append(dict(name=name, description=desc, parameters=params))
    out = other[:]
    if fn_decls: out.insert(0, dict(functionDeclarations=fn_decls))
    return out

# %% ../nbs/03_acomplete.ipynb #a9cf50a5
_tc_modes = {'auto', 'required', 'any', 'force', 'none', 'off', 'disabled'}

def denorm_openai_responses_tool_choice(v):
    "Map canonical tool_choice to OpenAI Responses format."
    if v is None: return None
    s = str(v).strip().lower()
    if s in _tc_modes: return s if s in ('auto','none','required') else {'auto':'auto','any':'required','force':'required','off':'none','disabled':'none'}[s]
    return {'type': 'function', 'name': v}

def denorm_openai_chat_tool_choice(v):
    "Map canonical tool_choice to OpenAI Chat format."
    if v is None: return None
    s = str(v).strip().lower()
    if s in _tc_modes: return s if s in ('auto','none','required') else {'any':'required','force':'required','off':'none','disabled':'none'}[s]
    return {'type': 'function', 'function': {'name': v}}

def denorm_anthropic_tool_choice(v):
    "Map canonical tool_choice to Anthropic format."
    if v is None: return None
    s = str(v).strip().lower()
    if s in ('auto',):                    return {'type': 'auto'}
    if s in ('required', 'any', 'force'): return {'type': 'any'}
    if s in ('none', 'off', 'disabled'):  return None
    return {'type': 'tool', 'name': v}

def denorm_gemini_tool_choice(v):
    "Map canonical tool_choice to Gemini toolConfig."
    if v is None: return None
    s = str(v).strip().lower()
    if s in ('auto',):                    return {'functionCallingConfig': {'mode': 'AUTO'}}
    if s in ('required', 'any', 'force'): return {'functionCallingConfig': {'mode': 'ANY'}}
    if s in ('none', 'off', 'disabled'):  return {'functionCallingConfig': {'mode': 'NONE'}}
    return {'functionCallingConfig': {'mode': 'ANY', 'allowedFunctionNames': [v]}}

# %% ../nbs/03_acomplete.ipynb #acf4c79e
#### reasoning_effort
def denorm_openai_responses_reasoning(v):
    "Map canonical reasoning_effort to OpenAI Responses reasoning param."
    if v is None: return None
    return {'effort': v} if isinstance(v, str) else v

def denorm_openai_chat_reasoning(v): return v  # passthrough as reasoning_effort param

_ant_think_budgets = dict(minimal=1024, low=2048, medium=4096, high=8192, max=16384)
def denorm_anthropic_reasoning(v):
    "Map canonical reasoning_effort to Anthropic thinking config."
    if v is None: return None
    if isinstance(v, dict): return v
    return {'type': 'enabled', 'budget_tokens': _ant_think_budgets.get(str(v).lower(), 4096)}

_gem_think_budgets = dict(minimal=256, low=512, medium=1024, high=2048, max=4096)
def denorm_gemini_reasoning(v):
    "Map canonical reasoning_effort to Gemini thinkingConfig."
    if v is None: return None
    if isinstance(v, dict): return v
    return {'thinkingBudget': _gem_think_budgets.get(str(v).lower(), 1024)}
