# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_anthropic.ipynb.

# %% auto #0
__all__ = ['ant_tc_types', 'norm_tool_call', 'norm_tool_calls', 'norm_usage', 'finalize_usage', 'norm_finish', 'search_results',
           'norm_parts', 'raw_msg', 'norm_tr_parts', 'norm_sse_event', 'delta_index_fn', 'collate_raw',
           'acollect_stream', 'denorm_tool_use', 'denorm_assistant', 'denorm_tool', 'denorm_msgs', 'denorm_tool_schs',
           'denorm_tool_choice', 'denorm_reasoning', 'denorm_web_search', 'denorm_system', 'denorm_user',
           'denorm_image', 'denorm_file', 'denorm_tool_result', 'apply_cache_idxs', 'mk_payload', 'get_hdrs', 'cost']

# %% ../nbs/04_anthropic.ipynb #02afd3d7
import json, copy
from collections import Counter
from fastcore.utils import *
from fastcore.meta import *
from fasttransport.errors import api_error_from_event

from .types import *
from aidialog.msg_parts import (MdStr, Part, PartType, mk_part, Msg, Completion, Text, Thinking, ToolUse, ToolResult, tool_text,
                                InputImage, InputAudio, InputVideo, InputFile, data_url)
from .streaming import *
from .streaming import mk_acollect_stream

# %% ../nbs/04_anthropic.ipynb #5656d1d6
ant_tc_types = ("tool_use", "server_tool_use", "mcp_tool_use")

def norm_tool_call(b):
    if b.get("type") in ant_tc_types:
        raw = {k:v for k,v in b.items() if k not in ("type","id","name","input")}
        return ToolUse(id=b["id"], name=b["name"], arguments=b.get("input") or {}, server=b.get("type")!="tool_use", raw=raw)

def norm_tool_calls(resp, delta=False):
    "Extract Anthropic tool_use blocks as normalized tool calls."
    out = []
    for b in resp.get("content", []):
        if tc:= norm_tool_call(b): out.append(tc)
    return out

# %% ../nbs/04_anthropic.ipynb #0a1e2a8e
def norm_usage(resp):
    "Normalize Anthropic usage shape."
    if not (usg:=resp.get("usage")): return None
    cached = int(usg.get("cache_read_input_tokens", 0) or 0)
    cache_creation = int(usg.get("cache_creation_input_tokens", 0) or 0)
    pt = int(usg.get("input_tokens", 0) or 0) + cached + cache_creation
    ct = int(usg.get("output_tokens", 0) or 0)
    return Usage(prompt_tokens=pt, completion_tokens=ct, total_tokens=pt + ct,
                 cached_tokens=cached, cache_creation_tokens=cache_creation, reasoning_tokens=0, raw=usg)

def finalize_usage(usg, parts):
    "Split reasoning tokens out of `output_tokens`: the reported `thinking_tokens`, else an estimate from the thinking text."
    if not usg: return usg
    rc = '\n'.join(p.text or '' for p in parts if isinstance(p, Thinking))
    ct = int(usg.raw.get('output_tokens', usg.completion_tokens) or 0)
    rt = int(nested_idx(usg.raw, 'output_tokens_details', 'thinking_tokens') or 0) or (min(int(len(rc.split())*1.5), ct) if rc else 0)
    return Usage(prompt_tokens=usg.prompt_tokens, completion_tokens=ct-rt, total_tokens=usg.prompt_tokens+ct,
        cached_tokens=usg.cached_tokens, cache_creation_tokens=usg.cache_creation_tokens, reasoning_tokens=rt, raw=usg.raw)

# %% ../nbs/04_anthropic.ipynb #7a8b1f8f
def norm_finish(resp, tcs=None):
    "Canonicalize finish_reason to OpenAI Chat values: stop, tool_calls, length, content_filter."
    reason = resp.get("stop_reason")
    mp = dict(end_turn=FinishReason.stop, tool_use=FinishReason.tool_calls, max_tokens=FinishReason.length)
    r =  mp.get(reason, reason)
    return FinishReason.tool_calls if r==FinishReason.stop and any(~L(tcs).attrgot('server')) else r 

# %% ../nbs/04_anthropic.ipynb #9796be28
def search_results(parts, blocks):
    "Give each server call the sources its `web_search_tool_result` block reports, one `title: url` line each, or the block's error code"
    calls = {p.id: p for p in parts if isinstance(p, ToolUse) and p.server}
    for b in blocks:
        if b.get('type') != 'web_search_tool_result' or not (call := calls.get(b.get('tool_use_id'))): continue
        res = b.get('content')
        call.text = res.get('error_code', '') if isinstance(res, dict) else MdStr('\n'.join(f"{r.get('title', '')}: {r['url']}" for r in res if r.get('url')))
    return parts

# %% ../nbs/04_anthropic.ipynb #20d2e803
def _ant_part_type(typ):
    "Map Anthropic content block type to canonical PartType."
    ant_parts_mapping = dict(text=PartType.text, thinking=PartType.thinking, redacted_thinking=PartType.thinking, tool_use=PartType.tool_use, server_tool_use=PartType.tool_use, mcp_tool_use=PartType.tool_use)
    return ant_parts_mapping.get(typ, typ)

def _url_cite(c): return dict(type='url_citation', url=c['url'], title=c.get('title', ''))

def norm_parts(resp):
    "Canonical parts of a response; a text block's web citations become `url_citation`s"
    parts = []
    for b in resp.get("content", []):
        typ = _ant_part_type(b.get("type", "text"))
        if   typ == PartType.thinking: parts.append(Thinking(b.get("thinking", ""), raw=b))
        elif typ == PartType.tool_use:
            if tc := norm_tool_call(b): parts.append(tc)
        elif typ == PartType.text:
            cites = [_url_cite(c) for c in b.get('citations') or [] if c.get('url')]
            parts.append(Text(b.get("text", ""), citations=cites, raw=b))
    return search_results(parts, resp.get("content", []))

# %% ../nbs/04_anthropic.ipynb #f24e52db
def raw_msg(resp):
    "The assistant message as the API sent it"
    return dict(role='assistant', content=resp['content'])

# %% ../nbs/04_anthropic.ipynb #5d1440b7
def norm_tr_parts(content):
    "Normalize an Anthropic `tool_result` content str or block list to canonical `Part`s"
    if isinstance(content, str): return [Text(content)]
    parts = []
    for b in content:
        typ = b.get('type', 'text')
        if typ=='text': parts.append(Text(b.get('text',''), raw=b))
        elif typ=='image':
            s = b['source']
            parts.append(InputImage(f"data:{s['media_type']};base64,{s['data']}", mime=s['media_type'], raw=b))
        else: parts.append(mk_part(**b))
    return parts

# %% ../nbs/04_anthropic.ipynb #a3869e31
def norm_sse_event(ev, **kwargs):
    ev = obj2dict(ev)
    typ = ev.get("type")
    text, thinking, tcs, citations = None, None, [], None
    if typ == "content_block_start":
        cb = ev.get("content_block", {})
        if tc := norm_tool_call(cb):
            if not tc.arguments: tc.arguments = {'_delta': ''}
            tcs = [tc]
    elif typ == "content_block_delta":
        d = ev.get("delta", {})
        dtyp = d.get("type")
        if   dtyp == "text_delta": text = d.get("text")
        elif dtyp == "thinking_delta": thinking = d.get("thinking")
        elif dtyp == "input_json_delta":
            tcs = [ToolUse(id=str(ev.get("index", "")), name="", arguments={"_delta": d.get("partial_json", '')})]
        elif dtyp == "citations_delta": citations = [_url_cite(c) for c in listify(d.get('citation', [])) if c.get('url')]
    elif typ == "message_delta":
        fin = norm_finish(ev.get('delta'))
        return Delta(finish_reason=fin, usage=norm_usage(ev), raw=ev, **kwargs)
    elif typ == "error": raise api_error_from_event(ev)
    return Delta(text=text, thinking=thinking, tool_calls=tcs, citations=citations, raw=ev, **kwargs)

# %% ../nbs/04_anthropic.ipynb #33cd3bd3
def delta_index_fn(d, typ, last_typ, last_idx):
    'Returns accumulation index for current delta and updated last idx'
    return nested_idx(d, 'raw', 'index'), None

# %% ../nbs/04_anthropic.ipynb #de900e34
def collate_raw(deltas):
    "The assistant message rebuilt from a stream's events"
    blocks = {}
    for ev in L(deltas).attrgot('raw'):
        typ,i = ev.get('type'),ev.get('index')
        if typ == 'content_block_start': blocks[i] = copy.deepcopy(ev['content_block'])
        elif typ == 'content_block_delta':
            d,b = ev['delta'],blocks[i]
            if   d['type'] == 'text_delta':       b['text'] += d['text']
            elif d['type'] == 'thinking_delta':   b['thinking'] += d['thinking']
            elif d['type'] == 'signature_delta':  b['signature'] = d['signature']
            elif d['type'] == 'input_json_delta': b['_json'] = b.get('_json', '') + d['partial_json']
            elif d['type'] == 'citations_delta':  b['citations'] = (b.get('citations') or []) + [d['citation']]
        elif typ == 'content_block_stop' and '_json' in blocks[i]: blocks[i]['input'] = json.loads(blocks[i].pop('_json') or '{}')
    return dict(role='assistant', content=list(blocks.values()))

# %% ../nbs/04_anthropic.ipynb #c994adb1
@delegates(mk_acollect_stream, but=['index_fn', 'api_name'])
async def acollect_stream(resp, **kwargs):
    res = mk_acollect_stream(norm_and_yield(resp, norm_sse_event), index_fn=delta_index_fn, api_name='anthropic', **kwargs)
    async for o in res:
        if isinstance(o, Completion): search_results(o.message.content, o.message.raw['content'])
        yield o

# %% ../nbs/04_anthropic.ipynb #bb11ab62
def _ant_cc(block, p):
    "Add the part's prompt-cache directive to `block`, if it has one."
    if p.cache_control: block['cache_control'] = p.cache_control
    return block

# %% ../nbs/04_anthropic.ipynb #62e9a042
def _sanid(id_str): return re.sub(r'[^a-zA-Z0-9_-]', '_', id_str or '')

# %% ../nbs/04_anthropic.ipynb #6ec772cb
def denorm_tool_use(p:ToolUse):
    "Convert canonical tool_use Part to Anthropic tool_use content block."
    return _ant_cc(dict(type='tool_use', id=_sanid(p.id or ''), name=p.name or '', input=p.arguments or {}), p)

def denorm_assistant(m:Msg):
    "The message as the API sent it, else its text and tool calls; a cache mark on the last part is copied onto the last raw block"
    if m.raw:
        cc = [p.cache_control for p in m.content if p.cache_control]
        if not cc: return m.raw
        return m.raw | dict(content=m.raw['content'][:-1] + [m.raw['content'][-1] | dict(cache_control=cc[-1])])
    blocks = [_ant_cc(dict(type='text', text=p.text or ''), p) if isinstance(p, Text) else denorm_tool_use(p) for p in m.content if isinstance(p, (Text, ToolUse))]
    return dict(role='assistant', content=blocks)

def denorm_tool(m:Msg):
    "Convert canonical tool Msg to Anthropic user message with tool_result blocks."
    blocks = [denorm_tool_result(p) for p in m.content if isinstance(p, ToolResult)]
    return dict(role='user', content=blocks)

def denorm_msgs(msgs:list[Msg]):
    "Convert list of canonical Msgs to Anthropic messages."
    res = []
    for m in msgs:
        if   m.role == 'user':      res.append(denorm_user(m))
        elif m.role == 'assistant': res.append(denorm_assistant(m))
        elif m.role == 'tool':      res.append(denorm_tool(m))
    return res

# %% ../nbs/04_anthropic.ipynb #f762a6f2
def denorm_tool_schs(tools):
    "Convert canonical tools to Anthropic format."
    out = []
    for t in tools:
        fn = fn_schema(t)
        if fn is None: out.append(t); continue
        name, desc, params = fn
        out.append(dict(name=name, description=desc, input_schema=params))
    return out

# %% ../nbs/04_anthropic.ipynb #6118d7ea
def denorm_tool_choice(v):
    "Map canonical tool_choice to Anthropic format."
    if v is None: return None
    if v in ('auto',):                    return {'type': 'auto'}
    if v in ('required', 'any', 'force'): return {'type': 'any'}
    if v in ('none', 'off', 'disabled'):  return {'type': 'none'}
    return {'type': 'tool', 'name': v}

# %% ../nbs/04_anthropic.ipynb #310f1e75
def denorm_reasoning(v):
    "Map canonical reasoning_effort to Anthropic adaptive thinking + output_config."
    mp = dict(minimal='low', low='low', medium='medium', high='high', xhigh='xhigh', max='max')
    err = ValueError(f"Invalid reasoning effort for Anthropic: {v}, accepted string values are: {list(mp)} and dicts are passthrough")
    if v is None: return None
    elif isinstance(v, dict): return v
    elif isinstance(v, str) and v in mp:  return {"thinking": {"type": "adaptive"}, "output_config": {"effort": mp.get(v)}}
    raise err

# %% ../nbs/04_anthropic.ipynb #8fa9fbb8
def denorm_web_search(v):
    "Map canonical web_search_options to Anthropic hosted web_search tool."
    _max_uses = {"low": 1, "medium": 5, "high": 10}
    t = {"type": "web_search_20250305", "name": "web_search"}
    if (typ := (v or {}).get("type")): t["type"] = typ
    if (s := (v or {}).get("search_context_size")):
        t["max_uses"] = _max_uses.get(s, 5)
    if (u := (v or {}).get("user_location", {}).get("approximate")):
        t["user_location"] = {"type": "approximate", **u}
    return t

# %% ../nbs/04_anthropic.ipynb #6b485275
def denorm_system(sp):
    if isinstance(sp, Msg): sp = sp.content[0]
    if isinstance(sp, Part): return [_ant_cc(dict(type='text', text=sp.text), sp)]
    else: return sp

# %% ../nbs/04_anthropic.ipynb #1b990cc9
def denorm_user(m:Msg):
    "Convert canonical user Msg to Anthropic user message."
    parts = []
    for p in m.content:
        if   isinstance(p, Text):       parts.append(_ant_cc({"type":"text", "text":p.text or ''}, p))
        elif isinstance(p, InputImage): parts.append(_ant_cc(denorm_image(p), p))
        elif isinstance(p, InputAudio): raise ValueError("Anthropic does not support audio input")
        elif isinstance(p, InputVideo): raise ValueError("Anthropic does not support video input")
        elif isinstance(p, InputFile):  parts.append(_ant_cc(denorm_file(p), p))
    return dict(role='user', content=parts)

# %% ../nbs/04_anthropic.ipynb #edd87272
def denorm_image(p, max_sz=None):
    if (b64:=data_url(p.text)):
        data = resize_b64(b64[1], max_sz) if max_sz else b64[1]
        return {"type": "image", "source": {"type": "base64", "media_type": b64[0], "data": data}}
    return {"type": "image", "source": {"type": "url", "url": p.text}}

# %% ../nbs/04_anthropic.ipynb #fc6bbdfc
def denorm_file(p):
    if (b64:=data_url(p.text)): return {"type": "document", "source": {"type": "base64", "media_type": b64[0], "data": b64[1]}}
    return {"type": "document", "source": {"type": "url", "url": p.text}}

# %% ../nbs/04_anthropic.ipynb #37b63cc2
def denorm_tool_result(p:ToolResult):
    "Convert canonical tool_result Part to Anthropic tool_result content block."
    tid = _sanid(p.id or (p.raw or {}).get('call_id',''))
    if isinstance(p.text, list):
        blocks = []
        for pp in p.text:
            if   isinstance(pp, Text):       blocks.append({"type": "text", "text": pp.text or ""})
            elif isinstance(pp, InputImage): blocks.append(denorm_image(pp, max_sz=2000))
            elif isinstance(pp, InputFile):  blocks.append(denorm_file(pp))
            else: raise ValueError(f"Anthropic tool_result does not support {pp.type}")
        return _ant_cc(dict(type='tool_result', tool_use_id=tid, content=blocks), p)
    return _ant_cc(dict(type='tool_result', tool_use_id=tid, content=tool_text(p.text)), p)

# %% ../nbs/04_anthropic.ipynb #e4eb8d3b
def _add_cache_control(
    msg,     # Canonical Msg to mark
    ttl=None # Cache TTL: '5m' (default) or '1h'
):
    "Set a cache breakpoint on the last `Text` or `ToolUse` part of `msg`"
    cc = {"type": "ephemeral"} | ({"ttl": ttl} if ttl else {})
    idxs = [i for i,p in enumerate(msg.content) if isinstance(p, (Text, ToolUse))]
    if idxs: msg.content[idxs[-1]].cache_control = cc
    return msg

# %% ../nbs/04_anthropic.ipynb #6bc52ef5
def apply_cache_idxs(
    msgs,            # Canonical Msgs to mark
    cache_idxs=[-1], # Breakpoint idxs into `msgs` (tool-role msgs excluded); 0 is `sp` when given
    sp=None,         # System prompt: str, Msg, or Part
    ttl=None         # Cache TTL: '5m' (default) or '1h'
):
    "Strip all cache breakpoints from `msgs`, then mark `cache_idxs`; returns `sp`, marked if 0 is included"
    for m in msgs:
        for p in m.content: p.cache_control = None
    if sp:
        if 0 in cache_idxs:
            if isinstance(sp, str): sp = Text(sp)
            if isinstance(sp, Part): sp = Msg('', [sp])
            _add_cache_control(sp, ttl)
        cache_idxs = [o-1 if o>0 else o for o in cache_idxs if o]
    ms = [j for j,m in enumerate(msgs) if m.role != 'tool']
    for i in cache_idxs:
        try: _add_cache_control(msgs[ms[i]], ttl)
        except IndexError: continue
    return sp

# %% ../nbs/04_anthropic.ipynb #587d4fe5
@delegates(payload_kwargs)
def mk_payload(msgs, model, **kwargs):
    sp = kwargs.get('system')
    if (ci:=kwargs.get('cache_idxs')) is not None: sp = apply_cache_idxs(msgs, ci, sp, kwargs.get('ttl'))
    payload = dict(model=model, messages=denorm_msgs(msgs), max_tokens=kwargs.get('max_tokens') or 1024)
    if kwargs.get('stream'):                payload['stream'] = True
    if sp:                              payload['system'] = denorm_system(sp)
    if tools:=kwargs.get('tools'):          payload['tools'] = denorm_tool_schs(tools)
    if tchc:=kwargs.get('tool_choice'):     payload['tool_choice'] = denorm_tool_choice(tchc)
    if thk:=kwargs.get('reasoning_effort'): payload.update(denorm_reasoning(thk))
    if (wopts:=kwargs.get('web_search_options')) is not None: 
        payload.setdefault('tools', []).append(denorm_web_search(wopts))
    if (temp:=kwargs.get('temperature')) is not None: 
        payload['temperature'] = temp
    return payload

# %% ../nbs/04_anthropic.ipynb #60d52c1f
def get_hdrs(api_key=None, oauth_token=None):
    "An OAuth token travels as a bearer under Anthropic's OAuth beta; an API key as `x-api-key`"
    hdrs = {"anthropic-version": "2023-06-01"}
    if oauth_token: return hdrs | {"Authorization": f"Bearer {oauth_token}", "anthropic-beta": "oauth-2025-04-20"}
    return hdrs | {"x-api-key": get_api_key(api_key, 'ANTHROPIC_API_KEY')}


# %% ../nbs/04_anthropic.ipynb #0d03643a
def cost(usage, m):
    raw = usage.raw
    in_tok = raw['input_tokens']
    cache_read = raw.get('cache_read_input_tokens', 0)
    cc = raw.get('cache_creation', {}) or {}
    cache_5m  = cc.get('ephemeral_5m_input_tokens', raw.get('cache_creation_input_tokens', 0))
    cache_1h  = cc.get('ephemeral_1h_input_tokens', 0)
    cost  = in_tok     * m.input_cost_per_token
    cost += raw['output_tokens'] * m.output_cost_per_token
    cost += cache_read * m.get('cache_read_input_token_cost', 0)
    cost += cache_5m   * m.get('cache_creation_input_token_cost', 0)
    cost += cache_1h   * m.get('cache_creation_input_token_cost_above_1hr', 0)
    return cost

# %% ../nbs/04_anthropic.ipynb #f7c0b989
api_registry.register('anthropic', norm_tool_calls=norm_tool_calls, norm_parts=norm_parts, norm_finish=norm_finish, norm_usage=norm_usage,
    finalize_usage=finalize_usage, raw_msg=raw_msg, collate_raw=collate_raw, acollect_stream=acollect_stream, mk_payload=mk_payload,
    cost=cost, get_hdrs=get_hdrs,
    endpoint='/v1/messages')
