"""ChatGPT subscription tokens for the Codex backend"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_codex.ipynb.

# %% auto #0
__all__ = ['SKEW_SECS', 'jwt_claims', 'mk_jwt', 'token_expired', 'codex_tokens', 'codex_info', 'codex_refresh', 'codex_token',
           'codex_auth_path', 'codex_auth', 'codex_device_code', 'codex_device_tokens', 'codex_login', 'main']

# %% ../nbs/05_codex.ipynb #a1d088d2
import asyncio, base64, json, sys, time, httpx2
from fastcore.aio import wait_until
from fastcore.utils import *


# %% ../nbs/05_codex.ipynb #aa7f9d4f
_CLIENT_ID = 'app_EMoamEEZ73f0CkXaXp7hrann'
_AUTH = 'https://auth.openai.com'
SKEW_SECS = 60

# %% ../nbs/05_codex.ipynb #2008472d
def jwt_claims(token):
    "The payload of JWT `token`, decoded without verification"
    payload = token.split('.')[1]
    return json.loads(base64.urlsafe_b64decode(payload + '='*(-len(payload)%4)))

# %% ../nbs/05_codex.ipynb #fdba8e96
def mk_jwt(**claims):
    "An unsigned JWT carrying `claims`, shaped like an access token; for examples and tests"
    enc = lambda o: base64.urlsafe_b64encode(json.dumps(o).encode()).decode().rstrip('=')
    return f"{enc(dict(alg='RS256', typ='JWT'))}.{enc(claims)}.sig"

# %% ../nbs/05_codex.ipynb #6b6a339d
def token_expired(token, skew=SKEW_SECS):
    "Is JWT `token` expired, or within `skew` seconds of expiring?"
    try: exp = jwt_claims(token)['exp']
    except (ValueError, KeyError, IndexError): return True
    return time.time() >= exp - skew

# %% ../nbs/05_codex.ipynb #099399d5
def codex_tokens(auth):
    "The `tokens` block of an `auth.json` dict (or an already-unwrapped block), checked for the keys a refresh needs"
    if not isinstance(auth, dict): raise ValueError('Codex auth must be a JSON object')
    tokens = auth.get('tokens', auth)
    missing = [k for k in ('access_token', 'refresh_token') if not tokens.get(k)]
    if missing: raise ValueError(f"Codex auth is missing {', '.join(missing)}")
    return tokens

# %% ../nbs/05_codex.ipynb #46864051
def codex_info(tokens):
    "Plan type and expiry time of the access token in `tokens`"
    claims = jwt_claims(tokens['access_token'])
    return dict(plan=claims.get('https://api.openai.com/auth', {}).get('chatgpt_plan_type'), expires=claims.get('exp'))

# %% ../nbs/05_codex.ipynb #28410636
async def _post(path, form=False, **body):
    "POST `body` to the OpenAI auth server at `path`, as a form or as JSON, returning the JSON reply"
    async with httpx2.AsyncClient() as cli: r = await cli.post(f'{_AUTH}{path}', **(dict(data=body) if form else dict(json=body)))
    r.raise_for_status()
    return r.json()

def _merge_tokens(tokens, new): return {**tokens, **{k: new[k] for k in ('access_token', 'id_token', 'refresh_token') if k in new}}

async def _token_grant(tokens, form=False, **grant):
    "The token block after `grant` at the token endpoint, merged over `tokens`; the exchange of a sign-in code is form-encoded, a refresh JSON"
    return _merge_tokens(tokens, await _post('/oauth/token', form=form, client_id=_CLIENT_ID, **grant))

# %% ../nbs/05_codex.ipynb #48efd465
async def codex_refresh(tokens):
    "Exchange the refresh token in `tokens` for a new token block"
    return await _token_grant(tokens, grant_type='refresh_token', refresh_token=tokens['refresh_token'], scope='openid profile email')

# %% ../nbs/05_codex.ipynb #be590818
async def codex_token(tokens, force_refresh=False):
    "A valid access token from `tokens`, and the refreshed block to store when a refresh happened (else `None`)"
    if not force_refresh and not token_expired(tokens['access_token']): return tokens['access_token'], None
    tokens = await codex_refresh(tokens)
    return tokens['access_token'], tokens

# %% ../nbs/05_codex.ipynb #ea6c1e6a
def codex_auth_path(): return Path(os.environ.get('CODEX_AUTH_PATH', '~/.codex/auth.json')).expanduser()

async def codex_auth(force_refresh=False):
    "A valid access token from the local Codex login, refreshing the file when needed"
    path = codex_auth_path()
    data = json.loads(path.read_text())
    token,new = await codex_token(codex_tokens(data), force_refresh)
    if new: path.write_text(json.dumps({**data, 'tokens':new}, indent=2))
    return token

# %% ../nbs/05_codex.ipynb #216c81ae
_DEVICE = '/api/accounts/deviceauth'
async def codex_device_code():
    "Start a device sign-in: the page and code to show the user, and what the poll needs"
    r = await _post(f'{_DEVICE}/usercode', client_id=_CLIENT_ID)
    return dict(url=f'{_AUTH}/codex/device', code=r['user_code'], device_auth_id=r['device_auth_id'], interval=int(r.get('interval') or 5))

# %% ../nbs/05_codex.ipynb #9ada6ae8
async def codex_device_tokens(dev, timeout=15*60):
    "Wait for the user to enter the code from `dev`, then exchange the grant for a token block"
    async def _poll():
        try: return await _post(f'{_DEVICE}/token', device_auth_id=dev['device_auth_id'], user_code=dev['code'])
        except httpx2.HTTPStatusError as e:
            if e.response.status_code in (403, 404): return None
            raise
    grant = await wait_until(_poll, 'the sign-in to complete', timeout, sleep=dev['interval'])
    return await _token_grant({}, form=True, grant_type='authorization_code', code=grant['authorization_code'], redirect_uri=f'{_AUTH}/deviceauth/callback',
        code_verifier=grant['code_verifier'])

# %% ../nbs/05_codex.ipynb #0ca00e36
async def codex_login():
    "Sign in to ChatGPT with a device code, returning the token block"
    dev = await codex_device_code()
    print(f"Open {dev['url']} and enter the code {dev['code']}", file=sys.stderr)
    return await codex_device_tokens(dev)

def main():
    "`fastllm-auth`: sign in to ChatGPT and print the token block"
    print(json.dumps(asyncio.run(codex_login())))
