"""Completion cost calculation"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_cost.ipynb.

# %% auto #0
__all__ = ['model_prices_url', 'codex_pricing', 'model_prices_meta', 'get_model_meta', 'get_model_info', 'openai_chat_cost',
           'openai_responses_cost', 'anthropic_cost', 'gemini_cost']

# %% ../nbs/04_cost.ipynb #f75da5c8
import nbdev, yaml, json
from dataclasses import dataclass, field, fields
from fastcore.utils import *
from fastcore.meta import *
from fastcore.net import urljson

from .types import *
from .normalize import *
from .streaming import *
from .acomplete import *

# %% ../nbs/04_cost.ipynb #7b6dcc06
model_prices_url = 'https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json'
@flexicache(time_policy(24*60*60))
def model_prices_meta(): return urljson(model_prices_url)

# %% ../nbs/04_cost.ipynb #08cef35a
@flexicache(time_policy(24*60*60))
def get_model_meta(model, vendor_name=None, tfm=noop):
    "Look up cost metadata for `model` from litellm price map, using `vendor_name` prefix if needed."
    vendor_name = ifnone(vendor_name, infer_api_name(model))
    mp = model_prices_meta()
    if model in mp: key = model
    elif vendor_name=='gemini' and model.startswith('models/'): key = f"gemini/{model.removeprefix('models/')}"
    elif vendor_name:                                           key = f"{vendor_name}/{model}"
    return dict2obj(tfm(mp.get(key), model, vendor_name))

# %% ../nbs/04_cost.ipynb #4f870128
codex_pricing = {
    "input_cost_per_token": 0.10 / 1_000_000,
    "cache_creation_input_token_cost": 0.10 / 1_000_000,
    "cache_read_input_token_cost": 0.10 / 1_000_000,
    "output_cost_per_token": 0.50 / 1_000_000,
}

def get_model_info(mn, vendor_name=None):
    info = get_model_meta(mn, vendor_name)
    # anthropic web search 
    if 'search_context_cost_per_query' in info:
        info['supports_web_search'] = True
    # add reasoning to kimi
    if 'kimi' in mn: 
        if 'k2p6' in mn: info = get_model_meta(mn.replace('k2p6', 'k2p5'), vendor_name)
        info['supports_reasoning'] = True
        info['supports_vision'] = True
    # add web search to gpt
    if mn in ("gpt-5.4", "gpt-5.4-mini"):
        info['supports_web_search'] = True
        info.pop('mode', None)
    # codex pricing
    if vendor_name == 'codex': info = merge(info, codex_pricing)
    return dict2obj(info)

# %% ../nbs/04_cost.ipynb #47d9d2e4
@patch(as_prop=True)
def cost(self:Completion):
    meta = dict2obj(get_model_info(self.model, self.vendor_name))
    if self.api_name == ApiName.openai_chat: return openai_chat_cost(self.usage, meta)
    if self.api_name == ApiName.openai:      return openai_responses_cost(self.usage, meta)
    if self.api_name == ApiName.gemini:      return gemini_cost(self.usage, meta)
    if self.api_name == ApiName.anthropic:   return anthropic_cost(self.usage, meta)

# %% ../nbs/04_cost.ipynb #bf460b71
def openai_chat_cost(usage, m):
    raw = usage.raw
    pd, cd = raw.get('prompt_tokens_details', {}), raw.get('completion_tokens_details', {})
    cached = pd.get('cached_tokens', 0)
    in_audio, out_audio = pd.get('audio_tokens', 0), cd.get('audio_tokens', 0)
    in_txt  = raw['prompt_tokens']     - cached - in_audio
    out_txt = raw['completion_tokens'] - out_audio
    cost  = in_txt  * m.input_cost_per_token  + out_txt * m.output_cost_per_token
    cost += cached  * m.get('cache_read_input_token_cost', 0)
    cost += in_audio  * m.get('input_cost_per_audio_token', 0)
    cost += out_audio * m.get('output_cost_per_audio_token', 0)
    return cost

# %% ../nbs/04_cost.ipynb #cc4aad3b
def openai_responses_cost(usage, m):
    raw = usage.raw
    cached = raw.get('input_tokens_details', {}).get('cached_tokens', 0)
    in_txt = raw['input_tokens'] - cached
    cost  = in_txt * m.input_cost_per_token + raw['output_tokens'] * m.output_cost_per_token
    cost += cached * m.get('cache_read_input_token_cost', 0)
    return cost

# %% ../nbs/04_cost.ipynb #a5ea3e22
def anthropic_cost(usage, m):
    raw = usage.raw
    in_tok = raw['input_tokens']
    cache_read = raw.get('cache_read_input_tokens', 0)
    cc = raw.get('cache_creation', {}) or {}
    cache_5m  = cc.get('ephemeral_5m_input_tokens', 0)
    cache_1h  = cc.get('ephemeral_1h_input_tokens', 0)
    cost  = in_tok     * m.input_cost_per_token
    cost += raw['output_tokens'] * m.output_cost_per_token
    cost += cache_read * m.get('cache_read_input_token_cost', 0)
    cost += cache_5m   * m.get('cache_creation_input_token_cost', 0)
    cost += cache_1h   * m.get('cache_creation_input_token_cost_above_1hr', 0)
    return cost

# %% ../nbs/04_cost.ipynb #89d9b658
def gemini_cost(usage, m):
    raw = usage.raw
    prompt_tot = raw.get('promptTokenCount', 0)
    tier = '_above_200k_tokens' if prompt_tot > 200_000 else ''
    in_rate    = m.get(f'input_cost_per_token{tier}')       or m.input_cost_per_token
    out_rate   = m.get(f'output_cost_per_token{tier}')      or m.output_cost_per_token
    cache_rate = m.get(f'cache_read_input_token_cost{tier}')or m.get('cache_read_input_token_cost', 0)
    audio_rate = m.get('input_cost_per_audio_token')  # None if not priced separately

    cached = raw.get('cachedContentTokenCount', 0)
    # Gemini 3 Pro supports bills audio at the standard input rate (no separate input_cost_per_audio_token key in the metadata)
    audio  = sum(d['tokenCount'] for d in raw.get('promptTokensDetails', []) if d.get('modality')=='AUDIO') if audio_rate else 0
    in_txt = prompt_tot - cached - audio

    thoughts = raw.get('thoughtsTokenCount', 0) or 0
    cands    = raw.get('candidatesTokenCount', 0) or 0
    reason_rate = m.get('output_cost_per_reasoning_token') or out_rate

    cost  = in_txt * in_rate + cands * out_rate
    cost += cached * cache_rate
    cost += audio  * (audio_rate or 0)
    cost += thoughts * reason_rate
    return cost
