"""Provider payload normalization helpers."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_normalize.ipynb.

# %% auto #0
__all__ = ['usage_from_anthropic', 'usage_from_openai', 'usage_from_gemini', 'normalize_openai_response', 'model_and_provider',
           'normalize_openai_response_event', 'normalize_openai_chat_completion', 'normalize_openai_chat_delta',
           'normalize_anthropic_message', 'normalize_anthropic_event', 'normalize_gemini_generate',
           'normalize_gemini_event']

# %% ../nbs/01_normalize.ipynb #eedf8f8f
import json
from collections import Counter
from fastcore.utils import *
from fastcore.meta import delegates
from .types import *
from fastspec.errors import api_error_from_event

# %% ../nbs/01_normalize.ipynb #7893c568
def _anthropic_tool_calls(resp):
    "Extract Anthropic tool_use blocks as normalized tool calls."
    out = []
    for b in resp.get("content", []):
        if b.get("type") not in ("tool_use", "server_tool_use", "mcp_tool_use"): continue
        extra = {k:v for k,v in b.items() if k not in ("type","id","name","input")}
        out.append(ToolCall(id=b["id"], name=b["name"], arguments=b["input"], server=b.get("type")!="tool_use", extra=extra))
    return out

# %% ../nbs/01_normalize.ipynb #97646970
def _openai_responses_tool_call(item):
    typ = item.get("type", "")
    if typ == "function_call":
        extra = {k:v for k,v in item.items() if k not in ("id","name","arguments")}
        return ToolCall(id=item["id"], name=item["name"], 
                        arguments=json.loads(item["arguments"]), extra=extra)
    if typ.endswith("_call"):  # web_search_call, file_search_call, etc.
        name = typ.removesuffix("_call")
        extra = {k:v for k,v in item.items() if k not in ("id")}
        return ToolCall(id=item.get("id",""), name=name, arguments=item.get("action", {}), server=True, extra=extra)

def _openai_responses_tool_calls(resp):
    "Extract Responses API tool call items as normalized tool calls."
    out = []
    for item in resp.get('output', []):
        if tc := _openai_responses_tool_call(item): out.append(tc)
    return out

# %% ../nbs/01_normalize.ipynb #32dd9e2a
def _openai_chat_tool_calls(resp):
    "Extract Chat Completions tool calls as normalized tool calls."
    out = []
    if not (tcs:= nested_idx(resp, 'choices', 0, 'message', 'tool_calls')): return out
    for tc in tcs:
        if not (fn:=tc.get("function")): continue
        extra = {k:v for k,v in tc.items() if k not in ("id","function")}
        out.append(ToolCall(id=tc.get("id",""), name=fn.get("name",""), arguments=json.loads(fn.get("arguments")), extra=extra))
    return out

# %% ../nbs/01_normalize.ipynb #e726bb44
def _gemini_tool_calls(resp):
    "Extract Gemini functionCall parts as normalized tool calls."
    out = []
    for i,p in enumerate(nested_idx(resp, 'candidates', 0, 'content', 'parts') or []):
        if not (fc:=p.get("functionCall")): continue
        extra = {k:v for k,v in p.items() if k != "functionCall"}
        out.append(ToolCall(id=fc.get("id", f"call_{i}"), name=fc.get("name", ""), arguments=fc.get("args") or {}, extra=extra))
    return out

# %% ../nbs/01_normalize.ipynb #0088e2d7
def usage_from_anthropic(resp):
    "Normalize Anthropic usage shape."
    if not (usg:=resp.get("usage")): return None
    pt = int(usg.get("input_tokens", 0) or 0)
    ct = int(usg.get("output_tokens", 0) or 0)
    return Usage(prompt_tokens=pt, completion_tokens=ct, total_tokens=pt + ct, raw=usg)

# %% ../nbs/01_normalize.ipynb #1589f622
def usage_from_openai(resp):
    "Normalize OpenAI usage shape(s)."
    if not (usg:=resp.get("usage")): return None
    pt = int(usg.get("prompt_tokens", usg.get("input_tokens", 0)) or 0)
    ct = int(usg.get("completion_tokens", usg.get("output_tokens", 0)) or 0)
    tt = int(usg.get("total_tokens", pt + ct) or (pt + ct))
    server_tool_use = dict(Counter(o['type'] for o in resp.get('output', []) if o.get('type') != 'function_call' and o.get('type', '').endswith('_call')))
    if server_tool_use: usg['server_tool_use'] = server_tool_use
    return Usage(prompt_tokens=pt, completion_tokens=ct, total_tokens=tt, raw=usg)

# %% ../nbs/01_normalize.ipynb #61c00016
def usage_from_gemini(resp):
    "Normalize Gemini usageMetadata shape."
    if not (usg:=resp.get("usageMetadata")): return None
    pt = int(usg.get("promptTokenCount", 0) or 0)
    ct = int(usg.get("candidatesTokenCount", 0) or 0)
    tt = int(usg.get("totalTokenCount", pt + ct) or (pt + ct))
    parts = nested_idx(resp, 'candidates', 0, 'content', 'parts') or []
    cand = nested_idx(resp, 'candidates', 0) or {}
    stu = {}
    if any("executableCode" in p for p in parts): stu["code_execution"] = sum(1 for p in parts if "executableCode" in p)
    if "groundingMetadata" in cand: stu["google_search"] = 1
    if stu: usg['server_tool_use'] = stu
    return Usage(prompt_tokens=pt, completion_tokens=ct, total_tokens=tt, raw=usg)

# %% ../nbs/01_normalize.ipynb #249a9d98
_OAI_RESP_FINISH = {'completed':'stop', 'incomplete':'length', 'failed':'content_filter'}
_GEM_FINISH = {'STOP':'stop', 'MAX_TOKENS':'length', 'SAFETY':'content_filter', 'BLOCKLIST':'content_filter'}
_ANT_FINISH = {'end_turn':'stop', 'tool_use':'tool_calls', 'max_tokens':'length'}

def _canon_finish(reason, mapping=None, tool_calls=None):
    "Canonicalize finish_reason to OpenAI Chat values: stop, tool_calls, length, content_filter."
    r = mapping.get(reason, reason) if mapping else reason
    if r == 'stop' and tool_calls and any(not tc.server for tc in tool_calls): r = 'tool_calls'
    return r

# %% ../nbs/01_normalize.ipynb #9945292f
def _openai_responses_parts(resp):
    parts = []
    for item in resp.get("output",[]):
        if (typ:=item.get("type")) == "message":
            for c in item.get("content", []):
                if (ctyp := c.get("type")) == "output_text":
                    parts.append(Part(type="text", text=c.get("text", ""), data=c))
                elif ctyp == "refusal":
                    parts.append(Part(type="refusal", text=c.get("refusal", ""), data=c))
        elif typ == "reasoning":
                for s in item.get("summary", []):
                    if s.get("type") == "summary_text":
                        parts.append(Part(type="thinking", text=s.get("text", ""), data=item))
        elif typ == "function_call" or typ.endswith("_call"):
            tc = _openai_responses_tool_call(item)
            parts.append(Part(type="tool_use", data=dict(id=tc.id, name=tc.name, arguments=tc.arguments, **tc.extra)))
    if not parts: return [Part(type="text", text="")]
    return parts

# %% ../nbs/01_normalize.ipynb #e0f3dc25
def normalize_openai_response(resp, model, provider:str="openai"):
    "Normalize OpenAI Responses API object into Completion."
    tcs = _openai_responses_tool_calls(resp)
    return Completion(
        model=str(resp.get("model") or model),
        message=Msg(role="assistant", content=_openai_responses_parts(resp)),
        finish_reason=_canon_finish(resp.get("status") or "completed", _OAI_RESP_FINISH, tcs),
        usage=usage_from_openai(resp),
        tool_calls=tcs,
        provider=provider,
        raw=resp)


# %% ../nbs/01_normalize.ipynb #c6561c34
def model_and_provider(model=None, provider=None): pass 

@delegates(model_and_provider)
def normalize_openai_response_event(ev, **kwargs):
    "Normalize OpenAI Responses API stream event into Delta."
    kwargs['model'],kwargs['provider'] = kwargs.get('model',None), kwargs.get('provider',None)
    typ = ev.get("type")
    if typ == "response.output_text.delta": return Delta(text=ev.get("delta"), raw=ev, **kwargs)
    if typ == "response.reasoning_text.delta": return Delta(thinking=ev.get("delta",""), raw=ev, **kwargs)
    if typ == "response.reasoning_summary_text.delta": return Delta(thinking=ev.get("delta",""), raw=ev, **kwargs)
    if typ == "response.output_item.done":
        if tc:= _openai_responses_tool_call(ev.get("item",{})): return Delta(tool_calls=[tc], raw=ev, **kwargs) 
    if typ == "response.completed":
        rsp = ev.get("response", {})
        tcs = _openai_responses_tool_calls(rsp)
        return Delta(finish_reason=_canon_finish(rsp.get("status") or "completed", _OAI_RESP_FINISH, tcs), usage=usage_from_openai(rsp), raw=ev, **kwargs)
    if typ == "error": raise api_error_from_event(ev, provider="openai", endpoint="responses.stream")
    return Delta(raw=ev, **kwargs)

# %% ../nbs/01_normalize.ipynb #9b9bac16
def normalize_openai_chat_completion(resp, model, provider="openai_chat"):
    "Normalize chat.completions response object into Completion."
    msg = nested_idx(resp, 'choices', 0, 'message') or {}
    parts = []
    if thinking := msg.get('reasoning_content'): parts.append(Part(type="thinking", text=thinking))
    if cts := msg.get('content'): parts.append(Part(type="text", text=cts))
    if ref := msg.get('refusal'): parts.append(Part(type="refusal", text=ref))
    tcs = _openai_chat_tool_calls(resp)
    for tc in tcs: parts.append(Part(type="tool_use", data=dict(id=tc.id, name=tc.name, arguments=tc.arguments, **tc.extra)))
    return Completion(
        model=resp.get("model") or model,
        message=Msg(role="assistant", content=parts),
        finish_reason=nested_idx(resp, 'choices', 0, 'finish_reason'),
        usage=usage_from_openai(resp),
        tool_calls=tcs,
        provider=provider,
        raw=resp)

# %% ../nbs/01_normalize.ipynb #d1af35e3
@delegates(model_and_provider)
def normalize_openai_chat_delta(ev, **kwargs):
    "Normalize a chat completion stream event."
    kwargs['model'],kwargs['provider'] = kwargs.get('model',None), kwargs.get('provider',None)
    if not (choices := ev.get("choices", [])): return Delta(usage=usage_from_openai(ev), raw=ev, **kwargs)
    thinking = nested_idx(choices, 0, 'delta', 'reasoning_content') or ''
    if thinking: return Delta(thinking=thinking, finish_reason=nested_idx(choices, 0, 'finish_reason'), usage=usage_from_openai(ev), raw=ev, **kwargs)
    txt = nested_idx(choices, 0, 'delta', 'content') or ''
    tcs = [ToolCall(id=tc.get("id"), name=nested_idx(tc, 'function', 'name'),
                    arguments={"_delta": nested_idx(tc, 'function', 'arguments')},
                    extra={'index':tc.get("index")}) for tc in ifnone(nested_idx(choices, 0, 'delta', 'tool_calls'), [])]
    return Delta(text=txt, tool_calls=tcs, finish_reason=nested_idx(choices, 0, 'finish_reason'), usage=usage_from_openai(ev), raw=ev, **kwargs)


# %% ../nbs/01_normalize.ipynb #35de7b1a
_ANT_PART = {
    'text':'text', 'thinking':'thinking', 'redacted_thinking':'thinking',
    'tool_use':'tool_use', 'server_tool_use':'tool_use', 'mcp_tool_use':'tool_use',
}

def _ant_part_type(typ):
    "Map Anthropic content block type to canonical PartType."
    if typ in _ANT_PART: return _ANT_PART[typ]
    if typ.endswith('_tool_result'): return 'server_tool_result'
    return typ

def normalize_anthropic_message(resp, model, provider="anthropic"):
    "Normalize Anthropic message response into Completion."
    tcs = _anthropic_tool_calls(resp)
    tc_map = {tc.id: tc for tc in tcs}
    parts = []
    for b in resp.get("content", []):
        typ = _ant_part_type(b.get("type", "text"))
        if typ == "thinking": parts.append(Part(type="thinking", text=b.get("thinking", ""), data=b))
        elif typ == "tool_use":
            tc = tc_map.get(b.get("id"))
            if tc: parts.append(Part(type="tool_use", data=dict(id=tc.id, name=tc.name, arguments=tc.arguments, **tc.extra)))
        else: parts.append(Part(type=typ, text=b.get("text", ""), data=b))
    if not parts: parts = [Part(type="text", text="")]
    return Completion(
        model=resp.get("model") or model,
        message=Msg(role="assistant", content=parts),
        finish_reason=_canon_finish(resp.get("stop_reason"), _ANT_FINISH, tcs),
        usage=usage_from_anthropic(resp),
        tool_calls=tcs,
        provider=provider,
        raw=resp)

# %% ../nbs/01_normalize.ipynb #ba9b0e20
_ANT_TC_TYPES = frozenset(("tool_use", "server_tool_use", "mcp_tool_use"))

@delegates(model_and_provider)
def normalize_anthropic_event(ev, **kwargs):
    "Normalize Anthropic SSE event into Delta."
    kwargs['model'],kwargs['provider'] = kwargs.get('model',None), kwargs.get('provider',None)
    typ = ev.get("type")
    if typ == "content_block_delta":
        d = ev.get("delta") or {}
        dtyp = d.get("type")
        if dtyp == "text_delta": return Delta(text=d.get("text", ""), raw=ev, **kwargs)
        if dtyp == "thinking_delta": return Delta(thinking=d.get("thinking", ""), raw=ev, **kwargs)
        if dtyp == "input_json_delta":
            return Delta(tool_calls=[ToolCall(id=str(ev.get("index", "")), name="",
                arguments={"_delta": d.get("partial_json") or ""})], raw=ev, **kwargs)
        return Delta(raw=ev, **kwargs)
    if typ == "content_block_start":
        b = ev.get("content_block") or {}
        if b.get("type") not in _ANT_TC_TYPES: return Delta(raw=ev, **kwargs)
        extra = {k:v for k,v in b.items() if k not in ("type","id","name","input")}
        return Delta(tool_calls=[ToolCall(id=b["id"], name=b["name"], arguments=b.get("input") or {}, server=b.get("type")!="tool_use", extra=extra)], raw=ev, **kwargs)
    if typ == "message_delta":
        d = ev.get("delta") or {}
        return Delta(finish_reason=_canon_finish(d.get("stop_reason"), _ANT_FINISH), usage=usage_from_anthropic(ev), raw=ev, **kwargs)
    if typ == "error": raise api_error_from_event(ev, provider="anthropic", endpoint="messages.stream")
    return Delta(raw=ev, **kwargs)

# %% ../nbs/01_normalize.ipynb #2cf597b2
def _gem_part_type(p):
    "Map Gemini part to canonical PartType."
    if 'functionCall' in p or 'toolCall' in p: return 'tool_use'
    if 'executableCode' in p or 'codeExecutionResult' in p: return 'tool_result'
    if p.get('thought'): return 'thinking'
    return 'text'

def normalize_gemini_generate(resp, model, provider="gemini"):
    "Normalize Gemini generateContent response."
    c0 = nested_idx(resp, 'candidates', 0) or {}
    gem_parts = nested_idx(c0, 'content', 'parts') or []
    parts = [Part(type=_gem_part_type(p), text=p.get("text",""), data=p) for p in gem_parts]
    tcs = _gemini_tool_calls(resp)
    if not parts: parts = [Part(type="text", text="")]
    return Completion(
        model=model,
        message=Msg(role="assistant", content=parts),
        finish_reason=_canon_finish(c0.get("finishReason"), _GEM_FINISH, tcs),
        usage=usage_from_gemini(resp),
        tool_calls=tcs,
        provider=provider,
        raw=resp)

# %% ../nbs/01_normalize.ipynb #893319e5
@delegates(model_and_provider)
def normalize_gemini_event(ev, emitted="", **kwargs):
    "Normalize Gemini stream event, returning incremental text delta."
    kwargs['model'],kwargs['provider'] = kwargs.get('model',None), kwargs.get('provider',None)
    c0 = nested_idx(ev, 'candidates', 0) or {}
    gem_parts = nested_idx(c0, 'content', 'parts') or []
    thinking = "".join(p.get("text","") for p in gem_parts if p.get("thought") and "text" in p)
    if thinking: return Delta(thinking=thinking,
        finish_reason=_canon_finish(c0.get("finishReason"), _GEM_FINISH),
        usage=usage_from_gemini(ev), raw=ev, **kwargs)
    txt = "".join(p.get("text","") for p in gem_parts if not p.get("thought") and "text" in p)
    tcs = _gemini_tool_calls(ev)
    delta_txt = txt[len(emitted):] if txt.startswith(emitted) else txt
    return Delta(text=delta_txt, tool_calls=tcs,
        finish_reason=_canon_finish(c0.get("finishReason"), _GEM_FINISH, tcs),
        usage=usage_from_gemini(ev), raw=ev, **kwargs)

