"""Provider payload normalization helpers."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_normalize.ipynb.

# %% auto #0
__all__ = ['ant_tc_types', 'provider', 'finish_reason', 'finish_reps_map', 'ToolCall', 'anthropic_tool_call',
           'anthropic_tool_calls', 'openai_responses_tool_call', 'openai_responses_tool_calls',
           'openai_chat_tool_calls', 'gemini_tool_calls', 'Usage', 'usage_from_anthropic', 'usage_from_openai',
           'usage_from_gemini', 'Completion', 'model_and_provider', 'canon_finish', 'openai_responses_parts',
           'normalize_openai_response', 'normalize_openai_chat_completion', 'normalize_anthropic_message',
           'normalize_gemini_generate']

# %% ../nbs/01_normalize.ipynb #eedf8f8f
import json
from dataclasses import dataclass, field, fields
from collections import Counter
from fastcore.utils import *
from fastcore.meta import delegates
from .types import *
from fastspec.errors import api_error_from_event

# %% ../nbs/01_normalize.ipynb #6bfe2ffc
@dataclass
class ToolCall:
    "Normalized tool call."
    id: str
    name: str
    arguments: dict = field(default_factory=dict)
    server: bool = False
    extra: dict = field(default_factory=dict)

# %% ../nbs/01_normalize.ipynb #112da633
ant_tc_types = ("tool_use", "server_tool_use", "mcp_tool_use")

def anthropic_tool_call(b):
    if b.get("type") in ant_tc_types:
        extra = {k:v for k,v in b.items() if k not in ("type","id","name","input")}
        return ToolCall(id=b["id"], name=b["name"], arguments=b.get("input") or {}, server=b.get("type")!="tool_use", extra=extra)

def anthropic_tool_calls(resp, delta=False):
    "Extract Anthropic tool_use blocks as normalized tool calls."
    out = []
    for b in resp.get("content", []):
        if tc:= anthropic_tool_call(b): out.append(tc)
    return out

# %% ../nbs/01_normalize.ipynb #97646970
def openai_responses_tool_call(item):
    typ = item.get("type", "")
    if typ == "function_call":
        extra = {k:v for k,v in item.items() if k not in ("id","name","arguments")}
        return ToolCall(id=item["id"], name=item["name"], 
                        arguments=json.loads(item["arguments"]), extra=extra)
    if typ.endswith("_call"):  # web_search_call, file_search_call, etc.
        name = typ.removesuffix("_call")
        extra = {k:v for k,v in item.items() if k not in ("id")}
        return ToolCall(id=item.get("id",""), name=name, arguments=item.get("action", {}), server=True, extra=extra)

def openai_responses_tool_calls(resp):
    "Extract Responses API tool call items as normalized tool calls."
    out = []
    for item in resp.get('output', []):
        if tc := openai_responses_tool_call(item): out.append(tc)
    return out

# %% ../nbs/01_normalize.ipynb #cee2cfab
def openai_chat_tool_calls(resp, delta=False):
    "Extract Chat Completions tool calls as normalized tool calls, optionally from streaming delta events"
    out = []
    key = 'delta' if delta else 'message'
    if not   (tcs:= nested_idx(resp, 'choices', 0, key, 'tool_calls')): return out
    for tc in tcs:
        if not (fn:=tc.get("function")): continue
        extra = {k:v for k,v in tc.items() if k not in ("id","function")}
        args  = json.loads(fn.get("arguments")) if not delta else {'_delta': fn.get("arguments")}
        out.append(ToolCall(id=tc.get("id",""), name=fn.get("name",""), arguments=args, extra=extra))
    return out

# %% ../nbs/01_normalize.ipynb #e726bb44
def gemini_tool_calls(resp):
    "Extract Gemini functionCall parts as normalized tool calls."
    out = []
    for i,p in enumerate(nested_idx(resp, 'candidates', 0, 'content', 'parts') or []):
        if not (fc:=p.get("functionCall")): continue
        extra = {k:v for k,v in p.items() if k != "functionCall"}
        out.append(ToolCall(id=fc.get("id", f"call_{i}"), name=fc.get("name", ""), arguments=fc.get("args") or {}, extra=extra))
    return out

# %% ../nbs/01_normalize.ipynb #000b42b2
@dataclass(frozen=True)
class Usage:
    "Normalized usage."
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    raw: dict = field(default_factory=dict)

# %% ../nbs/01_normalize.ipynb #0088e2d7
def usage_from_anthropic(resp):
    "Normalize Anthropic usage shape."
    if not (usg:=resp.get("usage")): return None
    pt = int(usg.get("input_tokens", 0) or 0)
    ct = int(usg.get("output_tokens", 0) or 0)
    return Usage(prompt_tokens=pt, completion_tokens=ct, total_tokens=pt + ct, raw=usg)

# %% ../nbs/01_normalize.ipynb #1589f622
def usage_from_openai(resp):
    "Normalize OpenAI usage shape(s)."
    if not (usg:=resp.get("usage")): return None
    pt = int(usg.get("prompt_tokens", usg.get("input_tokens", 0)) or 0)
    ct = int(usg.get("completion_tokens", usg.get("output_tokens", 0)) or 0)
    tt = int(usg.get("total_tokens", pt + ct) or (pt + ct))
    server_tool_use = dict(Counter(o['type'] for o in resp.get('output', []) if o.get('type') != 'function_call' and o.get('type', '').endswith('_call')))
    if server_tool_use: usg['server_tool_use'] = server_tool_use
    return Usage(prompt_tokens=pt, completion_tokens=ct, total_tokens=tt, raw=usg)

# %% ../nbs/01_normalize.ipynb #61c00016
def usage_from_gemini(resp):
    "Normalize Gemini usageMetadata shape."
    if not (usg:=resp.get("usageMetadata")): return None
    pt = int(usg.get("promptTokenCount", 0) or 0)
    ct = int(usg.get("candidatesTokenCount", 0) or 0)
    tt = int(usg.get("totalTokenCount", pt + ct) or (pt + ct))
    parts = nested_idx(resp, 'candidates', 0, 'content', 'parts') or []
    cand = nested_idx(resp, 'candidates', 0) or {}
    stu = {}
    if any("executableCode" in p for p in parts): stu["code_execution"] = sum(1 for p in parts if "executableCode" in p)
    if "groundingMetadata" in cand: stu["google_search"] = 1
    if stu: usg['server_tool_use'] = stu
    return Usage(prompt_tokens=pt, completion_tokens=ct, total_tokens=tt, raw=usg)

# %% ../nbs/01_normalize.ipynb #8c65aa2a
@dataclass(frozen=True)
class Completion:
    "Normalized completion response."
    model: str
    message: Msg
    finish_reason: str = None
    usage: Usage = None
    tool_calls: List[ToolCall] = field(default_factory=list)
    provider: str = None
    raw: dict = field(default_factory=dict)

# %% ../nbs/01_normalize.ipynb #f88c3f6d
def model_and_provider(model=None, provider=None): pass

# %% ../nbs/01_normalize.ipynb #bd5ae842
provider = str_enum('provider', 'openai', 'openai_chat', 'anthropic', 'gemini')
finish_reason = str_enum('finish_reason', 'stop', 'tool_calls', 'length', 'content_filter')

finish_reps_map = {}
finish_reps_map[provider.openai]    = {'completed':'stop', 'incomplete':'length', 'failed':'content_filter'}
finish_reps_map[provider.anthropic] = {'end_turn':'stop', 'tool_use':'tool_calls', 'max_tokens':'length'}
finish_reps_map[provider.gemini]    = {'STOP':'stop', 'MAX_TOKENS':'length', 'SAFETY':'content_filter', 'BLOCKLIST':'content_filter'}

def canon_finish(reason, provider, tcs=None):
    "Canonicalize finish_reason to OpenAI Chat values: stop, tool_calls, length, content_filter."
    r =  finish_reps_map.get(provider, {}).get(reason, reason)
    return finish_reason.tool_calls if r==finish_reason.stop and any(~L(tcs).attrgot('server')) else r 

# %% ../nbs/01_normalize.ipynb #9945292f
def openai_responses_parts(resp):
    parts = []
    for item in resp["output"]:
        if (typ:=item["type"]) == "message":
            for c in item["content"]:
                if (ctyp := c["type"]) == "output_text": 
                    parts.append(Part(type=PartType.text, text=c['text'], data=c))
                elif ctyp == "refusal":
                    parts.append(Part(type=PartType.refusal, text=c['refusal'], data=c))
        elif typ == "reasoning":
            for s in item["summary"]: parts.append(Part(type=PartType.thinking, text=s['text'], data=item))
        elif typ == "function_call" or typ.endswith("_call"):
            tc = openai_responses_tool_call(item)
            tdata = dict(id=tc.id, name=tc.name, arguments=tc.arguments, server=tc.server, **tc.extra)
            parts.append(Part(type=PartType.tool_use, data=tdata))
    return parts

# %% ../nbs/01_normalize.ipynb #e0f3dc25
def normalize_openai_response(resp, model, provider=provider.openai):
    "Normalize OpenAI Responses API object into Completion."
    tcs = openai_responses_tool_calls(resp)
    return Completion(
        model=resp.get("model") or model,
        message=Msg(role="assistant", content=openai_responses_parts(resp)),
        finish_reason=canon_finish(resp.get("status"), provider, tcs),
        usage=usage_from_openai(resp),
        tool_calls=tcs,
        provider=provider,
        raw=resp)

# %% ../nbs/01_normalize.ipynb #9b9bac16
def normalize_openai_chat_completion(resp, model, provider="openai_chat"):
    "Normalize chat.completions response object into Completion."
    msg = nested_idx(resp, 'choices', 0, 'message') or {}
    parts = []
    if thinking := msg.get('reasoning_content'): parts.append(Part(type="thinking", text=thinking))
    if cts := msg.get('content'): parts.append(Part(type="text", text=cts))
    if ref := msg.get('refusal'): parts.append(Part(type="refusal", text=ref))
    tcs = openai_chat_tool_calls(resp)
    for tc in tcs: parts.append(Part(type="tool_use", data=dict(id=tc.id, name=tc.name, arguments=tc.arguments, server=tc.server, **tc.extra)))
    return Completion(
        model=resp.get("model") or model,
        message=Msg(role="assistant", content=parts),
        finish_reason=nested_idx(resp, 'choices', 0, 'finish_reason'),
        usage=usage_from_openai(resp),
        tool_calls=tcs,
        provider=provider,
        raw=resp)

# %% ../nbs/01_normalize.ipynb #35de7b1a
def _ant_part_type(typ):
    "Map Anthropic content block type to canonical PartType."
    ant_parts_mapping = {'text':PartType.text, 
                         'thinking':PartType.thinking, 
                         'redacted_thinking':PartType.thinking, 
                         'tool_use':PartType.tool_use, 
                         'server_tool_use':PartType.tool_use,
                         'mcp_tool_use':PartType.tool_use}
    if typ in ant_parts_mapping: return ant_parts_mapping[typ]
    if typ.endswith('_tool_result'): return PartType.server_tool_result
    return typ

def normalize_anthropic_message(resp, model, provider="anthropic"):
    "Normalize Anthropic message response into Completion."
    tcs = anthropic_tool_calls(resp)
    tc_map = {tc.id: tc for tc in tcs}
    parts = []
    for b in resp.get("content", []):
        typ = _ant_part_type(b.get("type", "text"))
        if typ == PartType.thinking: parts.append(Part(type=PartType.thinking, text=b.get("thinking", ""), data=b))
        elif typ == "tool_use":
            tc = tc_map.get(b.get("id"))
            if tc: parts.append(Part(type=PartType.tool_use, data=dict(id=tc.id, name=tc.name, arguments=tc.arguments, server=tc.server, **tc.extra)))
        else: parts.append(Part(type=typ, text=b.get("text", ""), data=b))
    if not parts: parts = [Part(type=PartType.text, text="")]
    return Completion(
        model=resp.get("model") or model,
        message=Msg(role="assistant", content=parts),
        finish_reason=canon_finish(resp.get("stop_reason"), 'anthropic'),
        usage=usage_from_anthropic(resp),
        tool_calls=tcs,
        provider=provider,
        raw=resp)

# %% ../nbs/01_normalize.ipynb #2cf597b2
def _gem_part_type(p):
    "Map Gemini part to canonical PartType."
    if 'functionCall' in p or 'toolCall' in p: return PartType.tool_use
    if 'executableCode' in p or 'codeExecutionResult' in p: return PartType.tool_result
    if p.get('thought'): return PartType.thinking
    return PartType.text

def normalize_gemini_generate(resp, model, provider="gemini"):
    "Normalize Gemini generateContent response."
    c0 = nested_idx(resp, 'candidates', 0) or {}
    gem_parts = nested_idx(c0, 'content', 'parts') or []
    tcs = gemini_tool_calls(resp)
    tc_map = {tc.id: tc for tc in tcs}
    parts = []
    for p in gem_parts:
        typ = _gem_part_type(p)
        if typ == 'tool_use':
            fc = p.get('functionCall') or p.get('toolCall') or {}
            tc = tc_map.get(fc.get('id'))
            if tc: parts.append(Part(type=PartType.tool_use, data=dict(id=tc.id, name=tc.name, arguments=tc.arguments, server=tc.server, **tc.extra)))
        else: parts.append(Part(type=typ, text=p.get("text",""), data=p))
    if not parts: parts = [Part(type=PartType.text, text="")]
    return Completion(
        model=model,
        message=Msg(role="assistant", content=parts),
        finish_reason=canon_finish(c0.get("finishReason"), 'gemini', tcs),
        usage=usage_from_gemini(resp),
        tool_calls=tcs,
        provider=provider,
        raw=resp)
