# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_oai_chat.ipynb.

# %% auto #0
__all__ = ['api_ns', 'norm_tool_calls', 'norm_finish', 'norm_parts', 'norm_sse_event', 'delta_index_fn', 'acollect_stream',
           'denorm_tool_use', 'denorm_assistant', 'denorm_tool', 'denorm_msgs', 'denorm_tool_schs',
           'denorm_tool_choice', 'denorm_reasoning', 'denorm_web_search', 'denorm_system', 'denorm_user',
           'denorm_image', 'denorm_audio', 'denorm_file', 'denorm_tool_result', 'mk_payload', 'get_hdrs', 'cost']

# %% ../nbs/03_oai_chat.ipynb #493e3606
import json
from collections import Counter
from fastcore.utils import *
from fastcore.meta import *
from fastspec.errors import api_error_from_event

from .types import *
from .streaming import *
from .streaming import _acollect_stream
from .openai_responses import norm_usage

# %% ../nbs/03_oai_chat.ipynb #b4f0e4d0
def norm_tool_calls(resp, delta=False):
    "Extract Chat Completions tool calls as normalized tool calls, optionally from streaming delta events"
    out = []
    key = 'delta' if delta else 'message'
    if not   (tcs:= nested_idx(resp, 'choices', 0, key, 'tool_calls')): return out
    for tc in tcs:
        if not (fn:=tc.get("function")): continue
        extra = {k:v for k,v in tc.items() if k not in ("id","function")}
        args  = json.loads(fn.get("arguments")) if not delta else {'_delta': fn.get("arguments")}
        out.append(ToolCall(id=tc.get("id",""), name=fn.get("name",""), arguments=args, extra=extra))
    return out

# %% ../nbs/03_oai_chat.ipynb #b387d62d
def norm_finish(resp, tcs=None):
    "Canonicalize finish_reason to OpenAI Chat values: stop, tool_calls, length, content_filter."
    r = nested_idx(resp, 'choices', 0, 'finish_reason')
    return FinishReason.tool_calls if r==FinishReason.stop and any(~L(tcs).attrgot('server')) else r 

# %% ../nbs/03_oai_chat.ipynb #5abf90bb
def norm_parts(resp):
    "Normalize chat.completions response object into Completion."
    msg = nested_idx(resp, 'choices', 0, 'message') or {}
    parts = []
    if thinking := msg.get('reasoning_content'): parts.append(Part(type="thinking", text=thinking))
    if cts := msg.get('content'): parts.append(Part(type="text",text=cts,data=dict(citations=msg.get('annotations',[]))))
    if ref := msg.get('refusal'): parts.append(Part(type="refusal",text=ref))
    tcs = norm_tool_calls(resp)
    for tc in tcs: 
        tdata = {**tc.extra, 'id':tc.id, 'name':tc.name, 'arguments':tc.arguments, 'server':tc.server}
        parts.append(Part(type="tool_use", data=tdata))
    return parts

# %% ../nbs/03_oai_chat.ipynb #9baac40e
def norm_sse_event(ev, **kwargs):
    "Normalize a chat completion stream event."
    # usage always arrives as a single final event with choices: []
    fin = nested_idx(ev, 'choices', 0, 'finish_reason')
    tcs = norm_tool_calls(ev, delta=True)
    if (dlt:=nested_idx(ev, 'choices', 0, 'delta')) is not None:
        text, thinking, refusal = dlt.get('content'), dlt.get('reasoning_content'), dlt.get('refusal')
    else: text, thinking, refusal = None,None,None
    if ev.get("error"): raise api_error_from_event(ev)
    return Delta(text=text, thinking=thinking, refusal=refusal, tool_calls=tcs, finish_reason=fin, usage=norm_usage(ev), raw=ev, **kwargs)

# %% ../nbs/03_oai_chat.ipynb #cfec45b4
def delta_index_fn(d, typ, last_typ, last_idx):
    'Returns accumulation index for current delta and updated last idx'
    if d.tool_calls: 
        tc_idx = nested_idx(d.tool_calls, 0, 'extra', 'index')
        return f"tool_{tc_idx}", last_idx
    if not (last_typ or last_idx): return 0,0
    if typ == last_typ: return last_idx, last_idx
    return last_idx + 1, last_idx + 1

# %% ../nbs/03_oai_chat.ipynb #e7f8965b
@delegates(_acollect_stream, but=['index_fn', 'api_name'])
async def acollect_stream(resp, **kwargs):
    res = _acollect_stream(norm_and_yield(resp, norm_sse_event), index_fn=delta_index_fn, api_name='openai_chat', **kwargs)
    async for o in res: yield o

# %% ../nbs/03_oai_chat.ipynb #5a7129f1
def denorm_tool_use(p:Part):
    "Convert canonical tool_use Part to OpenAI Chat tool_call dict."
    return dict(id=p.data.get('id'), type='function', function=dict(name=p.data.get('name'), arguments=json.dumps(p.data.get('arguments', '{}'))))

def denorm_assistant(m:Msg):
    "Convert canonical assistant Msg to OpenAI Chat assistant message + synthetic tool responses for server tools."
    tcs, srv_responses, texts = [], [], []
    for p in m.content:
        if p.type == PartType.tool_use:
            tcs.append(denorm_tool_use(p))
            if p.data.get('server'):
                srv_txt = f"[Server tool `{p.data['name']}` executed successfully, results are generated]"
                srv_responses.append(dict(role='tool', tool_call_id=p.data['id'], content=srv_txt))
        elif p.type == PartType.text: texts.append(p)
    msg = dict(role='assistant')
    if texts: msg['content'] = texts[0].text if len(texts)==1 else [dict(type='text', text=p.text or '') for p in texts]
    if tcs: msg['tool_calls'] = tcs
    thinking = [p for p in m.content if p.type == PartType.thinking]
    if thinking: msg['reasoning_content'] = ''.join(p.text or '' for p in thinking)
    return [msg] + srv_responses

def denorm_tool(m:Msg):
    "Convert canonical tool Msg to list of OpenAI Chat tool messages."
    return [denorm_tool_result(p) for p in m.content if p.type == PartType.tool_result]

def denorm_msgs(msgs:list[Msg]):
    "Convert list of canonical Msgs to OpenAI Chat messages."
    res = []
    for m in msgs:
        if   m.role == 'user':      res.append(denorm_user(m))
        elif m.role == 'assistant': res.extend(denorm_assistant(m))
        elif m.role == 'tool':      res.extend(denorm_tool(m))
    return res

# %% ../nbs/03_oai_chat.ipynb #76f84455
def denorm_tool_schs(tools):
    "Passthrough — canonical format is already OpenAI Chat."
    return tools

# %% ../nbs/03_oai_chat.ipynb #659fdab9
def denorm_tool_choice(v):
    "Map canonical tool_choice to OpenAI Chat format."
    _tc_modes = {'auto', 'required', 'any', 'force', 'none', 'off', 'disabled'}
    if v is None: return None
    if v in _tc_modes: return v if v in ('auto','none','required') else {'any':'required','force':'required','off':'none','disabled':'none'}[v]
    return {'type': 'function', 'function': {'name': v}}

# %% ../nbs/03_oai_chat.ipynb #02ba4ab7
def denorm_reasoning(v): return v  # passthrough as reasoning_effort param

# %% ../nbs/03_oai_chat.ipynb #57b4969e
def denorm_web_search(v): return v

# %% ../nbs/03_oai_chat.ipynb #0f8cb4d1
def denorm_system(sp, msgs): 
    msgs.insert(0, dict(role='system', content=sys_text(part_txt(sp))))
    return msgs

# %% ../nbs/03_oai_chat.ipynb #13654225
def denorm_user(m:Msg):
    "Convert canonical user Msg to OpenAI Chat user message."
    parts = []
    for p in m.content:
        if   p.type == PartType.text:        parts.append({"type": "text", "text": p.text or ""})
        elif p.type == PartType.input_image: parts.append(denorm_image(p))
        elif p.type == PartType.input_audio: parts.append(denorm_audio(p))
        elif p.type == PartType.input_video: raise ValueError("OpenAI Chat API does not support video input")
        elif p.type == PartType.input_file:  parts.append(denorm_file(p))
    if len(parts) == 1 and parts[0].get('type') == 'text': return dict(role='user', content=parts[0]['text'])
    return dict(role='user', content=parts)

# %% ../nbs/03_oai_chat.ipynb #82f3615b
def denorm_image(p): return {"type": "image_url", "image_url": {"url": p.text}}

# %% ../nbs/03_oai_chat.ipynb #ab69ef9a
def denorm_audio(p):
    _mime_audio_fmt = {'audio/wav':'wav', 'audio/mpeg':'mp3', 'audio/mp3':'mp3'}
    if not (b64:=data_url(p.text)): raise ValueError("OpenAI Chat audio input requires base64 data URL")
    return {"type": "input_audio", "input_audio": {"data": b64[1], "format": _mime_audio_fmt.get(b64[0], 'wav')}}

# %% ../nbs/03_oai_chat.ipynb #e2cd77ad
def denorm_file(p):
    if (b64:=data_url(p.text)): return {"type": "file", "file": {"file_data": p.text, "filename": f"upload.{b64[0].split('/')[-1]}"}}
    raise ValueError("OpenAI Chat file input requires base64 data URL or file_id, not URLs")

# %% ../nbs/03_oai_chat.ipynb #0e9751c8
def denorm_tool_result(p:Part):
    "Convert canonical tool_result Part to OpenAI Chat tool message."
    if isinstance(p.text, list): raise ValueError("OpenAI Chat does not support media in tool results")
    return dict(role='tool', tool_call_id=p.data.get('id') or p.data.get('call_id', ''), content=str(p.text))

# %% ../nbs/03_oai_chat.ipynb #d2f55686
@delegates(payload_kwargs)
def mk_payload(msgs, model, **kwargs):
    payload = dict(model=model, messages=denorm_msgs(msgs))
    if sp:=kwargs.get('system'):            payload['messages'] = denorm_system(sp, payload['messages'])
    if kwargs.get('stream'):                payload.update(stream=True, stream_options={"include_usage": True})
    if mt:=kwargs.get('max_tokens'):        payload['max_tokens'] = mt
    if tools:=kwargs.get('tools'):          payload['tools'] = denorm_tool_schs(tools)
    if tchc:=kwargs.get('tool_choice'):     payload['tool_choice'] = denorm_tool_choice(tchc)
    if thk:=kwargs.get('reasoning_effort'): payload['reasoning_effort'] = denorm_reasoning(thk)
    if (wopts:=kwargs.get('web_search_options')) is not None: 
        payload['web_search_options'] = denorm_web_search(wopts)
    if (temp:=kwargs.get('temperature')) is not None: payload['temperature'] = temp
    return payload

# %% ../nbs/03_oai_chat.ipynb #16e813d2
def get_hdrs(api_key=None):
    return {"Authorization": f"Bearer {get_api_key(api_key, 'OPENAI_API_KEY')}"}

# %% ../nbs/03_oai_chat.ipynb #f89e2bf6
def cost(usage, m):
    raw = usage.raw
    pd, cd = raw.get('prompt_tokens_details', {}), raw.get('completion_tokens_details', {})
    cached = pd.get('cached_tokens', 0)
    in_audio, out_audio = pd.get('audio_tokens', 0), cd.get('audio_tokens', 0)
    in_txt  = raw['prompt_tokens']     - cached - in_audio
    out_txt = raw['completion_tokens'] - out_audio
    cost  = in_txt  * m.input_cost_per_token  + out_txt * m.output_cost_per_token
    cost += cached  * m.get('cache_read_input_token_cost', 0)
    cost += in_audio  * m.get('input_cost_per_audio_token', 0)
    cost += out_audio * m.get('output_cost_per_audio_token', 0)
    return cost

# %% ../nbs/03_oai_chat.ipynb #e2b0908e
api_ns = dict(norm_tool_calls=norm_tool_calls,
                norm_parts=norm_parts,
                norm_finish=norm_finish,
                norm_usage=norm_usage,
                acollect_stream=acollect_stream,
                mk_payload=mk_payload,
                cost=cost,
                get_hdrs=get_hdrs, 
                op_path=('chat.create_chat_completion','chat.create_chat_completion'))
api_registry.register('openai_chat', **api_ns)
