# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_oai_responses.ipynb.

# %% auto #0
__all__ = ['api_ns', 'norm_tool_call', 'norm_tool_calls', 'norm_usage', 'norm_finish', 'search_hits', 'norm_parts', 'raw_msg',
           'norm_sse_event', 'delta_index_fn', 'collate_raw', 'acollect_stream', 'denorm_tool_use', 'denorm_tool',
           'denorm_assistant', 'denorm_msgs', 'denorm_tool_schs', 'denorm_tool_choice', 'denorm_reasoning',
           'denorm_web_search', 'denorm_system', 'denorm_user', 'denorm_image', 'denorm_video', 'denorm_file',
           'denorm_tool_result', 'mk_payload', 'get_hdrs', 'cost', 'fix_payload']

# %% ../nbs/02_oai_responses.ipynb #591f55b5
import json
from collections import Counter
from fastcore.utils import *
from fastcore.meta import *
from fasttransport.errors import api_error_from_event

from .types import *
from aidialog.msg_parts import (Completion, Part, PartType, Msg, Text, Thinking, Refusal, ToolUse, ToolResult, tool_text, MdStr,
    InputImage, InputAudio, InputVideo, InputFile, mk_tool_res_msg, sys_text, part_txt, data_url)
from .streaming import *
from .streaming import mk_acollect_stream

# %% ../nbs/02_oai_responses.ipynb #479243ae
def norm_tool_call(item):
    typ = item.get("type", "")
    if typ == "function_call":
        raw = {k:v for k,v in item.items() if k not in ("call_id","name","arguments")}
        return ToolUse(id=item.get("call_id") or item["id"], name=item["name"], arguments=json.loads(item["arguments"]), raw=raw)
    if typ.endswith("_call"):  # a call the server ran: OpenAI's hosted items carry an `action`, a Responses server's `server_tool_call` its `arguments` and `output` (`md` when that output is markdown)
        raw = {k:v for k,v in item.items() if k not in ("id","name","arguments","output","action","md")}
        args = json.loads(item["arguments"]) if "arguments" in item else item.get("action", {})
        out = item.get("output")
        return ToolUse(id=item.get("id",""), name=item.get("name") or typ.removesuffix("_call"), arguments=args, server=True, text=MdStr(out) if item.get("md") else out, raw=raw)

def norm_tool_calls(resp):
    "Extract Responses API tool call items as normalized tool calls."
    out = []
    for item in resp.get('output', []):
        if tc := norm_tool_call(item): out.append(tc)
    return out

# %% ../nbs/02_oai_responses.ipynb #a199aab4
def norm_usage(resp):
    "Normalize OpenAI usage shape(s)."
    if not (usg:=resp.get("usage")): return None
    pt = int(usg.get("prompt_tokens", usg.get("input_tokens", 0)) or 0)
    ct = int(usg.get("completion_tokens", usg.get("output_tokens", 0)) or 0)
    tt = int(usg.get("total_tokens", pt + ct) or (pt + ct))
    pd = usg.get("prompt_tokens_details") or usg.get("input_tokens_details") or {}
    cd = usg.get("completion_tokens_details") or usg.get("output_tokens_details") or {}
    cached = int(pd.get("cached_tokens", 0) or 0)
    reasoning = int(cd.get("reasoning_tokens", 0) or 0)
    server_tool_use = dict(Counter(o['type'] for o in resp.get('output', []) if o.get('type') != 'function_call' and o.get('type', '').endswith('_call')))
    if server_tool_use: usg['server_tool_use'] = server_tool_use
    return Usage(prompt_tokens=pt, completion_tokens=ct, total_tokens=tt,
        cached_tokens=cached, reasoning_tokens=reasoning, raw=usg)


# %% ../nbs/02_oai_responses.ipynb #95102df4
def norm_finish(resp, tcs=None):
    "Canonicalize finish_reason to OpenAI Chat values: stop, tool_calls, length, content_filter."
    reason = resp.get("status")
    mp = dict(completed=FinishReason.stop, incomplete=FinishReason.length, failed=FinishReason.content_filter)
    r =  mp.get(reason, reason)
    return FinishReason.tool_calls if r==FinishReason.stop and any(~L(tcs).attrgot('server')) else r 

# %% ../nbs/02_oai_responses.ipynb #bbfb99b9
def search_hits(parts):
    "OpenAI reports no result for a hosted search, so a server call's empty `text` becomes the message's cited sources, one `title: url` line each"
    hits = {c['url']: c.get('title', '') for p in parts if isinstance(p, Text) for c in p.citations or [] if c.get('url')}
    for p in parts:
        if isinstance(p, ToolUse) and p.server and not p.text: p.text = MdStr('\n'.join(f"{t}: {u}" for u,t in hits.items()))
    return parts

# %% ../nbs/02_oai_responses.ipynb #4ef27720
def norm_parts(resp):
    parts = []
    for item in resp["output"]:
        if (typ:=item["type"]) == "message":
            for c in item["content"]:
                if (ctyp := c["type"]) == "output_text":
                    c['citations'] = c.pop('annotations', [])
                    parts.append(Text(c['text'], citations=c['citations'], raw=c))
                elif ctyp == "refusal": parts.append(Refusal(c['refusal'], raw=c))
        elif typ == "reasoning":
            for s in item["summary"]: parts.append(Thinking(s['text'], raw=item))
        elif typ == "function_call" or typ.endswith("_call"): parts.append(norm_tool_call(item))
    return search_hits(parts)

# %% ../nbs/02_oai_responses.ipynb #2aaab962
def raw_msg(resp):
    "The output items as the API sent them"
    return resp['output']

# %% ../nbs/02_oai_responses.ipynb #ef2d19f3
@patch(as_prop=True)
def response_id(self:Completion):
    "Provider continuation identifier."
    if self.vendor_name == 'codex': return
    if rid := self.raw.get('response_id'): return rid
    if self.api_name != 'openai': return
    if rid := self.raw.get('id'): return rid
    for d in reversed(self.raw.get('deltas', [])):
        if rid := nested_idx(d.raw, 'response', 'id'): return rid

# %% ../nbs/02_oai_responses.ipynb #7cd48aa5
def norm_sse_event(ev, **kwargs):
    "Normalize OpenAI Responses API stream event into Delta."
    ev = obj2dict(ev)
    typ = ev.get("type")
    if typ == "response.output_text.delta":            return Delta(text=ev.get("delta"), raw=ev, **kwargs)
    if typ == "response.reasoning_text.delta":         return Delta(thinking=ev.get("delta",""), raw=ev, **kwargs)
    if typ == "response.reasoning_summary_text.delta": return Delta(thinking=ev.get("delta",""), raw=ev, **kwargs)
    if typ == "response.output_text.annotation.added": return Delta(citations=[ev.get("annotation")], raw=ev, **kwargs)
    if typ == "response.output_item.done":
        item = ev.get("item", {})
        itype = item.get("type", "")
        if itype == "function_call" or itype.endswith("_call"): return Delta(tool_calls=[norm_tool_call(item)], raw=ev, **kwargs)
        return Delta(raw=ev, **kwargs)
    if typ in ("response.completed", "response.incomplete"):
        resp = ev.get("response", {})
        return Delta(finish_reason=norm_finish(resp), usage=norm_usage(resp), raw=ev, **kwargs)
    if typ == "error": raise api_error_from_event(ev)

# %% ../nbs/02_oai_responses.ipynb #66370799
def delta_index_fn(d, typ, last_typ, last_idx):
    'Returns accumulation index for current delta and updated last idx'
    idx = nested_idx(d, 'raw', 'output_index')
    return idx, idx

# %% ../nbs/02_oai_responses.ipynb #689e31b0
def collate_raw(deltas):
    "The output items rebuilt from a stream's events"
    return [d.raw['item'] for d in deltas if d.raw.get('type') == 'response.output_item.done']

# %% ../nbs/02_oai_responses.ipynb #021b5257
@delegates(mk_acollect_stream, but=['index_fn', 'api_name'])
async def acollect_stream(resp, **kwargs):
    res = mk_acollect_stream(norm_and_yield(resp, norm_sse_event), index_fn=delta_index_fn, api_name='openai', **kwargs)
    async for o in res:
        if isinstance(o, Completion): search_hits(o.message.content)
        yield o

# %% ../nbs/02_oai_responses.ipynb #9608e813
def _sanid(id_str): return id_str[:64] # codex max 64 char limit

# %% ../nbs/02_oai_responses.ipynb #b746c82b
def denorm_tool_use(p:ToolUse):
    "Convert canonical tool_use Part back to OpenAI Responses function_call item."
    return dict(type='function_call', call_id=_sanid(p.id), name=p.name, arguments=json.dumps(p.arguments))

# %% ../nbs/02_oai_responses.ipynb #8f42adf7
def denorm_tool(m:Msg): return [denorm_tool_result(p) for p in m.content if isinstance(p, ToolResult)]

# %% ../nbs/02_oai_responses.ipynb #67c8de13
def denorm_assistant(m:Msg):
    "The output items as the API sent them, else the message's text and tool calls as items"
    if m.raw: return m.raw
    items = []
    for p in m.content:
        if isinstance(p, ToolUse): items.append(denorm_tool_use(p))
        elif isinstance(p, Text): items.append(dict(type="message", role="assistant", content=[dict(type="output_text", text=p.text or '')]))
    return items

# %% ../nbs/02_oai_responses.ipynb #64883b99
def denorm_msgs(msgs:list[Msg]):
    res = []
    for m in msgs:
        if m.role == 'user':        res.append(denorm_user(m))
        elif m.role == 'assistant': res.extend(denorm_assistant(m))
        elif m.role == 'tool':      res.extend(denorm_tool(m))
    return res

# %% ../nbs/02_oai_responses.ipynb #f280226d
def denorm_tool_schs(tools):
    "Convert canonical tools to OpenAI Responses format."
    out = []
    for t in tools:
        if isinstance(t, dict) and t.get('type')=='function' and 'name' in t and 'parameters' in t: out.append(t); continue
        fn = fn_schema(t)
        if fn is None: out.append(t); continue
        name, desc, params = fn
        out.append(dict(type='function', name=name, description=desc, parameters=params))
    return out

# %% ../nbs/02_oai_responses.ipynb #a6bc189c
def denorm_tool_choice(v):
    "Map canonical tool_choice to OpenAI Responses format."
    _tc_modes = {'auto', 'required', 'any', 'force', 'none', 'off', 'disabled'}
    if v is None: return None
    if v in _tc_modes: return v if v in ('auto','none','required') else dict(auto='auto', any='required', force='required', off='none', disabled='none')[v]
    return {'type': 'function', 'name': v}

# %% ../nbs/02_oai_responses.ipynb #b1dcf1d3
def denorm_reasoning(v):
    "Map canonical reasoning_effort to OpenAI Responses reasoning param."
    if v is None: return None
    if isinstance(v, int): return {'level': v}  # a 0-3 level, for a Responses server that resolves it per model
    return {'effort': v} if isinstance(v, str) else v

# %% ../nbs/02_oai_responses.ipynb #e11c15c0
def denorm_web_search(v):
    "Map canonical web_search_options to OpenAI Responses web_search_preview tool."
    t = {"type": "web_search_preview"}
    if (typ := (v or {}).get("type")): t["type"] = typ
    if (s := (v or {}).get("search_context_size")): t["search_context_size"] = s
    if (u := (v or {}).get("user_location")): t["user_location"] = u
    return t

# %% ../nbs/02_oai_responses.ipynb #18346f93
def denorm_system(sp): return sys_text(part_txt(sp))

# %% ../nbs/02_oai_responses.ipynb #8c06da0c
def denorm_user(m:Msg):
    "Convert canonical user Msg to OpenAI Responses input message."
    parts = []
    for p in m.content:
        if   isinstance(p, Text):       parts.append({"type": "input_text", "text": p.text or ""})
        elif isinstance(p, InputImage): parts.append(denorm_image(p))
        elif isinstance(p, InputAudio): raise ValueError("OpenAI Responses API does not support audio input; Coming Soon.") 
        elif isinstance(p, InputVideo): parts.append(denorm_video(p))
        elif isinstance(p, InputFile):  parts.append(denorm_file(p))
    return dict(type='message', role='user', content=parts)

# %% ../nbs/02_oai_responses.ipynb #4ced282f
def denorm_image(p): return {"type": "input_image", "image_url": p.text}

# %% ../nbs/02_oai_responses.ipynb #e0ca62d6
def denorm_video(p): return {"type": "input_video", "video_url": p.text}

# %% ../nbs/02_oai_responses.ipynb #6e79a133
def denorm_file(p):
    if (b64:=data_url(p.text)): return dict(type="input_file", file_data=p.text, filename=f"upload.{b64[0].split('/')[-1]}")
    return {"type": "input_file", "file_url": p.text}

# %% ../nbs/02_oai_responses.ipynb #145b1c79
def denorm_tool_result(m:ToolResult):
    "Convert canonical tool result back to OpenAI Responses function_call_output item."
    cid = _sanid(m.id or (m.raw or {}).get('call_id'))
    if isinstance(m.text, list):
        out = []
        for p in m.text:
            if   isinstance(p, Text):       out.append({"type": "input_text", "text": p.text or ""})
            elif isinstance(p, InputImage): out.append(denorm_image(p))
            elif isinstance(p, InputFile):  out.append(denorm_file(p))
            else: raise ValueError(f"OpenAI Responses tool_result does not support {p.type}")
        return dict(type='function_call_output', call_id=cid, output=out)
    return dict(type='function_call_output', call_id=cid, output=tool_text(m.text))

# %% ../nbs/02_oai_responses.ipynb #9b0f81a4
@delegates(payload_kwargs)
def mk_payload(msgs, model, **kwargs):
    payload = dict(model=model)
    if msgs: payload['input'] = denorm_msgs(msgs)
    if stream:=kwargs.get('stream'):        payload['stream'] = True
    if sp:=kwargs.get('system'):            payload['instructions'] = denorm_system(sp)
    if mt:=kwargs.get('max_tokens'):        payload['max_output_tokens'] = mt
    if tools:=kwargs.get('tools'):          payload['tools'] = denorm_tool_schs(tools)
    if tchc:=kwargs.get('tool_choice'):     payload['tool_choice'] = denorm_tool_choice(tchc)
    if rid:=kwargs.get('previous_response_id'): payload['previous_response_id'] = rid
    if (ptc:=kwargs.get('parallel_tool_calls')) is not None: payload['parallel_tool_calls'] = ptc
    if thk:=kwargs.get('reasoning_effort'): payload['reasoning'] = denorm_reasoning(thk)
    if (wopts:=kwargs.get('web_search_options')) is not None:  payload.setdefault('tools', []).append(denorm_web_search(wopts))
    if (temp:=kwargs.get('temperature')) is not None: payload['temperature'] = temp
    return payload

# %% ../nbs/02_oai_responses.ipynb #529fd4bc
def get_hdrs(api_key=None, oauth_token=None):
    "Bearer auth: an OAuth access token, or else an API key from the argument or the environment"
    return {"Authorization": f"Bearer {oauth_token or get_api_key(api_key, 'OPENAI_API_KEY')}"}


# %% ../nbs/02_oai_responses.ipynb #a907ffa8
def cost(usage, m):
    raw = usage.raw
    cached = raw.get('input_tokens_details', {}).get('cached_tokens', 0)
    tier = price_tier(m, raw['input_tokens'])
    cost  = (raw['input_tokens'] - cached) * tier_rate(m, 'input_cost_per_token', tier)
    cost += raw['output_tokens'] * tier_rate(m, 'output_cost_per_token', tier)
    cost += cached * tier_rate(m, 'cache_read_input_token_cost', tier)
    return cost

# %% ../nbs/02_oai_responses.ipynb #2efda2a1
def fix_payload(payload, model, vendor_name):
    "Apply vendor request quirks to a built payload."
    if vendor_name == 'codex':
        for k in 'temperature max_tokens max_output_tokens max_completion_tokens metadata'.split(): payload.pop(k, None)
        payload['store'] = False

# %% ../nbs/02_oai_responses.ipynb #07114b55
api_ns = dict(norm_tool_calls=norm_tool_calls, norm_parts=norm_parts, norm_finish=norm_finish, norm_usage=norm_usage,
    supports_previous_response_id=True, raw_msg=raw_msg, collate_raw=collate_raw, acollect_stream=acollect_stream, mk_payload=mk_payload,
    cost=cost, get_hdrs=get_hdrs, fix_payload=fix_payload,
    endpoint='/responses')
api_registry.register('openai', **api_ns)
