"""Provider-independent Responses resources and streaming over FastLLM

`response_input` converts a plain prompt or standard input-item array to canonical messages. System and developer messages become provider instructions; adjacent function outputs remain one tool message so a parallel batch reaches the next model turn together.

FastLLM completions become ordinary assistant-message and function-call items. Call ids are normalized before the canonical history is retained, so a later tool result always refers to the same id the client saw.

`ResponseState` is the complete provider-independent continuation value. A host may store it under any ownership and expiry policy. When a provider id exists, the next turn sends only new items; otherwise it replays canonical history.

Every request is streamed. `_ResponseStream` only tracks the standard event grammar for one inference; it contains no provider, persistence, or billing policy."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06a_responses.ipynb.

# %% auto #0
__all__ = ['ResponsesError', 'response_input', 'normalize_call_ids', 'response_output', 'response_usage', 'response_object',
           'ResponseState', 'ResponseTurn', 'AsyncResponses', 'response_event', 'pending_response']

# %% ../nbs/06a_responses.ipynb #e16fc24e
import asyncio, copy, json, secrets, time
from fastcore.utils import *
from fastcore.funccall import call_func_async, get_schema
from fasttransport.errors import APIError

from .acomplete import acomplete
from .streaming import Status
from aidialog.msg_parts import Msg, Text, ToolUse, ToolResult, InputImage, InputFile, Completion, tool_text

# %% ../nbs/06a_responses.ipynb #f904c16f
class ResponsesError(Exception):
    "A request error with Responses-compatible metadata."
    def __init__(self, message, status=400, code='invalid_request_error', param=None):
        super().__init__(message)
        store_attr()

# %% ../nbs/06a_responses.ipynb #381110be
def _msg_parts(content):
    if isinstance(content, str): return [Text(content)]
    parts = []
    for o in content:
        typ = o.get('type')
        if typ in ('input_text', 'output_text', 'text'): parts.append(Text(o.get('text', '')))
        elif typ == 'input_image': parts.append(InputImage(o.get('image_url')))
        elif typ == 'input_file': parts.append(InputFile(o.get('file_url') or o.get('file_data')))
        else: raise ResponsesError(f'Unsupported message content type: {typ}', param='input')
    return parts

# %% ../nbs/06a_responses.ipynb #21432ba9
def _text_content(content):
    if isinstance(content, str): return content
    return ''.join(o.get('text', '') for o in content if o.get('type') in ('input_text', 'output_text', 'text'))

def response_input(inp):
    "Convert Responses input items to canonical messages and instructions."
    if isinstance(inp, str): return [Msg('user', [Text(inp)])], ''
    if not isinstance(inp, list): raise ResponsesError('input must be a string or array', param='input')
    msgs,systems,pending_tools = [],[],[]
    def flush_tools():
        if pending_tools:
            msgs.append(Msg('tool', pending_tools.copy()))
            pending_tools.clear()
    for item in inp:
        typ = item.get('type')
        if typ in ('message', 'easy_input_message') or 'role' in item:
            flush_tools()
            role = item.get('role', 'user')
            if role in ('system', 'developer'): systems.append(_text_content(item.get('content', '')))
            else: msgs.append(Msg(role, _msg_parts(item.get('content', ''))))
        elif typ == 'function_call':
            flush_tools()
            args = item.get('arguments') or {}
            if isinstance(args, str):
                try: args = json.loads(args)
                except json.JSONDecodeError: pass
            call = ToolUse(id=item.get('call_id'), name=item.get('name'), arguments=args)
            if msgs and msgs[-1].role == 'assistant': msgs[-1].content.append(call)
            else: msgs.append(Msg('assistant', [call]))
        elif typ == 'function_call_output':
            out = item.get('output', '')
            pending_tools.append(ToolResult(id=item.get('call_id'), name=item.get('name', ''),
                text=out if isinstance(out, str) else _msg_parts(out)))
        else: raise ResponsesError(f'Unsupported input item type: {typ}', param='input')
    flush_tools()
    return msgs,'\n\n'.join(filter(None, systems))

# %% ../nbs/06a_responses.ipynb #7154feb3
def _new_id(prefix): return f'{prefix}_{secrets.token_hex(16)}'

def normalize_call_ids(comp):
    "Ensure every client tool call has a Responses call id."
    for tc in comp.tool_calls:
        if not tc.id: tc.id = _new_id('call')
    return comp

# %% ../nbs/06a_responses.ipynb #ab1a57d7
def _arguments(args): return args if isinstance(args, str) else json.dumps(args or {}, separators=(',', ':'))

def response_output(comp):
    "Convert a Completion to Responses output items."
    output,msg = [],None
    for part in comp.message.content:
        if isinstance(part, Text):
            if msg is None:
                content = dict(type='output_text', text=part.text or '', annotations=list(part.citations or []))
                msg = dict(id=getattr(part, '_response_item_id', None) or _new_id('msg'), type='message', status='completed',
                    role='assistant', content=[content])
                output.append(msg)
            else:
                msg['content'][0]['text'] += part.text or ''
                msg['content'][0]['annotations'].extend(part.citations or [])
        elif isinstance(part, ToolUse) and not part.server:
            output.append(dict(id=getattr(part, '_response_item_id', None) or _new_id('fc'), type='function_call', status='completed',
                call_id=part.id, name=part.name, arguments=_arguments(part.arguments)))
    return output

# %% ../nbs/06a_responses.ipynb #7da06143
def response_usage(usage):
    "Convert normalized usage to Responses usage fields."
    if usage is None: return None
    result = dict(input_tokens=usage.prompt_tokens, output_tokens=usage.completion_tokens, total_tokens=usage.total_tokens)
    result['input_tokens_details'] = {'cached_tokens':usage.cached_tokens, 'cache_write_tokens':usage.cache_creation_tokens}
    result['output_tokens_details'] = {'reasoning_tokens':usage.reasoning_tokens}
    return result

# %% ../nbs/06a_responses.ipynb #71bc0e94
def _response_base(rid, body, previous_response_id=None, created_at=None):
    result = dict(id=rid, object='response', created_at=int(created_at or time.time()), instructions=body.get('instructions'), model=body['model'])
    result.update(parallel_tool_calls=body.get('parallel_tool_calls', True), previous_response_id=previous_response_id,
        reasoning=body.get('reasoning'), store=True, temperature=body.get('temperature'))
    result.update(text=body.get('text', {'format':{'type':'text'}}), tool_choice=body.get('tool_choice', 'auto'),
        tools=body.get('tools', []), top_p=body.get('top_p'), metadata=body.get('metadata', {}))
    return result

# %% ../nbs/06a_responses.ipynb #688ebc7c
def response_object(rid, body, comp, previous_response_id=None, created_at=None):
    "Build a completed Responses resource from a Completion."
    incomplete = comp.finish_reason == 'length'
    output = response_output(comp)
    result = _response_base(rid, body, previous_response_id, created_at)
    result.update(completed_at=int(time.time()), status='incomplete' if incomplete else 'completed', error=None,
        incomplete_details={'reason':'max_output_tokens'} if incomplete else None, output=output, usage=response_usage(comp.usage))
    result['output_text'] = ''.join(c['text'] for o in output if o['type']=='message' for c in o['content'] if c['type']=='output_text')
    return result

# %% ../nbs/06a_responses.ipynb #73a2fc16
class ResponseState(BasicRepr):
    "Canonical history and optional provider continuation metadata."
    def __init__(self, id, model, history, provider_response_id=None): store_attr()

# %% ../nbs/06a_responses.ipynb #c9ca3744
class ResponseTurn(BasicRepr):
    "A prepared Responses request for one provider call."
    def __init__(self, id, created_at, body, history, provider_messages, system='', previous=None, server_tools=None, call_kwargs=None):
        store_attr()
        if server_tools is None: self.server_tools = {}
        if call_kwargs is None: self.call_kwargs = {}

    @property
    def provider_previous_id(self): return self.previous.provider_response_id if self.previous else None


# %% ../nbs/06a_responses.ipynb #a648297f
class AsyncResponses:
    "Run individual Responses turns over FastLLM."
    def __init__(self): self.tasks = set()   # served turns still running
    def prepare(self, body, previous=None, server_tools=None, **kwargs):
        if not isinstance(body, dict): raise ResponsesError('Request body must be an object')
        model = body.get('model')
        if not model: raise ResponsesError('model is required', param='model')
        if 'input' not in body: raise ResponsesError('input is required', param='input')
        if previous and previous.model != model: raise ResponsesError('model must match the previous response', param='model')
        new_msgs,input_system = response_input(body['input'])
        history = (*previous.history, *new_msgs) if previous else tuple(new_msgs)
        names = {p.id: p.name for m in history for p in m.content if isinstance(p, ToolUse)}
        for m in new_msgs:
            for p in m.content:
                if isinstance(p, ToolResult) and not p.name: p.name = names.get(p.id, '')
        instructions = '\n\n'.join(filter(None, [body.get('instructions', ''), input_system]))
        provider_messages = new_msgs if previous and previous.provider_response_id else list(history)
        return ResponseTurn(_new_id('resp'), int(time.time()), body, history, provider_messages, instructions, previous,
            {f.__name__: f for f in server_tools or []}, kwargs)


# %% ../nbs/06a_responses.ipynb #373f7d5e
@patch
async def call(self:AsyncResponses, turn):
    "Start the provider stream for a prepared turn, having received its first chunk; the turn's `call_kwargs` reach `acomplete`"
    body = turn.body
    reasoning = body.get('reasoning') or {}
    tools = list(body.get('tools') or []) + [dict(type='function', **get_schema(f, pname='parameters')) for f in turn.server_tools.values()]
    kwargs = dict(previous_response_id=turn.provider_previous_id, system=turn.system or None, tools=tools or None)
    kwargs.update(tool_choice=body.get('tool_choice'), parallel_tool_calls=body.get('parallel_tool_calls', True),
        reasoning_effort=reasoning.get('effort'), max_tokens=body.get('max_output_tokens'), temperature=body.get('temperature'),
        cache_idxs=body.get('cache_idxs'), ttl=body.get('ttl'), web_search_options=body.get('web_search_options'))
    stream = await acomplete(turn.provider_messages, model=body['model'], stream=True, **kwargs, **turn.call_kwargs)
    first = await anext(stream)
    async def _rest():
        yield first
        async for o in stream: yield o
    return _rest()


# %% ../nbs/06a_responses.ipynb #4f424285
@patch
def state(self:AsyncResponses, turn, comp, results=()):
    "Build the next continuation state; `results` are server tool results answering `comp`'s calls."
    normalize_call_ids(comp)
    history = (*turn.history, comp.message, *([Msg('tool', list(results))] if results else []))
    return ResponseState(turn.id, turn.body['model'], history, comp.response_id)


# %% ../nbs/06a_responses.ipynb #7615b274
@patch
async def server_results(self:AsyncResponses, turn, comp):
    "Run the server tool calls in `comp`, returning their results"
    normalize_call_ids(comp)
    res = []
    for tc in comp.tool_calls:
        if tc.name not in turn.server_tools: continue
        out = await call_func_async(tc.name, tc.arguments, ns=turn.server_tools, raise_on_err=False)
        res.append(ToolResult(id=tc.id, name=tc.name, arguments=tc.arguments, text=tool_text(out)))
    return res

@patch
def server_turn(self:AsyncResponses, turn, comp, results):
    "The follow-up provider turn answering server tool `results`, within the same public response"
    outputs = [dict(type='function_call_output', call_id=r.id, output=r.text) for r in results]
    nxt = self.prepare(turn.body | dict(input=outputs), self.state(turn, comp), turn.server_tools.values(), **turn.call_kwargs)
    nxt.id = turn.id
    return nxt

# %% ../nbs/06a_responses.ipynb #25502099
def response_event(event_type, sequence_number, **kwargs):
    "Encode one Responses SSE frame."
    data = {'type':event_type, **kwargs, 'sequence_number':sequence_number}
    return f"event: {event_type}\ndata: {json.dumps(data, separators=(',', ':'))}\n\n"

# %% ../nbs/06a_responses.ipynb #d62864b4
def pending_response(turn):
    "Build the initial in-progress Responses resource."
    previous_id = turn.previous.id if turn.previous else None
    result = _response_base(turn.id, turn.body, previous_id, turn.created_at)
    result.update(status='in_progress', error=None, incomplete_details=None, output=[], usage=None)
    return result

# %% ../nbs/06a_responses.ipynb #096b3121
class _ResponseStream(BasicRepr):
    def __init__(self, turn):
        self.turn,self.seq,self.next_index = turn,0,0
        self.message_id,self.message_index,self.text = None,None,''
        self.tool_item_ids,self.streamed_call_ids = {},[]

    def event(self, event_type, **kwargs):
        result = response_event(event_type, self.seq, **kwargs)
        self.seq += 1
        return result

# %% ../nbs/06a_responses.ipynb #394b3c6f
@patch
def text_events(self:_ResponseStream, part):
    events = []
    if self.message_id is None:
        self.message_id,self.message_index = _new_id('msg'),self.next_index
        self.next_index += 1
        item = dict(id=self.message_id, type='message', status='in_progress', role='assistant', content=[])
        events.append(self.event('response.output_item.added', output_index=self.message_index, item=item))
        content = dict(type='output_text', text='', annotations=[])
        events.append(self.event('response.content_part.added', item_id=self.message_id,
            output_index=self.message_index, content_index=0, part=content))
    self.text += part.text or ''
    if part.text:
        events.append(self.event('response.output_text.delta', item_id=self.message_id,
            output_index=self.message_index, content_index=0, delta=part.text))
    return events

# %% ../nbs/06a_responses.ipynb #d1679663
@patch
def tool_events(self:_ResponseStream, part):
    if not part.id: part.id = _new_id('call')
    self.streamed_call_ids.append(part.id)
    item_id,index,args = _new_id('fc'),self.next_index,_arguments(part.arguments)
    self.next_index += 1
    self.tool_item_ids[part.id] = item_id
    item = dict(id=item_id, type='function_call', status='in_progress', call_id=part.id, name=part.name, arguments='')
    events = [self.event('response.output_item.added', output_index=index, item=item)]
    events.append(self.event('response.function_call_arguments.delta', item_id=item_id, output_index=index, delta=args))
    events.append(self.event('response.function_call_arguments.done', item_id=item_id, output_index=index,
        name=part.name, arguments=args))
    item['status'],item['arguments'] = 'completed',args
    events.append(self.event('response.output_item.done', output_index=index, item=item))
    return events

# %% ../nbs/06a_responses.ipynb #7086fbeb
@patch
def part_events(self:_ResponseStream, part):
    if isinstance(part, Text): return self.text_events(part)
    if isinstance(part, ToolUse) and not part.server: return self.tool_events(part)
    return []

# %% ../nbs/06a_responses.ipynb #c96550ce
@patch
def done_events(self:_ResponseStream, comp):
    events = []
    if self.message_id is not None:
        content = dict(type='output_text', text=self.text, annotations=[])
        item = dict(id=self.message_id, type='message', status='completed', role='assistant', content=[content])
        events.append(self.event('response.output_text.done', item_id=self.message_id, output_index=self.message_index,
            content_index=0, text=self.text))
        events.append(self.event('response.content_part.done', item_id=self.message_id, output_index=self.message_index,
            content_index=0, part=content))
        events.append(self.event('response.output_item.done', output_index=self.message_index, item=item))
    for i,tc in enumerate(comp.tool_calls):
        if not tc.id and i < len(self.streamed_call_ids): tc.id = self.streamed_call_ids[i]
        tc._response_item_id = self.tool_item_ids.get(tc.id)
    for part in comp.message.content:
        if isinstance(part, Text): part._response_item_id = self.message_id
    return events

# %% ../nbs/06a_responses.ipynb #e10c928b
@patch
async def events(self:AsyncResponses, turn, finalize=None, stream=None):
    state,first = _ResponseStream(turn),turn
    yield state.event('response.created', response=pending_response(turn))
    try:
        texts,usage = [],None
        while True:
            async for part in (stream or await self.call(turn)):
                if isinstance(part, Completion): comp = part
                elif isinstance(part, Status) or (isinstance(part, ToolUse) and part.name in turn.server_tools): continue
                else:
                    for event in state.part_events(part): yield event
            usage,stream = (comp.usage if usage is None else usage + comp.usage),None
            results = await self.server_results(turn, comp)
            if not results or len(results) < len(comp.tool_calls): break
            texts += [p for p in comp.message.content if isinstance(p, Text)]
            turn = self.server_turn(turn, comp, results)
        next_state = self.state(turn, comp, results)
        comp = copy.copy(comp)
        comp.message,comp.usage = Msg('assistant', texts + comp.message.content),usage
        for event in state.done_events(comp): yield event
        response = response_object(first.id, first.body, comp, first.previous.id if first.previous else None, first.created_at)
        if finalize: await finalize(next_state, comp)
        name = 'response.incomplete' if response['status'] == 'incomplete' else 'response.completed'
        yield state.event(name, response=response)
    except asyncio.CancelledError: raise
    except ResponsesError as exc: yield state.event('error', code=exc.code, message=str(exc), param=exc.param)
    except APIError as exc: yield state.event('error', code=exc.code or 'provider_error', message=str(exc), param=None)


# %% ../nbs/06a_responses.ipynb #cc32ce40
@patch
def serve(self:AsyncResponses, turn, finalize=None, stream=None, timeout=None):
    "The frames of `events`, from a task that outlives its reader, so a disconnected client still gets its turn finalized"
    q = asyncio.Queue()
    async def _run():
        try:
            async with asyncio.timeout(timeout):
                async for frame in self.events(turn, finalize=finalize, stream=stream): q.put_nowait(frame)
        except TimeoutError: q.put_nowait(response_event('error', 0, code='timeout', message=f'turn exceeded {timeout}s', param=None))
        finally: q.put_nowait(None)
    t = asyncio.create_task(_run())
    self.tasks.add(t)
    t.add_done_callback(self.tasks.discard)
    async def _frames():
        while (frame := await q.get()) is not None: yield frame
    return _frames()
