"""Streaming helpers for lossless event collation."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_streaming.ipynb.

# %% auto #0
__all__ = ['Delta', 'norm_and_yield', 'PartAccum', 'stop_and_trim', 'mk_acollect_stream']

# %% ../nbs/01_streaming.ipynb #0df5c926
import json,copy
from dataclasses import dataclass, field, fields
from fastcore.utils import *
from fastcore.meta import delegates
from fastspec.errors import *
from .types import *

# %% ../nbs/01_streaming.ipynb #400d628a
@dataclass
class Delta:
    "Normalized streaming delta event."
    text: str = ""
    thinking: str = ""
    refusal: str = ""
    tool_calls: list[ToolCall] = field(default_factory=list)
    citations: list = field(default_factory=list)
    server_tool_result: dict = None
    finish_reason: str = None
    usage: Usage = None
    raw: dict = field(default_factory=dict)

# %% ../nbs/01_streaming.ipynb #f59f837b
async def norm_and_yield(resp, norm_func):
    async for ev in resp:
        if (d := norm_func(ev)) is not None: yield d

# %% ../nbs/01_streaming.ipynb #a7f1738a
@dataclass
class PartAccum:
    parts: dict[Part|ToolCall] = field(default_factory=dict)
    tool_calls: list[ToolCall] = field(default_factory=list)
    
    def append(self, typ, index, txt='', citations=None, **tc_kwargs):
        'Create and accumulate same type sequential parts'
        if index not in self.parts: 
            if typ==PartType.tool_use: self.parts[index] = ToolCall(**tc_kwargs)
            else:                      self.parts[index] = Part(type=typ, text=txt, data=dict(citations=citations or []))
        else:
            if typ==PartType.tool_use:
                new_args = tc_kwargs.get('arguments', '')
                cur_args = self.parts[index].arguments
                if isinstance(new_args, str) and isinstance(cur_args, str): self.parts[index].arguments += new_args
                elif isinstance(new_args, str) and isinstance(cur_args, dict): self.parts[index].arguments = new_args
                else: self.parts[index].arguments = new_args
            else: 
                self.parts[index].text += txt
                # anthropic citations have matching idx
                self.parts[index].data['citations'].extend(citations or [])
    
    def get_merged(self, with_tools=True):
        tmp_parts = copy.deepcopy(self.parts)
        tool_calls = []
        if with_tools:
            for idx,tc in tmp_parts.items():
                if isinstance(tc, ToolCall):
                    if isinstance(tc.arguments, str): tc.arguments = json.loads(tc.arguments) if tc.arguments else {}
                    tool_calls.append(tc)
                    data = {**tc.extra, 'id':tc.id, 'name':tc.name, 'arguments':tc.arguments, 'server':tc.server}
                    tmp_parts[idx] = Part(type=PartType.tool_use, data=data)
        
        merged = []
        for p in tmp_parts.values():
            if isinstance(p, ToolCall) and not with_tools: continue
            if merged and merged[-1].type == p.type and p.type in (PartType.text, PartType.thinking): merged[-1].text += p.text
            else: merged.append(p)
        return merged, tool_calls
    
    def finalize(self):
        self.parts, self.tool_calls = self.get_merged()

# %% ../nbs/01_streaming.ipynb #f11ea80a
def _trim_delta(d, txt, s):
    "Trim `d.text` so accumulated text in `cur` stops just before stop sequence `s`."
    idx = len(txt) - (txt.find(s) + len(s))
    if idx>0: d.text = d.text[:-idx]

# %% ../nbs/01_streaming.ipynb #efbf96d7
def stop_and_trim(part_accum, d, stop_callables):
    'Stop based on the accumulated text so far, and trim current delta'
    parts,_ = part_accum.get_merged(with_tools=False)
    prev = parts[-1].text if parts and parts[-1].type == PartType.text else ''
    txt = prev + (d.text or '')
    for f in stop_callables:
        if res:=f(txt):
            if isinstance(res, str): _trim_delta(d, txt, res)
            return True
    return False

# %% ../nbs/01_streaming.ipynb #fc71790b
async def mk_acollect_stream(it, index_fn, model=None, api_name=None, vendor_name=None, stop_callables=None):
    "Collect a Delta stream, yielding incremental chunks and a final Completion."
    part_accum,deltas,stop_callables = PartAccum(), [], L(stop_callables)
    fin, usg, typ, last_typ, last_idx = [None]*5
    def _fidx(d, name, pt=None):
        nonlocal typ, last_idx
        typ = getattr(PartType, pt or name)
        idx,last_idx = index_fn(d, typ, last_typ, last_idx)
        return idx
    def _proc(d, name, pt=None, kw='txt', ret=None):
        if not ret and not (val := getattr(d, name)): return None, None
        idx = _fidx(d, name, pt)
        part_accum.append(typ, idx, **(ret or {kw: val}))
        return ret or {name: val}, idx
    def _yield_parts(d):
        for args in [('text',), ('thinking',), ('citations', 'text', 'citations')]:
            r = _proc(d, args[0], pt=args[1] if len(args)>1 else None, kw=args[2] if len(args)>2 else 'txt')
            if r[0]: yield r[0]
    stop, stop_yielded = False, False
    async for d in it:
        # Check stop condition and yield stop delta
        if not stop: stop = stop_and_trim(part_accum, d, stop_callables)
        if stop and not stop_yielded:
            for r in _yield_parts(d): yield r
            stop_yielded = True
        # If stop the remaining deltas are yielded as processing
        if stop: yield {'thinking':'processing'}
        else:
            for r in _yield_parts(d): yield r
        # Rest incl. tools, finish reason, usage is processed independently
        for tc in d.tool_calls:
            args = tc.arguments.get('_delta', tc.arguments)
            _, idx = _proc(d, 'tool_use', ret=dict(id=tc.id, name=tc.name, arguments=args, server=tc.server, extra=tc.extra))
            if (isinstance(args, str) and args.endswith('}')) or (isinstance(args, dict) and '_delta' not in tc.arguments): # tool call ready
                if isinstance(args, str):
                    try: args = json.loads(part_accum.parts[idx].arguments) if args else {}
                    except json.JSONDecodeError: continue
                acc = part_accum.parts[idx]
                acc.arguments = args
                data = {**acc.extra, 'id':acc.id, 'name':acc.name, 'arguments':args, 'server':acc.server}
                yield Part(type=PartType.tool_use, data=data)
                # Server tool results for anthropic are yielded in d.server_tool_result by checking injected dummy `_delta`
                if acc.server: yield Part(type=PartType.tool_result, text="Server tool call executed.", data=data)
        if d.server_tool_result:
            idx = _fidx(d, 'server_tool_result')
            part_accum.parts[idx] = Part(type=typ, data=d.server_tool_result)
        r = _proc(d, 'refusal')
        if r[0]: yield r[0]
        if d.finish_reason: fin = d.finish_reason
        if d.usage: usg = d.usage
        last_typ = typ
        deltas.append(d)
    part_accum.finalize()
    tcs = part_accum.tool_calls
    if api_name: usg = api_registry.apis[api_name].finalize_usage(usg, part_accum.parts)
    if stop: fin = FinishReason.stop
    fin = FinishReason.tool_calls if fin==FinishReason.stop and any(~L(tcs).attrgot('server')) else fin # recheck tool calls post collation
    # tool calls and non-anthropic citations are yielded at the end
    yield Completion(model,
            message=Msg(role="assistant", content=part_accum.parts),
            finish_reason=fin, usage=usg, tool_calls=tcs, api_name=api_name, vendor_name=vendor_name,
            raw={'deltas':deltas})
