"""Streaming helpers for lossless event collation."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_streaming.ipynb.

# %% auto #0
__all__ = ['Delta', 'norm_and_yield', 'PartAccum', 'accum_completion', 'completion_text', 'stop_sequences', 'mk_acollect_stream',
           'fake_stream']

# %% ../nbs/01_streaming.ipynb #0df5c926
import json
from dataclasses import dataclass, field, fields
from fastcore.utils import *
from fastcore.meta import delegates
from fastspec.errors import *
from .types import *

# %% ../nbs/01_streaming.ipynb #400d628a
@dataclass
class Delta:
    "Normalized streaming delta event."
    text: str = ""
    thinking: str = ""
    refusal: str = ""
    tool_calls: list[ToolCall] = field(default_factory=list)
    citations: list = field(default_factory=list)
    server_tool_result: dict = None
    finish_reason: str = None
    usage: Usage = None
    raw: dict = field(default_factory=dict)

# %% ../nbs/01_streaming.ipynb #f59f837b
async def norm_and_yield(resp, norm_func):
    async for ev in resp:
        if (d := norm_func(ev)) is not None: yield d

# %% ../nbs/01_streaming.ipynb #a7f1738a
@dataclass
class PartAccum:
    parts: dict[Part|ToolCall] = field(default_factory=dict)
    tool_calls: list[ToolCall] = field(default_factory=list)
    
    def append(self, typ, index, txt='', citations=None, **tc_kwargs):
        'Create and accumulate same type sequential parts'
        if index not in self.parts: 
            if typ==PartType.tool_use: self.parts[index] = ToolCall(**tc_kwargs)
            else:                      self.parts[index] = Part(type=typ, text=txt, data=dict(citations=citations or []))
        else:
            if typ==PartType.tool_use:
                new_args = tc_kwargs.get('arguments', '')
                cur_args = self.parts[index].arguments
                if isinstance(new_args, str) and isinstance(cur_args, str): self.parts[index].arguments += new_args
                elif isinstance(new_args, str) and isinstance(cur_args, dict): self.parts[index].arguments = new_args
                else: self.parts[index].arguments = new_args
            else: 
                self.parts[index].text += txt
                # anthropic citations have matching idx
                self.parts[index].data['citations'].extend(citations or [])
    
    def finalize(self):
        for idx,tc in self.parts.items():
            if isinstance(tc, ToolCall):
                if isinstance(tc.arguments, str): tc.arguments = json.loads(tc.arguments) if tc.arguments else {}
                self.tool_calls.append(tc)
                data = {**tc.extra, 'id':tc.id, 'name':tc.name, 'arguments':tc.arguments, 'server':tc.server}
                self.parts[idx] = Part(type=PartType.tool_use, data=data)
        
        merged = []
        for p in self.parts.values():
            if merged and merged[-1].type == p.type and p.type in (PartType.text, PartType.thinking): merged[-1].text += p.text
            else: merged.append(p)        
        self.parts = merged

# %% ../nbs/01_streaming.ipynb #0e8ca58e
def accum_completion(pa, raw, fin, usg, deltas, model=None, api_name=None, vendor_name=None, delta=None):
    "Build a Completion snapshot from in-progress PartAccum state"
    parts = [p for p in pa.parts.values() if isinstance(p, Part)]
    if delta and delta.text:
        parts = parts.copy()
        if parts and parts[-1].type==PartType.text:
            p = parts[-1]
            parts[-1] = Part(type=p.type, text=(p.text or '') + delta.text, data=p.data)
        else: parts.append(Part(type=PartType.text, text=delta.text))
    return Completion(raw.get('model', model), Msg(role="assistant", content=parts),
                      fin, usg, api_name=api_name, vendor_name=vendor_name, raw={'deltas':deltas})

# %% ../nbs/01_streaming.ipynb #c28f706f
def completion_text(c):
    "Combined text from a Completion."
    return ''.join(p.text or '' for p in c.message.content if p.type==PartType.text)

# %% ../nbs/01_streaming.ipynb #b2b9f7ca
def stop_sequences(seqs):
    "Stop when any sequence appears in the accumulated completion text."
    seqs = L(seqs)
    def _stop(c):
        txt = completion_text(c)
        for s in seqs:
            if s in txt: return s
    return _stop

# %% ../nbs/01_streaming.ipynb #931f686b
def _trim_delta(d, cur, s):
    "Trim `d.text` so accumulated text in `cur` stops just before stop sequence `s`."
    txt,dt = completion_text(cur), d.text or ''
    i = txt.find(s)
    if i>=0: d.text = dt[:max(0, i-(len(txt)-len(dt)))]

# %% ../nbs/01_streaming.ipynb #fc71790b
async def mk_acollect_stream(it, index_fn, model=None, api_name=None, vendor_name=None, stop_callables=None):
    "Collect a Delta stream, yielding incremental chunks and a final Completion."
    part_accum,deltas,stop_callables = PartAccum(), [], L(stop_callables)
    fin, usg, typ, last_typ, last_idx = [None]*5
    def _fidx(d, name, pt=None):
        nonlocal typ, last_idx
        typ = getattr(PartType, pt or name)
        idx,last_idx = index_fn(d, typ, last_typ, last_idx)
        return idx
    def _proc(d, name, pt=None, kw='txt', ret=None):
        if not ret and not (val := getattr(d, name)): return
        idx = _fidx(d, name, pt)
        part_accum.append(typ, idx, **(ret or {kw: val}))
        return ret or {name: val}
    async for d in it:
        stop = False
        if stop_callables:
            cur = accum_completion(part_accum, d.raw, fin, usg, deltas+[d], model, api_name=api_name, vendor_name=vendor_name, delta=d)
            for f in stop_callables:
                if res:=f(cur):
                    if isinstance(res, str): _trim_delta(d, cur, res)
                    stop = True
                    break
        if (r:=_proc(d, 'text')): yield r
        if (r:=_proc(d, 'thinking')): yield r
        if (r:=_proc(d, 'citations', pt='text', kw='citations')): yield r
        for tc in d.tool_calls:
            args = tc.arguments.get('_delta', tc.arguments)
            _proc(d, 'tool_use', ret=dict(id=tc.id, name=tc.name, arguments=args, server=tc.server, extra=tc.extra))
        if d.server_tool_result:
            idx = _fidx(d, 'server_tool_result')
            part_accum.parts[idx] = Part(type=typ, data=d.server_tool_result)
        if (r:=_proc(d, 'refusal')): yield r
        if d.finish_reason: fin = d.finish_reason
        if d.usage: usg = d.usage
        last_typ = typ
        deltas.append(d)
        if stop:
            fin = fin or FinishReason.stop
            await it.aclose()
            break
    part_accum.finalize()
    # need to recheck for tool calls post collation for streaming
    tcs = part_accum.tool_calls
    fin = FinishReason.tool_calls if fin==FinishReason.stop and any(~L(tcs).attrgot('server')) else fin
    # tool calls and non-anthropic citations are yielded at the end
    yield Completion(d.raw.get('model', model),
            message=Msg(role="assistant", content=part_accum.parts),
            finish_reason=fin, usage=usg, tool_calls=tcs, api_name=api_name, vendor_name=vendor_name,
            raw={'deltas':deltas})

# %% ../nbs/01_streaming.ipynb #f79d3b99
async def fake_stream(*ss):
    for s in ss: yield Delta(text=s, raw={'model':'fake'})
