"""Streaming helpers for lossless event collation."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_streaming.ipynb.

# %% auto #0
__all__ = ['Delta', 'norm_and_yield', 'PrintStream', 'PartAccum', 'FenceToolStop', 'stop_and_trim', 'stop_sequences', 'Status',
           'mk_acollect_stream']

# %% ../nbs/01_streaming.ipynb #0df5c926
import json,copy
from fastcore.utils import *
from fastcore.meta import delegates
from fastspec.errors import *
from .types import *
from aidialog.msg_parts import Part, PartType, Msg, Text, Thinking, ToolUse, ToolResult, ServerToolResult, mk_part, fence_call_re, Completion

# %% ../nbs/01_streaming.ipynb #400d628a
class Delta(BasicRepr):
    "Normalized streaming delta event."
    def __init__(self, text='', thinking='', refusal='', tool_calls=None, citations=None,
        server_tool_result=None, finish_reason=None, usage=None, raw=None):
        store_attr()
        self.tool_calls,self.citations,self.raw = ifnone(tool_calls,[]),ifnone(citations,[]),ifnone(raw,{})
    def __eq__(self, o): return type(o) is type(self) and self.__dict__ == o.__dict__
    def __hash__(self): return hash((self.text, self.thinking, self.finish_reason))

# %% ../nbs/01_streaming.ipynb #f59f837b
async def norm_and_yield(resp, norm_func):
    async for ev in resp:
        if (d := norm_func(ev)) is not None: yield d

# %% ../nbs/01_streaming.ipynb #0c3fb4fd
class PrintStream:
    "Print a typed stream's `formatted` items; 🧠 glyphs capped at `max_think` per round"
    def __init__(self, max_think=10): self.max_think,self.cnt = max_think,0
    def __call__(self, o):
        if isinstance(o, Completion): self.cnt = 0; return
        f = getattr(o, 'formatted', '')
        if f=='🧠':
            self.cnt += 1
            if self.cnt > self.max_think: return
        if f: print(f, end='', flush=True)

# %% ../nbs/01_streaming.ipynb #a7f1738a
class PartAccum(BasicRepr):
    "Accumulate streamed part deltas by index"
    def __init__(self, parts=None):
        store_attr()
        self.parts = ifnone(parts, {})
    def __eq__(self, o): return type(o) is type(self) and self.__dict__ == o.__dict__
    def __hash__(self): return hash(len(self.parts))

    def append(self, typ, index, txt='', citations=None, **tc_kwargs):
        'Create and accumulate same type sequential parts'
        p = self.parts.get(index)
        if p is None:
            if typ==PartType.tool_use: p = ToolUse(**tc_kwargs)
            elif typ==PartType.text:   p = Text(txt, citations=list(citations or []))
            else:                      p = mk_part(typ, text=txt)
            self.parts[index] = p
        elif isinstance(p, ToolUse):
            new_args = tc_kwargs.get('arguments', '')
            if isinstance(new_args, str) and isinstance(p.arguments, str): p.arguments += new_args
            else: p.arguments = new_args
        else:
            p.text += txt
            if isinstance(p, Text): p.citations.extend(citations or [])  # anthropic citations have matching idx

    def get_merged(self, with_tools=True):
        "A copy of the accumulated parts, runs of text/thinking merged and tool arguments parsed"
        merged = []
        for p in copy.deepcopy(list(self.parts.values())):
            if isinstance(p, ToolUse):
                if not with_tools: continue
                if isinstance(p.arguments, str): p.arguments = json.loads(p.arguments) if p.arguments else {}
            elif merged and type(merged[-1]) is type(p) and isinstance(p, (Text, Thinking)):
                merged[-1].text += p.text
                continue
            merged.append(p)
        return merged

# %% ../nbs/01_streaming.ipynb #c64e2379
class FenceToolStop:
    def __init__(self, langs): self.langs = langs
    def __call__(self, text):
        "Return trim result if complete fence detected in active lang"
        m = fence_call_re.search(text)
        if m and m.group(1) in self.langs: return m.group(0)

# %% ../nbs/01_streaming.ipynb #f11ea80a
def _trim_delta(d, txt, s):
    "Trim `d.text` so accumulated text in `cur` stops just before stop sequence `s`."
    idx = len(txt) - (txt.find(s) + len(s))
    if idx>0: d.text = d.text[:-idx]

# %% ../nbs/01_streaming.ipynb #efbf96d7
def stop_and_trim(part_accum, d, stop_callables):
    'Stop based on the accumulated text so far, and trim current delta'
    parts = part_accum.get_merged(with_tools=False)
    prev = parts[-1].text if parts and isinstance(parts[-1], Text) else ''
    txt = prev + (d.text or '')
    for f in stop_callables:
        if res:=f(txt):
            if isinstance(res, str): _trim_delta(d, txt, res)
            return True
    return False

# %% ../nbs/01_streaming.ipynb #9de6ac91
def stop_sequences(seqs):
    "Stop when any sequence appears in the accumulated completion text."
    seqs = L(seqs)
    def _stop(text):
        for s in seqs:
            if s in text: return text[:text.find(s)+len(s)]
    return _stop

# %% ../nbs/01_streaming.ipynb #90f91955
class Status(BasicRepr):
    "Stream marker for activity that isn't model content (e.g. draining deltas after a stop sequence)"
    type = 'status'
    def __init__(self, status): store_attr()
    def __eq__(self, o): return type(o) is type(self) and self.__dict__ == o.__dict__
    def __hash__(self): return hash(self.status)
    @property
    def formatted(self): return '🧠'

def _mk_delta_part(name, val):
    "Wrap one collected delta field as a `Part`"
    if name=='citations': return Text('', citations=val)
    return mk_part(getattr(PartType, name), text=val)

# %% ../nbs/01_streaming.ipynb #fc71790b
async def mk_acollect_stream(it, index_fn, model=None, api_name=None, vendor_name=None, stop_callables=None):
    "Collect a Delta stream, yielding incremental `Part`s and a final Completion."
    part_accum,deltas,stop_callables = PartAccum(), [], L(stop_callables)
    fin, usg, typ, last_typ, last_idx = [None]*5
    def _fidx(d, name, pt=None):
        nonlocal typ, last_idx
        typ = getattr(PartType, pt or name)
        idx,last_idx = index_fn(d, typ, last_typ, last_idx)
        return idx
    def _proc(d, name, pt=None, kw='txt', ret=None):
        if not ret and not (val := getattr(d, name)): return None, None
        idx = _fidx(d, name, pt)
        part_accum.append(typ, idx, **(ret or {kw: val}))
        return ret or {name: val}, idx
    def _yield_parts(d):
        for name,pt,kw in [('text',None,'txt'), ('thinking',None,'txt'), ('citations','text','citations')]:
            r,_ = _proc(d, name, pt=pt, kw=kw)
            if r: yield _mk_delta_part(name, r[name])
    stop, stop_yielded = False, False
    async for d in it:
        # Check stop condition and yield stop delta
        if not stop: stop = stop_and_trim(part_accum, d, stop_callables)
        if stop and not stop_yielded:
            for r in _yield_parts(d): yield r
            stop_yielded = True
        # If stop the remaining deltas are yielded as processing
        if stop: yield Status('processing')
        else:
            for r in _yield_parts(d): yield r
        # Rest incl. tools, finish reason, usage is processed independently
        for tc in d.tool_calls:
            args = tc.arguments.get('_delta', tc.arguments)
            _, idx = _proc(d, 'tool_use', ret=dict(id=tc.id, name=tc.name, arguments=args, server=tc.server, raw=tc.raw))
            if (isinstance(args, str) and args.endswith('}')) or (isinstance(args, dict) and '_delta' not in tc.arguments): # tool call ready
                acc = part_accum.parts[idx]
                if isinstance(args, str):
                    try: args = json.loads(acc.arguments) if args else {}
                    except json.JSONDecodeError: continue
                acc.arguments = args
                yield acc
                # Server tool results for anthropic are yielded in d.server_tool_result by checking injected dummy `_delta`
                if acc.server: yield ToolResult(id=acc.id, name=acc.name, arguments=args, server=True, text="Server tool call executed.")
        if d.server_tool_result:
            idx = _fidx(d, 'server_tool_result')
            part_accum.parts[idx] = ServerToolResult(raw=d.server_tool_result)
        r = _proc(d, 'refusal')
        if r[0]: yield _mk_delta_part('refusal', r[0]['refusal'])
        if d.finish_reason: fin = d.finish_reason
        if d.usage: usg = d.usage
        last_typ = typ
        deltas.append(d)
    parts = part_accum.get_merged()
    tcs = [p for p in parts if isinstance(p, ToolUse)]
    if api_name: usg = api_registry[api_name].finalize_usage(usg, parts)
    if stop: fin = FinishReason.stop
    fin = FinishReason.tool_calls if fin==FinishReason.stop and any(~L(tcs).attrgot('server')) else fin # recheck tool calls post collation
    # tool calls and non-anthropic citations are yielded at the end
    yield Completion(model,
            message=Msg(role="assistant", content=parts),
            finish_reason=fin, usage=usg, api_name=api_name, vendor_name=vendor_name,
            raw={'deltas':deltas})
