"""Core internal types."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_types.ipynb.

# %% auto #0
__all__ = ['PartType', 'FinishReason', 'api_registry', 'model_prices_url', 'haik45', 'sonn45', 'sonn', 'sonn46', 'opus46', 'opus',
           'gpt54', 'gpt54m', 'gpt55', 'codex54', 'codex54m', 'codex55', 'codex53spark', 'model_info_registry',
           'deepseek_v4_common', 'codex_pricing', 'Part', 'Msg', 'ToolCall', 'display_list', 'Usage', 'Completion',
           'APIRegistry', 'mk_completion', 'mk_tool_res_msg', 'fn_schema', 'sys_text', 'part_txt', 'data_url',
           'url_mime', 'payload_kwargs', 'get_api_key', 'model_prices_meta', 'infer_api_name', 'get_model_meta',
           'register_model_info', 'get_model_info', 'get_model_pricing', 'approx_pricing']

# %% ../nbs/00_types.ipynb #b4d047fd
import httpx
from dataclasses import dataclass, field
from fastcore.net import urljson
from fastcore.utils import *

# %% ../nbs/00_types.ipynb #e568bade
@dataclass
class Part:
    "A normalized content part."
    type: str
    text: str = None
    data: dict = None

# %% ../nbs/00_types.ipynb #aa3cfc23
PartType = str_enum('PartType', 'text', 'thinking', 'refusal', 'tool_use', 'server_tool_result', 'tool_result',
                    'input_image', 'input_audio', 'input_video', 'input_file')

# %% ../nbs/00_types.ipynb #2eeff103
def _trunc_strs(o, n=200):
    "Truncate str or dict"
    if not o: return o
    if isinstance(o,str) and len(o)>n: return o[:100]+'...'
    if isinstance(o,dict): return {k: (v[:100]+'...' if isinstance(v,str) and len(v)>n else v) for k,v in o.items()}
    return o

@patch
def _repr_markdown_(self: Part):
    body = _trunc_strs(self.text) if self.text else ''
    data = _trunc_strs(self.data)
    return f"""**Part** (`{self.type}`)

{body}

<details markdown='1'>

- data: `{data}`

</details>"""

# %% ../nbs/00_types.ipynb #afeb9eef
@dataclass
class Msg:
    "A normalized message."
    role: str
    content: List[Part]

    def _repr_markdown_(self):
        return f"""**Msg**

- role: `{self.role}`

<contents>

{'\n\n'.join(p._repr_markdown_() for p in self.content)}

</contents>"""

# %% ../nbs/00_types.ipynb #f6d04920
@dataclass
class ToolCall:
    "Normalized tool call."
    id: str
    name: str
    arguments: dict = field(default_factory=dict)
    server: bool = False
    extra: dict = field(default_factory=dict)

# %% ../nbs/00_types.ipynb #509cfc99
@patch
def _repr_markdown_(self: ToolCall):
    extra = _trunc_strs(self.extra)
    return f"""🔧 **{self.name}**(`{self.arguments}`)

<details markdown='1'>

- id: `{self.id}`
- server: `{self.server}`
- extra: `{extra}`

</details>"""

def display_list(l): 
    from IPython.display import Markdown, display
    display(Markdown('\n\n'.join(o._repr_markdown_() for o in l)))

# %% ../nbs/00_types.ipynb #802ad832
@dataclass(frozen=True)
class Usage:
    "Normalized usage."
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    cached_tokens: int = 0
    cache_creation_tokens: int = 0
    reasoning_tokens: int = 0
    raw: dict = field(default_factory=dict)


# %% ../nbs/00_types.ipynb #297a1672
@dataclass(frozen=True)
class Completion:
    "Normalized completion response."
    model: str
    message: Msg
    finish_reason: str = None
    usage: Usage = None
    tool_calls: List[ToolCall] = field(default_factory=list)
    api_name: str = None
    vendor_name: str = None
    raw: dict = field(default_factory=dict)

# %% ../nbs/00_types.ipynb #1b0dbab0
@patch
def _repr_markdown_(self: Completion):
    message = self.message
    content = ''
    for p in message.content:
        if p.type == PartType.thinking:
            if p.text: content += f"<details><summary>Thinking</summary>\n\n{p.text}\n\n</details>\n\n"
        elif txt := p.text: content += txt
    if self.tool_calls:
        tool_calls = [f"\n\n🔧 {tc.name}({tc.arguments})\n" for tc in self.tool_calls]
        content += "\n".join(tool_calls)
    # for img in getattr(message, 'images', []): content += f"\n\n![generated image]({nested_idx(img, 'image_url', 'url')})" # TODO
    details = [f"model: `{self.model}`", f"finish_reason: `{self.finish_reason}`", f"usage: `{self.usage}`"]
    det_str = '\n- '.join(details)    
    return f"""{content}

<details markdown='1'>

- {det_str}

</details>"""

# %% ../nbs/00_types.ipynb #ce59e431
FinishReason = str_enum('finish_reason', 'stop', 'tool_calls', 'length', 'content_filter')

# %% ../nbs/00_types.ipynb #fc681c52
class APIRegistry:
    def __init__(self): self.apis = {}
    def register(self, name, finalize_usage=noop, **kwargs): self.apis[name] = SimpleNamespace(finalize_usage=finalize_usage, **kwargs)

api_registry = APIRegistry()


# %% ../nbs/00_types.ipynb #d58a5f96
def mk_completion(resp, model, api_name, vendor_name):
    "Normalize an api response into Completion."
    api = api_registry.apis[api_name]
    tcs = api.norm_tool_calls(resp)
    parts = api.norm_parts(resp)
    usg = api.finalize_usage(api.norm_usage(resp), parts)
    return Completion(
        model=model,
        message=Msg(role="assistant", content=parts),
        finish_reason=api.norm_finish(resp, tcs),
        usage=usg,
        tool_calls=tcs,
        api_name=api_name,
        vendor_name=vendor_name,
        raw=resp)

# %% ../nbs/00_types.ipynb #d5322db5
def mk_tool_res_msg(tool_calls:list[ToolCall], results:list[str|list]):
    'A util to prepare parallel tool call with str or media list results'
    parts = []
    for tc,res in zip(tool_calls, results):
        data = dict(id=tc.id, name=tc.name, arguments=tc.arguments, server=tc.server)
        parts.append(Part(type=PartType.tool_result, text=res, data=data))
    return Msg(role="tool", content=parts)

# %% ../nbs/00_types.ipynb #8a8e468b
def fn_schema(t):
    "Extract (name, description, parameters) from any tool format."
    if not isinstance(t, dict): return None
    fn = t.get('function')
    if isinstance(fn, dict): return fn.get('name',''), fn.get('description',''), fn.get('parameters',{})
    if 'name' in t and ('parameters' in t or 'input_schema' in t):
        return t.get('name',''), t.get('description',''), t.get('parameters', t.get('input_schema',{}))
    return None

# %% ../nbs/00_types.ipynb #d1d48d91
def sys_text(system):
    "Extract text from system (str or Part)."
    if system is None: return None
    return system if isinstance(system, str) else system.text

def part_txt(p): return p.text if isinstance(p,Part) else p

# %% ../nbs/00_types.ipynb #f3deb055
@flexicache(time_policy(24*3600))
def _fetch_url_partial(url, nbytes=512): 
    "Fetch remote media bytes, optionally only first `nbytes`."
    try:
        with httpx.stream('GET', url, headers={'Range': f'bytes=0-{nbytes-1}'}, follow_redirects=True) as r:
            if r.status_code not in (200, 206): return
            return r.read()
    except (httpx.HTTPError, httpx.InvalidURL): return

# %% ../nbs/00_types.ipynb #70a9a0c3
_ext_mime = {
    '.jpg':'image/jpeg', '.jpeg':'image/jpeg', '.png':'image/png', '.gif':'image/gif', '.webp':'image/webp',
    '.pdf':'application/pdf',
    '.mp3':'audio/mpeg', '.wav':'audio/wav', '.ogg':'audio/ogg', '.flac':'audio/flac', '.m4a':'audio/mp4',
    '.mp4':'video/mp4', '.mov':'video/quicktime', '.webm':'video/webm',
}

def data_url(url):
    "Parse data:mime;base64,data URL into (mime, b64_data), or None."
    if not isinstance(url, str) or not url.startswith('data:') or ',' not in url: return None
    header, body = url.split(',', 1)
    if ';base64' not in header or not body: return None
    return header[5:].split(';',1)[0].strip() or 'application/octet-stream', body

def url_mime(url, default='application/octet-stream'):
    "Guess mime from URL extension, and optional bytes fallback."
    if "youtube.com" in url or "youtu.be" in url: return "video/mp4"
    ext = '.' + url.rsplit('.', 1)[-1].split('?')[0].lower() if '.' in url.split('?')[0].split('/')[-1] else ''
    if (mime:=_ext_mime.get(ext)) is None: return detect_mime(_fetch_url_partial(url))
    return ifnone(mime, default)

# %% ../nbs/00_types.ipynb #28c698fe
def payload_kwargs(msgs, model, stream=False, system=None, max_tokens=None, temperature=None, tools=None, tool_choice=None, reasoning_effort=None, web_search_options=None, stop_callables=None): pass

# %% ../nbs/00_types.ipynb #c2a2cb49
def get_api_key(api_key, default):
    key = api_key or os.getenv(default)
    if not key: raise ValueError(f"Missing API key: set environment variable '{default}' or pass `api_key` parameter")
    return key

# %% ../nbs/00_types.ipynb #852adecd
model_prices_url = 'https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json'

@flexicache(time_policy(24*60*60))
def model_prices_meta(): return urljson(model_prices_url)

# %% ../nbs/00_types.ipynb #68e488d8
def infer_api_name(model):
    "Infer api_name from model"
    if "claude" in model: return 'anthropic'
    if "gemini" in model: return 'gemini'
    if any(o in model for o in ('gpt','o3-','o4-')): return 'openai'

# %% ../nbs/00_types.ipynb #2f0720c2
@flexicache(time_policy(24*60*60))
def get_model_meta(model, vendor_name=None, tfm=noop):
    "Look up cost metadata for `model` from litellm price map, using `vendor_name` prefix if needed."
    vendor_name = ifnone(vendor_name, infer_api_name(model))
    mp, key = model_prices_meta(), ''
    if model in mp: key = model
    elif vendor_name=='gemini' and model.startswith('models/'): key = f"gemini/{model.removeprefix('models/')}"
    elif vendor_name:                                           key = f"{vendor_name}/{model}"
    return dict2obj(tfm(mp.get(key), model, vendor_name))

# %% ../nbs/00_types.ipynb #60607e23
haik45 = "claude-haiku-4-5"
sonn45 = "claude-sonnet-4-5"
sonn = sonn46 = "claude-sonnet-4-6"
opus46 = "claude-opus-4-6"
opus = "claude-opus-4-7"
gpt54 = "gpt-5.4"
gpt54m = "gpt-5.4-mini"
gpt55 = "gpt-5.5"
codex54 = "gpt-5.4"
codex54m = "gpt-5.4-mini"
codex55 = "gpt-5.5"
codex53spark = "gpt-5.3-codex-spark"

# %% ../nbs/00_types.ipynb #583e017b
model_info_registry = {}

def register_model_info(model, vendor_name=None, base=None, base_vendor_name=None, **overrides):
    "Register model metadata, optionally starting from `base`."
    info = dict(get_model_info(base, base_vendor_name or vendor_name)) if base else {}
    info.update(overrides)
    model_info_registry[vendor_name, model] = info

def get_model_info(mn, vendor_name=None):
    info = model_info_registry.get((vendor_name, mn)) or get_model_meta(mn, vendor_name)
    if 'search_context_cost_per_query' in info: info['supports_web_search'] = True
    return dict2obj(info)

# %% ../nbs/00_types.ipynb #8261dcd0
register_model_info('accounts/fireworks/models/qwen3p6-plus', vendor_name='fireworks_ai',
    supports_vision=True, supports_reasoning=True, supports_function_calling=True, supports_tool_choice=True,
    supports_system_messages=True, supports_response_schema=True, supports_parallel_function_calling=True,
    supports_prompt_caching=True, supports_native_streaming=True, supports_native_structured_output=True,
    max_tokens=1000000, max_input_tokens=1000000, max_output_tokens=65536,
    input_cost_per_token=0.5e-6, cache_read_input_token_cost=0.1e-6, output_cost_per_token=3.0e-6)

register_model_info('gemini-3.5-flash', vendor_name='gemini', base='gemini-3-flash-preview',
    input_cost_per_token=1.5e-6, output_cost_per_token=9e-6,
    output_cost_per_reasoning_token=9e-6, cache_read_input_token_cost=1.5e-7)

for model in ('gpt-5.4', 'gpt-5.4-mini'):
    register_model_info(model, vendor_name='openai', base=model, supports_web_search=True, mode=None)

for model in ('kimi-k2.5', 'kimi-k2.6'):
    register_model_info(model, vendor_name='moonshot', base=f'moonshot/{model}', base_vendor_name=None,
        supports_reasoning=True, supports_vision=True, supports_assistant_prefill=True)

register_model_info('gemini-3.1-flash-lite', vendor_name='gemini', base='gemini-3.1-flash-lite-preview')
register_model_info('models/gemini-3.1-flash-lite', vendor_name='gemini', base='gemini-3.1-flash-lite-preview')

for model in ('accounts/fireworks/models/kimi-k2p5', 'accounts/fireworks/models/kimi-k2p6'):
    register_model_info(model, vendor_name='fireworks_ai', base=model.replace('k2p6', 'k2p5'),
        supports_reasoning=True, supports_vision=True,
        input_cost_per_token=0.95e-6, cache_read_input_token_cost=0.16e-6, output_cost_per_token=4.0e-6)

# %% ../nbs/00_types.ipynb #948d55d0
deepseek_v4_common = dict(
    supports_assistant_prefill=True, supports_function_calling=True, supports_prompt_caching=True,
    supports_reasoning=True, supports_tool_choice=True,
    max_input_tokens=1048576, max_output_tokens=393216, max_tokens=393216)

register_model_info('deepseek-v4-flash', vendor_name='deepseek', base='deepseek/deepseek-v3.2', **deepseek_v4_common,
    input_cost_per_token=1.4e-07, input_cost_per_token_cache_hit=2.8e-09,
    output_cost_per_token=2.8e-07, cache_read_input_token_cost=1.4e-07/10)
register_model_info('deepseek-v4-pro', vendor_name='deepseek', base='deepseek/deepseek-v3.2', **deepseek_v4_common,
    input_cost_per_token=4.35e-07, input_cost_per_token_cache_hit=3.625e-09,
    output_cost_per_token=8.7e-07, cache_read_input_token_cost=4.35e-07/10)

# %% ../nbs/00_types.ipynb #2c23d11e
codex_pricing = dict(
    input_cost_per_token = 0.10/1_000_000, output_cost_per_token = 0.50/1_000_000,
    cache_creation_input_token_cost = 0.10/1_000_000, cache_read_input_token_cost = 0.10/1_000_000)

for model in (codex54, codex54m, codex55):
    register_model_info(model, 'codex', base=model, base_vendor_name='chatgpt', supports_web_search=True, **codex_pricing)

register_model_info(codex53spark, 'codex', **codex_pricing,
    supports_vision=False, supports_image_input=False, supports_web_search=True, supports_reasoning=True, supports_function_calling=True,
    max_tokens=128000, max_input_tokens=128000, max_output_tokens=128000)

# %% ../nbs/00_types.ipynb #24cc47ec
def get_model_pricing(mn, vendor_name, million=True):
    return {k:round(v * (1e6 if million else 1), 6)
        for k,v in get_model_info(mn, vendor_name).items()
        if 'cost' in k and isinstance(v,float) and 'priority' not in k}

# %% ../nbs/00_types.ipynb #79304cd9
def approx_pricing(nm, vendor_name, out=10, cache=80, inp=10, markup=0):
    "Approx cost per million tokens with given output/cache/input proportions"
    p = get_model_pricing(nm, vendor_name)
    ic = p.get('cache_creation_input_token_cost', p['input_cost_per_token'])
    res = (p['output_cost_per_token']*out + p['cache_read_input_token_cost']*cache + ic*inp) / (out+cache+inp)
    if nm=='claude-opus-4-7': res *= 1.5
    return res*(1+markup)

# %% ../nbs/00_types.ipynb #8bfca02d
@patch(as_prop=True)
def cost(self:Completion):
    meta = dict2obj(get_model_info(self.model, self.vendor_name))
    api = api_registry.apis[self.api_name]
    if not hasattr(api, 'cost'): raise NotImplementedError(f"API: {self.api_name} doesn't have a registered `cost` function in ns")
    return api.cost(self.usage, meta)
