"""Core internal types."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_types.ipynb.

# %% auto #0
__all__ = ['FinishReason', 'api_registry', 'model_prices_url', 'haik45', 'sonn45', 'sonn46', 'sonn', 'sonn5', 'opus46', 'opus48',
           'opus', 'opus5', 'fable', 'fable5', 'gpt54', 'gpt54m', 'gpt55', 'codex54', 'codex54m', 'codex55',
           'codex53spark', 'model_info_registry', 'modern_llm', 'deepseek_v4_common', 'mimo_v25_common',
           'codex_pricing', 'sol', 'terra', 'luna', 'gpt56s', 'Usage', 'APIRegistry', 'mk_completion', 'fn_schema',
           'payload_kwargs', 'get_api_key', 'wrap_typed', 'unwrap_typed', 'resize_b64', 'model_prices_meta',
           'infer_api_name', 'get_model_meta', 'register_model_info', 'get_model_info', 'get_model_pricing',
           'approx_pricing', 'is_deepseek_peak_hour', 'price_tier', 'tier_rate']

# %% ../nbs/00_types.ipynb #b4d047fd
import httpx2, base64, io
from importlib.metadata import entry_points
from datetime import datetime, timezone
from fastcore.utils import *
from PIL import Image as PImg
from aidialog.msg_parts import Msg, Thinking, ToolUse, Completion, StopResponse, FullResponse


# %% ../nbs/00_types.ipynb #802ad832
class Usage(BasicRepr):
    "Normalized usage."
    def __init__(self, prompt_tokens=0, completion_tokens=0, total_tokens=0, cached_tokens=0,
        cache_creation_tokens=0, reasoning_tokens=0, raw=None):
        if raw is None: raw = {}
        store_attr()
    def __eq__(self, o): return type(o) is type(self) and self.__dict__ == o.__dict__


# %% ../nbs/00_types.ipynb #4901e693
@patch(as_prop=True)
def formatted(self:Completion): return ''

# %% ../nbs/00_types.ipynb #1b0dbab0
@patch
def _repr_markdown_(self: Completion):
    content = ''
    for p in self.message.content:
        if isinstance(p, Thinking):
            if p.text: content += f"\n::: details\n## Thinking\n\n{p.text}\n\n:::\n\n"
        elif isinstance(p, ToolUse): content += f"\n\n🔧 {p.name}({p.arguments})\n"
        elif txt := p.text: content += txt
    details = [f"model: `{self.model}`", f"finish_reason: `{self.finish_reason}`", f"usage: `{self.usage}`"]
    det_str = '\n- '.join(details)    
    return f"""{content}

::: details

- {det_str}

:::"""

# %% ../nbs/00_types.ipynb #ce59e431
FinishReason = str_enum('finish_reason', 'stop', 'tool_calls', 'length', 'content_filter')

# %% ../nbs/00_types.ipynb #fc681c52
class APIRegistry(dict):
    _eps = None
    def register(self, name, finalize_usage=noop, **kwargs): self[name] = SimpleNamespace(finalize_usage=finalize_usage, **kwargs)
    def _load(self, name):
        "Import the plugin providing api `name` from the `fastllm.apis` entry-point group; its import registers the api."
        if self._eps is None: self._eps = {o.name:o for o in entry_points(group='fastllm.apis')}
        if name in self._eps: self._eps[name].load()
        return dict.__contains__(self, name)
    def __contains__(self, name): return dict.__contains__(self, name) or self._load(name)
    def __missing__(self, name):
        if self._load(name): return self[name]
        raise KeyError(name)

api_registry = APIRegistry()


# %% ../nbs/00_types.ipynb #d58a5f96
def mk_completion(resp, model, api_name, vendor_name):
    "Normalize an api response into Completion."
    resp = obj2dict(resp)
    api = api_registry[api_name]
    tcs = api.norm_tool_calls(resp)
    parts = api.norm_parts(resp)
    usg = api.finalize_usage(api.norm_usage(resp), parts)
    return Completion(model=model, message=Msg(role="assistant", content=parts), finish_reason=api.norm_finish(resp, tcs),
        usage=usg, api_name=api_name, vendor_name=vendor_name, raw=resp)

# %% ../nbs/00_types.ipynb #8a8e468b
def fn_schema(t):
    "Extract (name, description, parameters) from any tool format."
    if not isinstance(t, dict): return None
    fn = t.get('function')
    if isinstance(fn, dict): return fn.get('name',''), fn.get('description',''), fn.get('parameters',{})
    if 'name' in t and ('parameters' in t or 'input_schema' in t):
        return t.get('name',''), t.get('description',''), t.get('parameters', t.get('input_schema',{}))
    return None

# %% ../nbs/00_types.ipynb #28c698fe
def payload_kwargs(msgs, model, stream=False, system=None, max_tokens=None, temperature=None, tools=None, tool_choice=None,
    reasoning_effort=None, web_search_options=None, cache_idxs=None, ttl=None, stop_callables=None): pass

# %% ../nbs/00_types.ipynb #c2a2cb49
def get_api_key(api_key, default):
    key = api_key or os.getenv(default)
    if not key: raise ValueError(f"Missing API key: set environment variable '{default}' or pass `api_key` parameter")
    return key

# %% ../nbs/00_types.ipynb #e6e9ac99
_typed_re = re.compile(r'^𝍁(\w+)𝍁(.+)$', re.S)
_typed_strs = {c.__name__: c for c in (StopResponse, FullResponse)}

def wrap_typed(s):
    "Mark `s` with a `𝍁TypeName𝍁` prefix when it is a `str` subclass, so the type survives a plain-string wire"
    return s if type(s) is str else f'𝍁{type(s).__name__}𝍁{s}'

def unwrap_typed(s):
    "Rebuild the named `str` subclass from a `𝍁`-marked string; unknown names get a minted ephemeral type"
    if not (m := _typed_re.match(s)): return s
    nm,body = m.groups()
    return _typed_strs.setdefault(nm, type(nm, (str,), {}))(body)

# %% ../nbs/00_types.ipynb #25e9cd60
def resize_b64(b64, max_sz):
    "Resize a base64 image data to a max long edge, preserving aspect ratio."
    img = PImg.open(io.BytesIO(base64.b64decode(b64)))
    if max(img.size) < max_sz: return b64
    img.thumbnail((max_sz,max_sz), PImg.Resampling.LANCZOS)
    fmt = (img.format or 'PNG').upper()
    if fmt=='JPG': fmt = 'JPEG'
    buf = io.BytesIO()
    img.save(buf, format=fmt)
    return base64.b64encode(buf.getvalue()).decode()

# %% ../nbs/00_types.ipynb #852adecd
model_prices_url = 'https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json'

def model_prices_meta():
    "Download model prices to the module dir once, then load from disk."
    p = Path(__file__).parent/'model_prices.json'
    if not p.exists(): p.write_text(httpx2.get(model_prices_url, follow_redirects=True).text)
    return loads(p.read_text())

# %% ../nbs/00_types.ipynb #68e488d8
def infer_api_name(model):
    "Infer api_name from model"
    if "claude" in model: return 'anthropic'
    if "gemini" in model: return 'gemini'
    if any(o in model for o in ('gpt','o3-','o4-')): return 'openai'

# %% ../nbs/00_types.ipynb #2f0720c2
def get_model_meta(model, vendor_name=None, tfm=noop):
    "Look up cost metadata for `model` from litellm price map, using `vendor_name` prefix if needed."
    vendor_name = ifnone(vendor_name, infer_api_name(model))
    mp, key = model_prices_meta(), ''
    if model in mp: key = model
    elif vendor_name=='gemini' and model.startswith('models/'): key = f"gemini/{model.removeprefix('models/')}"
    elif vendor_name:                                           key = f"{vendor_name}/{model}"
    return dict2obj(tfm(mp.get(key, {}), model, vendor_name))

# %% ../nbs/00_types.ipynb #60607e23
haik45 = "claude-haiku-4-5"
sonn45 = "claude-sonnet-4-5"
sonn46 = "claude-sonnet-4-6"
sonn = sonn5 = "claude-sonnet-5"
opus46 = "claude-opus-4-6"
opus48 = "claude-opus-4-8"
opus = opus5 = "claude-opus-5"
fable = fable5 = 'claude-fable-5'
gpt54 = "gpt-5.4"
gpt54m = "gpt-5.4-mini"
gpt55 = "gpt-5.5"
codex54 = "gpt-5.4"
codex54m = "gpt-5.4-mini"
codex55 = "gpt-5.5"
codex53spark = "gpt-5.3-codex-spark"

# %% ../nbs/00_types.ipynb #583e017b
model_info_registry = {}

def register_model_info(model, vendor_name=None, base=None, base_vendor_name=None, **overrides):
    "Register model metadata, optionally starting from `base`."
    info = dict(get_model_info(base, base_vendor_name or vendor_name)) if base else {}
    info.update(overrides)
    if isinstance(c := info.get('search_context_cost_per_query'), (int,float)):
        info['search_context_cost_per_query'] = {f'search_context_size_{s}':c for s in ('low','medium','high')}
    model_info_registry[vendor_name, model] = info

def get_model_info(mn, vendor_name=None):
    info = model_info_registry.get((vendor_name, mn)) or get_model_meta(mn, vendor_name)
    if 'search_context_cost_per_query' in info: info['supports_web_search'] = True
    return dict2obj(info)

# %% ../nbs/00_types.ipynb #b36178d4
modern_llm = dict(supports_function_calling=True, supports_tool_choice=True, supports_prompt_caching=True,
    supports_parallel_function_calling=True, supports_native_streaming=True, supports_native_structured_output=True,
    supports_reasoning=True, supports_response_schema=True, supports_system_messages=True)

# %% ../nbs/00_types.ipynb #8261dcd0
register_model_info('accounts/fireworks/models/qwen3p7-plus', vendor_name='fireworks_ai', **modern_llm, supports_vision=True,
    max_tokens=1000000, max_input_tokens=1000000, max_output_tokens=65536,
    input_cost_per_token=0.4e-6, cache_read_input_token_cost=0.08e-6, output_cost_per_token=1.6e-6)

register_model_info('accounts/fireworks/models/qwen3p6-plus', vendor_name='fireworks_ai', **modern_llm, supports_vision=True,
    max_tokens=1000000, max_input_tokens=1000000, max_output_tokens=65536,
    input_cost_per_token=0.5e-6, cache_read_input_token_cost=0.1e-6, output_cost_per_token=3.0e-6)

register_model_info('accounts/fireworks/models/glm-5p2', vendor_name='fireworks_ai', **modern_llm, supports_vision=False,
    max_tokens=1000000, max_input_tokens=1000000, max_output_tokens=65536,
    input_cost_per_token=1.4e-6, cache_read_input_token_cost=0.14e-6, output_cost_per_token=4.4e-6)

register_model_info('accounts/fireworks/routers/glm-5p2-fast', vendor_name='fireworks_ai', **modern_llm, supports_vision=False,
    max_tokens=1000000, max_input_tokens=1000000, max_output_tokens=65536,
    input_cost_per_token=2.8e-6, cache_read_input_token_cost=0.28e-6, output_cost_per_token=8.8e-6)

register_model_info('gemini-3.5-flash', vendor_name='gemini', base='gemini-3-flash-preview',
    input_cost_per_token=1.5e-6, output_cost_per_token=9e-6, output_cost_per_reasoning_token=9e-6, cache_read_input_token_cost=1.5e-7)

register_model_info('gpt-5.4', vendor_name='openai', base='gpt-5.4', supports_web_search=True, mode=None)
# Upstream metadata says 1,050,000 input tokens for gpt-5.4-mini, but OpenAI documents a 272k limit
register_model_info('gpt-5.4-mini', vendor_name='openai', base='gpt-5.4-mini', supports_web_search=True, mode=None, max_input_tokens=272_000)

for model in ('kimi-k2.5', 'kimi-k2.6' , 'kimi-k3'):
    register_model_info(model, vendor_name='moonshot', base=f'moonshot/{model}', base_vendor_name=None,
        supports_reasoning=True, supports_vision=True)

register_model_info('gemini-3.1-flash-lite', vendor_name='gemini', base='gemini-3.1-flash-lite-preview')
register_model_info('models/gemini-3.1-flash-lite', vendor_name='gemini', base='gemini-3.1-flash-lite-preview')

register_model_info('accounts/fireworks/models/kimi-k2p5', vendor_name='fireworks_ai', base='accounts/fireworks/models/kimi-k2p5',
    supports_reasoning=True, supports_vision=True,
    input_cost_per_token=0.60e-6, cache_read_input_token_cost=0.10e-6, output_cost_per_token=3.0e-6)
register_model_info('accounts/fireworks/models/kimi-k2p6', vendor_name='fireworks_ai', base='accounts/fireworks/models/kimi-k2p5',
    supports_reasoning=True, supports_vision=True,
    input_cost_per_token=0.95e-6, cache_read_input_token_cost=0.16e-6, output_cost_per_token=4.0e-6)
register_model_info('kimi-k2.7-code', vendor_name='moonshot', base='kimi-k2.6',
    input_cost_per_token=0.95e-6, cache_read_input_token_cost=0.19e-6, output_cost_per_token=4.0e-6)
register_model_info('kimi-k3', vendor_name='moonshot', base='kimi-k2.6', supports_reasoning=True, supports_vision=True,
    max_input_tokens=1_000_000, input_cost_per_token=3e-6, cache_read_input_token_cost=0.30e-6, output_cost_per_token=15.0e-6)

# %% ../nbs/00_types.ipynb #948d55d0
deepseek_v4_common = dict(**modern_llm, max_input_tokens=1048576, max_output_tokens=393216, max_tokens=393216)

register_model_info('deepseek-v4-flash', vendor_name='deepseek', base='deepseek/deepseek-v3.2', **deepseek_v4_common,
    input_cost_per_token=1.4e-07, input_cost_per_token_cache_hit=2.8e-09,
    output_cost_per_token=2.8e-07, cache_read_input_token_cost=1.4e-07/10)
register_model_info('deepseek-v4-pro', vendor_name='deepseek', base='deepseek/deepseek-v3.2', **deepseek_v4_common,
    input_cost_per_token=4.35e-07, input_cost_per_token_cache_hit=3.625e-09,
    output_cost_per_token=8.7e-07, cache_read_input_token_cost=4.35e-07/10)

mimo_v25_common = dict(**modern_llm, supports_web_search=True, max_input_tokens=1048576, max_output_tokens=131072, max_tokens=131072)

register_model_info('mimo-v2.5-pro', vendor_name='mimo', **mimo_v25_common, base='deepseek-v4-pro', base_vendor_name='deepseek',
    input_cost_per_token=0.435e-6, output_cost_per_token=0.87e-6, cache_read_input_token_cost=0.0036e-6, search_context_cost_per_query=0.005)
register_model_info('mimo-v2.5', vendor_name='mimo', **mimo_v25_common, base='deepseek-v4-pro', base_vendor_name='deepseek',
    input_cost_per_token=0.14e-6,  output_cost_per_token=0.28e-6, cache_read_input_token_cost=0.0028e-6, search_context_cost_per_query=0.005,
    supports_vision=True, supports_image_input=True)
register_model_info('mimo-v2.5-pro-ultraspeed', vendor_name='mimo', **mimo_v25_common, base='deepseek-v4-pro', base_vendor_name='deepseek',
    input_cost_per_token=1.305e-6, output_cost_per_token=2.61e-6, cache_read_input_token_cost=0.0108e-6, search_context_cost_per_query=0.005)

# %% ../nbs/00_types.ipynb #defb1c5c
register_model_info('MiniMax-M3', vendor_name='minimax', **modern_llm, max_input_tokens=512_000, max_output_tokens=512_000, max_tokens=512_000,
    input_cost_per_token=0.3e-6, output_cost_per_token=1.2e-6, cache_read_input_token_cost=0.06e-6, supports_vision=True, supports_video_input=True)

# %% ../nbs/00_types.ipynb #4e1b40b3
register_model_info('muse-spark-1.1', vendor_name='meta_ai', **modern_llm, max_input_tokens=1_048_576, max_output_tokens=128000, max_tokens=128000,
    supports_vision=True, supports_image_input=True, supports_video_input=True, supports_pdf_input=True, supports_web_search=True,
    search_context_cost_per_query=0.0025, input_cost_per_token=1.25e-6, output_cost_per_token=4.25e-6, cache_read_input_token_cost=0.15e-6)

# %% ../nbs/00_types.ipynb #5a2b3430
# z.ai list pricing (a 50% discount applies until 2026-09-09)
register_model_info('glm-5.3-flash', vendor_name='zai', base='glm-5.1', **modern_llm,
    supports_vision=True, supports_image_input=True,
    max_input_tokens=1_000_000, max_output_tokens=128_000, max_tokens=128_000,
    input_cost_per_token=0.15e-6, cache_read_input_token_cost=0.03e-6, output_cost_per_token=0.5e-6)

# %% ../nbs/00_types.ipynb #2c23d11e
codex_pricing = dict(input_cost_per_token = 0.10/1_000_000, output_cost_per_token = 0.50/1_000_000,
    cache_creation_input_token_cost = 0.10/1_000_000, cache_read_input_token_cost = 0.10/1_000_000)

def _rm_ctx_tiers(vendor_name, model):
    "Drop upstream context-tier rates, which would otherwise override flat subscription pricing"
    info = model_info_registry[vendor_name, model]
    for k in [k for k in info if re.search(r'_above_\d+k_tokens', k)]: del info[k]

for model in (codex54, codex54m, codex55):
    register_model_info(model, 'codex', base=model, base_vendor_name='chatgpt', supports_web_search=True, max_input_tokens=256000, **codex_pricing)
    _rm_ctx_tiers('codex', model)

register_model_info(codex53spark, 'codex', **codex_pricing,
    supports_vision=False, supports_image_input=False, supports_web_search=True, supports_reasoning=True, supports_function_calling=True,
    max_tokens=128000, max_input_tokens=128000, max_output_tokens=128000)

# %% ../nbs/00_types.ipynb #5d3e4720
for model in (haik45, sonn45, sonn46, sonn5, opus46, opus48, opus5, fable5):
    register_model_info(model, 'claude_code', base=model, base_vendor_name='anthropic', **codex_pricing)

# %% ../nbs/00_types.ipynb #bb0c4c2a
sol,terra,luna = gpt56s = 'gpt-5.6-sol gpt-5.6-terra gpt-5.6-luna'.split()
for model in ['gpt-5.6']+gpt56s: register_model_info(model, 'openai', base=model, base_vendor_name='openai')
# Codex serves only the suffixed names; bare `gpt-5.6` is rejected with a ChatGPT account.
# Its window is smaller than the API's: 371,331 input tokens is accepted and 371,981 is not, on all three.
for model in gpt56s:
    register_model_info(model, 'codex', base=model, base_vendor_name='openai', max_input_tokens=371_000, **codex_pricing)
    _rm_ctx_tiers('codex', model)

# %% ../nbs/00_types.ipynb #24cc47ec
def get_model_pricing(mn, vendor_name, million=True):
    return {k:round(v * (1e6 if million else 1), 6) for k,v in get_model_info(mn, vendor_name).items()
        if 'cost' in k and isinstance(v,float) and 'priority' not in k}

# %% ../nbs/00_types.ipynb #79304cd9
def approx_pricing(nm, vendor_name, out=10, cache=80, inp=10, markup=0):
    "Approx cost per million tokens with given output/cache/input proportions"
    p = get_model_pricing(nm, vendor_name)
    ic = p.get('cache_creation_input_token_cost', p['input_cost_per_token'])
    res = (p['output_cost_per_token']*out + p['cache_read_input_token_cost']*cache + ic*inp) / (out+cache+inp)
    if vendor_name=='anthropic': res *= 1.5
    return res*(1+markup)

# %% ../nbs/00_types.ipynb #d2a310fb
def is_deepseek_peak_hour(dt=None):
    "Check whether current UTC time is in DeepSeek peak pricing hours."
    dt = dt or datetime.now(timezone.utc)
    h = dt.hour + dt.minute/60
    return 1 <= h < 4 or 6 <= h < 10

# %% ../nbs/00_types.ipynb #4c701619
def price_tier(meta, n):
    "Suffix of the pricing tier applying to `n` prompt tokens, or '' for base rates."
    o = first(o for k in meta if (o:=re.match(r'input_cost_per_token(_above_(\d+)k_tokens)$', k)))
    return o[1] if o and n>int(o[2])*1000 else ''

# %% ../nbs/00_types.ipynb #956d2495
def tier_rate(meta, key, tier):
    "Rate for `key` at `tier`, falling back to the base key."
    return meta.get(f'{key}{tier}') or meta[key]

# %% ../nbs/00_types.ipynb #8bfca02d
@patch(as_prop=True)
def cost(self:Completion):
    meta = dict2obj(get_model_info(self.model, self.vendor_name))
    api = api_registry[self.api_name]
    if not hasattr(api, 'cost'): raise NotImplementedError(f"API: {self.api_name} doesn't have a registered `cost` function in ns")
    res = api.cost(self.usage, meta)
    return res*2 if self.vendor_name=='deepseek' and self.model.startswith('deepseek-v4') and is_deepseek_peak_hour() else res
