"""Core internal types."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_types.ipynb.

# %% auto #0
__all__ = ['PartType', 'FinishReason', 'api_registry', 'model_prices_url', 'haik45', 'sonn45', 'sonn', 'sonn46', 'opus46', 'opus',
           'gpt54', 'gpt54m', 'codex54', 'codex55', 'codex53spark', 'codex_pricing', 'Part', 'Msg', 'ToolCall',
           'display_list', 'Usage', 'Completion', 'APIRegistry', 'mk_completion', 'mk_tool_res_msg', 'fn_schema',
           'sys_text', 'part_txt', 'data_url', 'url_mime', 'payload_kwargs', 'get_api_key', 'model_prices_meta',
           'infer_api_name', 'get_model_meta', 'get_model_info']

# %% ../nbs/00_types.ipynb #b4d047fd
from dataclasses import dataclass, field
from fastcore.net import urljson
from fastcore.utils import *

# %% ../nbs/00_types.ipynb #e568bade
@dataclass
class Part:
    "A normalized content part."
    type: str
    text: str = None
    data: dict = None

# %% ../nbs/00_types.ipynb #aa3cfc23
PartType = str_enum('PartType', 'text', 'thinking', 'refusal', 'tool_use', 'server_tool_result', 'tool_result',
                    'input_image', 'input_audio', 'input_video', 'input_file')

# %% ../nbs/00_types.ipynb #2eeff103
def _trunc_strs(d, n=200):
    "Return copy of dict `d` with str values >n chars truncated to first 10 chars + '...'"
    if not d: return d
    return {k: (v[:10]+'...' if isinstance(v,str) and len(v)>n else v) for k,v in d.items()}

@patch
def _repr_markdown_(self: Part):
    body = self.text if self.text else ''
    data = _trunc_strs(self.data)
    return f"""**Part** (`{self.type}`)

{body}

<details>

- data: `{data}`

</details>"""

# %% ../nbs/00_types.ipynb #afeb9eef
@dataclass
class Msg:
    "A normalized message."
    role: str
    content: List[Part]

    def _repr_markdown_(self):
        return f"""**Msg**

- role: `{self.role}`

<contents>

{'\n\n'.join(p._repr_markdown_() for p in self.content)}

</contents>"""

# %% ../nbs/00_types.ipynb #f6d04920
@dataclass
class ToolCall:
    "Normalized tool call."
    id: str
    name: str
    arguments: dict = field(default_factory=dict)
    server: bool = False
    extra: dict = field(default_factory=dict)

# %% ../nbs/00_types.ipynb #509cfc99
@patch
def _repr_markdown_(self: ToolCall):
    extra = _trunc_strs(self.extra)
    return f"""🔧 **{self.name}**(`{self.arguments}`)

<details>

- id: `{self.id}`
- server: `{self.server}`
- extra: `{extra}`

</details>"""

def display_list(l): 
    from IPython.display import Markdown, display
    display(Markdown('\n\n'.join(o._repr_markdown_() for o in l)))

# %% ../nbs/00_types.ipynb #802ad832
@dataclass(frozen=True)
class Usage:
    "Normalized usage."
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    cached_tokens: int = 0
    cache_creation_tokens: int = 0
    reasoning_tokens: int = 0
    raw: dict = field(default_factory=dict)


# %% ../nbs/00_types.ipynb #297a1672
@dataclass(frozen=True)
class Completion:
    "Normalized completion response."
    model: str
    message: Msg
    finish_reason: str = None
    usage: Usage = None
    tool_calls: List[ToolCall] = field(default_factory=list)
    api_name: str = None
    vendor_name: str = None
    raw: dict = field(default_factory=dict)

# %% ../nbs/00_types.ipynb #1b0dbab0
@patch
def _repr_markdown_(self: Completion):
    message = self.message
    content = ''
    for p in message.content:
        if p.type == PartType.thinking:
            if p.text: content += f"<details><summary>Thinking</summary>\n\n{p.text}\n\n</details>\n\n"
        elif txt := p.text: content += txt
    if self.tool_calls:
        tool_calls = [f"\n\n🔧 {tc.name}({tc.arguments})\n" for tc in self.tool_calls]
        content += "\n".join(tool_calls)
    # for img in getattr(message, 'images', []): content += f"\n\n![generated image]({nested_idx(img, 'image_url', 'url')})" # TODO
    details = [f"model: `{self.model}`", f"finish_reason: `{self.finish_reason}`", f"usage: `{self.usage}`"]
    det_str = '\n- '.join(details)    
    return f"""{content}

<details>

- {det_str}

</details>"""

# %% ../nbs/00_types.ipynb #ce59e431
FinishReason = str_enum('finish_reason', 'stop', 'tool_calls', 'length', 'content_filter')

# %% ../nbs/00_types.ipynb #fc681c52
class APIRegistry:
    def __init__(self): self.apis = {}
    def register(self, name, **kwargs): self.apis[name] = SimpleNamespace(**kwargs)

api_registry = APIRegistry()

# %% ../nbs/00_types.ipynb #d58a5f96
def mk_completion(resp, model, api_name, vendor_name):
    "Normalize an api response into Completion."
    api = api_registry.apis[api_name]
    tcs = api.norm_tool_calls(resp)
    return Completion(
        model=resp.get("model") or model,
        message=Msg(role="assistant", content=api.norm_parts(resp)),
        finish_reason=api.norm_finish(resp, tcs),
        usage=api.norm_usage(resp),
        tool_calls=tcs,
        api_name=api_name,
        vendor_name=vendor_name,
        raw=resp)

# %% ../nbs/00_types.ipynb #d5322db5
def mk_tool_res_msg(tool_calls:list[ToolCall], results:list[str|list]):
    'A util to prepare parallel tool call with str or media list results'
    parts = []
    for tc,res in zip(tool_calls, results):
        data = dict(id=tc.id, name=tc.name, arguments=tc.arguments, server=tc.server)
        parts.append(Part(type=PartType.tool_result, text=res, data=data))
    return Msg(role="tool", content=parts)

# %% ../nbs/00_types.ipynb #8a8e468b
def fn_schema(t):
    "Extract (name, description, parameters) from any tool format."
    if not isinstance(t, dict): return None
    fn = t.get('function')
    if isinstance(fn, dict): return fn.get('name',''), fn.get('description',''), fn.get('parameters',{})
    if 'name' in t and ('parameters' in t or 'input_schema' in t):
        return t.get('name',''), t.get('description',''), t.get('parameters', t.get('input_schema',{}))
    return None

# %% ../nbs/00_types.ipynb #d1d48d91
def sys_text(system):
    "Extract text from system (str or Part)."
    if system is None: return None
    return system if isinstance(system, str) else system.text

def part_txt(p): return p.text if isinstance(p,Part) else p

# %% ../nbs/00_types.ipynb #dc2b75a0
_ext_mime = {
    '.jpg':'image/jpeg', '.jpeg':'image/jpeg', '.png':'image/png', '.gif':'image/gif', '.webp':'image/webp',
    '.pdf':'application/pdf',
    '.mp3':'audio/mpeg', '.wav':'audio/wav', '.ogg':'audio/ogg', '.flac':'audio/flac', '.m4a':'audio/mp4',
    '.mp4':'video/mp4', '.mov':'video/quicktime', '.webm':'video/webm',
}

def data_url(url):
    "Parse data:mime;base64,data URL into (mime, b64_data), or None."
    if not isinstance(url, str) or not url.startswith('data:') or ',' not in url: return None
    header, body = url.split(',', 1)
    if ';base64' not in header or not body: return None
    return header[5:].split(';',1)[0].strip() or 'application/octet-stream', body

def url_mime(url, default='application/octet-stream'):
    "Guess mime from URL extension."
    ext = '.' + url.rsplit('.', 1)[-1].split('?')[0].lower() if '.' in url.split('?')[0].split('/')[-1] else ''
    return _ext_mime.get(ext, default)

# %% ../nbs/00_types.ipynb #28c698fe
def payload_kwargs(msgs, model, stream=False, system=None, max_tokens=None, temperature=None, tools=None, tool_choice=None, reasoning_effort=None, web_search_options=None, stop_callables=None, stop_sequences=None): pass

# %% ../nbs/00_types.ipynb #c2a2cb49
def get_api_key(api_key, default):
    err = ValueError(f"Missing API key: make sure to have the expected env var name or pass `api_key`")
    key = api_key or os.getenv(default)
    if not key: raise err
    return key

# %% ../nbs/00_types.ipynb #852adecd
model_prices_url = 'https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json'
@flexicache(time_policy(24*60*60))
def model_prices_meta(): return urljson(model_prices_url)

# %% ../nbs/00_types.ipynb #68e488d8
def infer_api_name(model):
    "Infer api_name from model"
    if "claude" in model: return 'anthropic'
    if "gemini" in model: return 'gemini'
    if any(o in model for o in ('gpt','o3-','o4-')): return 'openai'

# %% ../nbs/00_types.ipynb #2f0720c2
@flexicache(time_policy(24*60*60))
def get_model_meta(model, vendor_name=None, tfm=noop):
    "Look up cost metadata for `model` from litellm price map, using `vendor_name` prefix if needed."
    vendor_name = ifnone(vendor_name, infer_api_name(model))
    mp = model_prices_meta()
    if model in mp: key = model
    elif vendor_name=='gemini' and model.startswith('models/'): key = f"gemini/{model.removeprefix('models/')}"
    elif vendor_name:                                           key = f"{vendor_name}/{model}"
    return dict2obj(tfm(mp.get(key), model, vendor_name))

# %% ../nbs/00_types.ipynb #60607e23
haik45 = "claude-haiku-4-5"
sonn45 = "claude-sonnet-4-5"
sonn = sonn46 = "claude-sonnet-4-6"
opus46 = "claude-opus-4-6"
opus = "claude-opus-4-7"
gpt54 = "gpt-5.4"
gpt54m = "gpt-5.4-mini"
codex54 = "gpt-5.4"
codex55 = "gpt-5.5"
codex53spark = "gpt-5.3-codex-spark"

# %% ../nbs/00_types.ipynb #d6d5b98c
codex_pricing = {
    "input_cost_per_token": 0.10 / 1_000_000,
    "cache_creation_input_token_cost": 0.10 / 1_000_000,
    "cache_read_input_token_cost": 0.10 / 1_000_000,
    "output_cost_per_token": 0.50 / 1_000_000,
}

_codex_overrides = {
    codex53spark: dict(
        supports_vision=False, supports_image_input=False, supports_web_search=True,
        max_tokens=128000, max_input_tokens=128000, max_output_tokens=128000)
}

# %% ../nbs/00_types.ipynb #fbfdeb0a
def get_model_info(mn, vendor_name=None):
    info = get_model_meta(mn, vendor_name)
    # anthropic web search 
    if 'search_context_cost_per_query' in info: info['supports_web_search'] = True
    # kimi
    if 'kimi' in mn: 
        if 'k2p6' in mn: info = get_model_meta(mn.replace('k2p6', 'k2p5'), vendor_name)
        info['supports_reasoning'] = True
        info['supports_vision'] = True
        if vendor_name == 'moonshot': info['supports_assistant_prefill'] = True
    # gpt web search
    if mn in ("gpt-5.4", "gpt-5.4-mini"):
        info['supports_web_search'] = True
        info.pop('mode', None)
    # codex updates
    if vendor_name == 'codex': 
        info = merge(info, codex_pricing)
        info |= _codex_overrides.get(mn, {})
    # deepseek v4
    if vendor_name == 'deepseek' and mn in ("deepseek-v4-flash", "deepseek-v4-pro"):
        info = dict(get_model_meta("deepseek/deepseek-v3.2"))
        info |= dict(supports_assistant_prefill=True, supports_function_calling=True, supports_prompt_caching=True,
            supports_reasoning=True, supports_tool_choice=True)
        info.update(input_cost_per_token=1.4e-07, input_cost_per_token_cache_hit=2.8e-09, output_cost_per_token=2.8e-07,
            max_input_tokens=1048576, max_output_tokens=393216, max_tokens=393216)
        if 'pro' in mn: info = {**info, 'input_cost_per_token': 4.35e-07, 'input_cost_per_token_cache_hit': 3.625e-09, 'output_cost_per_token': 8.7e-07}
    # qwen 3p6
    if vendor_name == 'fireworks_ai' and mn == 'accounts/fireworks/models/qwen3p6-plus':
        info = dict(supports_vision=True, supports_reasoning=True, supports_function_calling=True, supports_tool_choice=True,
                    supports_system_messages=True, supports_response_schema=True, supports_parallel_function_calling=True,
                    supports_prompt_caching=True, supports_native_streaming=True, supports_native_structured_output=True,
                    max_tokens=1000000, max_input_tokens=1000000, max_output_tokens=65536,
                    input_cost_per_token=0.5e-6, cache_read_input_token_cost=0.1e-6, output_cost_per_token=3.0e-6)
    return dict2obj(info)

# %% ../nbs/00_types.ipynb #8bfca02d
@patch(as_prop=True)
def cost(self:Completion):
    meta = dict2obj(get_model_info(self.model, self.vendor_name))
    api = api_registry.apis[self.api_name]
    if not hasattr(api, 'cost'): raise NotImplementedError(f"API: {self.api_name} doesn't have a registered `cost` function in ns")
    return api.cost(self.usage, meta)
